### ISSUE TITLE
Document default null ordering for Ordering

### ISSUE THREAD

**Issue by JensRantil** [google/guava#1945]
I couldn't find how a `natural()` [`Ordering`](http://docs.guava-libraries.googlecode.com/git-history/release/javadoc/com/google/common/collect/Ordering.html) orders `null`s if not calling if `nullsFirst()`/`nullsLast()` is not called. https://code.google.com/p/guava-libraries/wiki/OrderingExplained didn't give me anything either.

Will the ordering thrown an NPE, or will it default to `nullsFirst()`? Should probably be documented.

Let me know if I've missed something.

**Comment by cpovirk** [comment]
The link you've included takes me to this...

"""
Returns a serializable ordering that uses the natural order of the values. The ordering throws a NullPointerException when passed a null parameter.

The type specification is <C extends Comparable>, instead of the technically correct <C extends Comparable<? super C>>, to support legacy types from before Java 5.
"""

...which seems to speak to the issue. Any suggestions for how we could make it better?

**Comment by JensRantil** [comment]
Ah! Thank you for pointing out my blindness... ;)
