### ISSUE TITLE
ImmutableList.iterator() shouldn't retain a reference to the ImmutableList

### ISSUE THREAD

**Issue by dbentley** [google/guava#1960]
This is a feature request where the cost may far outweigh the benefit, and I understand that, but I ran into it and think it would be right in principle, if difficult in practice.

Consider the following code:

Iterator<Bar> deserialize(DatabaseConnection conn) {
  return Iterators.transform(conn.fetch(), new Function<Foo, Bar>() {
    @override public Bar apply(Foo foo) {
      Bar.deserialize(foo);
    }});
}

Context:
1) conn.fetch() returns an ImmutableList<Foo>
2) Foo is the serialized form (perhaps a protobuf) of a record, and Bar is the POJO form.
3) A Foo is smaller than a Bar, so you can keep ImmutableList<Foo> in memory, but you can't keep an ImmutableList<Foo> in memory while you operate on each Bar.

The result is that, instead, we copy the ImmutableList into an array and then create an Iterator that in each call to next() nulls out that slot in the array.

It would be awesome if ImmutableList's Iterator allowed earlier elements in the list to be garbage.

**Comment by lowasser** [comment]
I don't see how this could be possible without unacceptable performance cost?  I think if you tried to implement this in ImmutableList you'd see why, but in summary -- you have to maintain a reference to *something*, either the array or the ImmutableList.  Copying the array on an iterator() call would increase the asymptotic cost of an iterator() call from O(1) to O(n), and nulling out the elements behind you would break ImmutableList generally, if you could only iterate over it once.  I don't see any way of doing this feature request without breaking asymptotic or semantic guarantees.

It sounds like this is the wrong solution for your problem, however -- perhaps you'd be better off with a queue of some kind, where elements are expected to be consumed once.

**Comment by dbentley** [comment]
I don't know much about how ImmutableList is implemented.

In a naive singly linked list, I would expect the iterator to have this property. Would that be a reasonable expectation?

All I'm saying is:
1) this property is desirable
2) you could implement ImmutableList having this property
3) it would be nice for future changes to ImmutableList to made with 1 and 2 in mind.

Like I said from the beginning, I realize it's a pony request, so I understand it would require a different approach to ImmutableList.

**Comment by lowasser** [comment]
All the immutable collections are expected to have competitive performance with their most popular JDK mutable alternatives; ImmutableList is array-based because arrays are by far the fastest and most efficient way to implement lists.  O(1) get(int) is definitely not negotiable.

It really does look like a list isn't really the data structure you really want in this context.  Is there a compelling reason ImmutableList ought to be used here?

**Comment by dbentley** [comment]
Nope, and that's why we've created ForgetfulArrayIterator. I just thought you might want to know of a time I used a collection and it wasn't the best thing ever.

What collection class should I use for reading through things once?

**Comment by lowasser** [comment]
As mentioned above, a queue seems more like what you're looking for?  Queues *expect* to have an element consumed once and never used again.

**Comment by dbentley** [comment]
Does Queue do that? It looks like Queue.iterator() doesn't remove elements from the queue, just lets you peek at them.

It sounds like you think mine isn't a popular use case (i.e., a Collection that lets you stream over immutable data once, letting what you have already seen be garbage). I wanted to offer the feedback that the implementation was doing something the interface didn't seem to require, leading to surprise on my part.

**Comment by lowasser** [comment]
I didn't have using Queue.iterator() in mind, I had in mind using the Queue directly instead of an iterator.

FWIW, I don't believe *any* JDK iterator implementation has the property you're looking for?  All of ArrayList, LinkedList (over doubly linked list nodes), HashSet, LinkedHashSet, and TreeSet have iterators that appear to retain references to the entire collection.

As far as "a Collection that lets you stream over immutable data once" goes, the immutability of the collection data structure and the immutability of the data inside it are orthogonal concerns.  ImmutableList can be used freely for mutable element types; ArrayList can be used freely for immutable data types.

**Comment by lowasser** [comment]
Possibly relevant: Iterables.consumingIterable, which has a special implementation for Queue.

**Comment by nglorioso** [comment]
Given the comments from lowasser@ here, and that "a Collection that lets you stream over immutable data once" might be better represented as a `Stream<T>` now. I think I'm going to close this. Please reopen if there's something I missed.
