### ISSUE TITLE
Can different Cache eviction strategies be combined?

### ISSUE THREAD

**Issue by JensRantil** [google/guava#1980]
Just making sure, is it documented somewhere whether for time based and size based eviction can be combined? Or are they mutual exclusive? So far, I haven't found anything saying whether it should be possible or not, but maybe I've just missed it?

**Comment by ben-manes** [comment]
Yes they can be combined. Unless stated in CacheBuilder, the features can be mixed together.

**Comment by JensRantil** [comment]
Great. Thanks!

**Comment by kevinb9n** [comment]
I'm glad you have your answer. But the issue is about whether this answer is clear in the documentation; if it's not, we should reopen it.

I believed that the first sentence of CacheBuilder was enough to cover this:

"A builder of LoadingCache and Cache instances having **any combination** of the following features."

(emphasis added)

Should we do more?

**Comment by JensRantil** [comment]
Nah, that's probably enough.
