### ISSUE TITLE
Ordering.onResultOf should respect nullsFirst/nullsLast

### ISSUE THREAD

**Issue by jkstrauss** [google/guava#1983]
When creating a Guava Ordering object using `onResultOf`, a `NullPointerException` in most situations where the function returns `null` even if the object in the collection is not. (This can only be prevented by writing a specialized comparator that checks for null or wrapping the comparator with a comparator that catches `NullPointerException`s, neither of which is optimal.)

Would it be possible to have Guava respect `nullsFirst()`/`nullLast()` with regard to the result of `onResultOf` in addition to the actual object being sorted?

**Comment by kevinb9n** [comment]
You can do this with, for example:

```
return Ordering.natural()
    .nullsLast()
    .onResultOf(someFunction)
    .nullsFirst()
    .sortedCopy(stuff);
```

In this example, null objects in the collection appear first, and objects in the collection that evaluate to null in the function appear last.

**Comment by jkstrauss** [comment]
That would be nice, but it throws a `NullPointerException`. Below is the stack trace (using guava-18.0.jar).

    Exception in thread "Main Thread" java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
	at com.google.common.collect.NaturalOrdering.compare(NaturalOrdering.java:34)
	at com.google.common.collect.NaturalOrdering.compare(NaturalOrdering.java:26)
	at com.google.common.collect.ByFunctionOrdering.compare(ByFunctionOrdering.java:46)
	at com.google.common.collect.NullsLastOrdering.compare(NullsLastOrdering.java:44)
	at java.util.Arrays.mergeSort(Arrays.java:1270)
	at java.util.Arrays.mergeSort(Arrays.java:1282)
	at java.util.Arrays.sort(Arrays.java:1210)
	at com.google.common.collect.Ordering.sortedCopy(Ordering.java:817)

**Comment by kevinb9n** [comment]
Take another look at my sample code; you're missing a key bit.

**Comment by jkstrauss** [comment]
I git it to work.

Is this documented anywhere? Also, what is the logic in arranging it this way. In other cases the logic is the inverse. For instance, with regard to `natural` the `nullLast` that follows it does not throw exceptions, so why would it do that here. Is there some rule of thumb for this.

**Comment by kevinb9n** [comment]
Each call in the chain returns a new Ordering which contains a reference back to the Ordering that spawned it. In this example:

```
Ordering.natural()
    .nullsLast()
    .onResultOf(f)
    .nullsFirst()
    .compare(left, right)
```

The ordering you are actually calling `compare` on is a `NullsFirstOrdering`.  That ordering will immediately sort nulls to the front, and for everything else must delegate to its backing ordering, which is `Ordering.natural().nullsLast().onResultOf(f)`. 

*That* ordering invokes `f` on every element (which is always non-null) and gets a bunch of surrogate objects to compare. In order to compare these new objects, it must delegate to *its* backing ordering, which is `Ordering.natural().nullsLast()`.

Etc. In other words, to understand the behavior of chained Ordering construct, it is helpful to read the chain *backwards*.

**Comment by jkstrauss** [comment]
Thanks. I think I got it now.
