### ISSUE TITLE
Support collection tests of arbitrary sizes

### ISSUE THREAD

**Issue by simonmcooper** [google/guava#1986]
Currently, guava-testlib only tests collections using ZERO(0), ONE(1), and SEVERAL(3) collection sizes. I have a collection implementation that switches its internal representation at 10 elements. I would like to use testlib to test my collection around that switching point, but I can't at the moment.

It would be great if one could specify arbitrary sizes to test collections with.

**Comment by cpovirk** [comment]
We probably wouldn't support arbitrary sizes, since the enum-ness of collection features is baked in pretty deeply. One thing we've considered is a `HUGE` size to catch bugs that arise with many, many elements (whether from things like hash collisions or from changes in implementation, as in your case), but of course that comes with the time costs of running many of our tests on large collections. I should admit that the collection testers aren't too much of a priority for us anymore, though, since they're mostly good enough, so I'm mostly just letting you know that this probably won't happen soon. Sorry.

**Comment by simonmcooper** [comment]
You could include a LARGE size that test up to (say) 100 elements. A lot of collections have got specific implementations for small-ish numbers, then once it gets to 100 elements most degenerate into a general implementation for any number of items.

Testing up to 100 would also test things like internal array resizes - ArrayList has got a default size of 10, HashMap a default size of 16, and the current code doesn't test the array resizes of those classes. And it wouldn't take too long to run as well, 100 is not that much in the grand scheme of things.

**Comment by ronshapiro** [comment]
I'm going to close this given @cpovirk's response from 2 years ago that this isn't a high priority for us.

**Comment by thecoop** [comment]
:(
