### ISSUE TITLE
Stopwatch.toString(TimeUnit)

### ISSUE THREAD

**Issue by ogregoire** [google/guava#2007]
To easily visually compare elapsed times with different orders of magnitude, please overload the method `Stopwatch::toString()` with `Stopwatch::toString(TimeUnit)` (or something similar) where we can then pass a specific `TimeUnit` which allows us to see actual differences.

The current implementation is very nice to see how much time a portion of code took to execute, but if we want to compare, it'd be nice to normalize the TimeUnit.

My use case is the following: I have a hundred time measures and I often have orders of magnitude of difference between those:

```
A took 12.34 ms
B took 23.45 µs
C took 34.56 ms
```

And then we're ask ourselves "oh wait, was B "ms" or "μs" ?" And we gotta check again. Oh, so B was (roughly) 500 times faster than A.

If I always select the same `TimeUnit` (milliseconds in this case), I can have this:

```
A took 12.34 ms
B took 0.023 ms
C took 34.56 ms
```

Then it's really clear that B took a fraction of time of what A used.

A comment in Guava's code for `toString()` also mentions `Too bad this functionality is not exposed as a regular method call`. Which seems to mean that someone else also kind of needed a similar behavior.

**Comment by kevinb9n** [comment]
Sensible request. 

There is one small issue I see. We round to 4 significant digits. Currently, that doesn't cause too many problems since we constrain the value to be < 1000, so there's always a decimal part. (Well, technically you could have a single stopwatch running for more than 1000 *days*, but that's damn unlikely.)

But now it would be possible to see a message of

A took 12340 ms

... when the actual value might have been 12335, and there is no way to indicate that rounding took place. 

Not necessarily a deal-breaker, just raising it.

**Comment by fror** [comment]
I see the point, and if we start to add the precision and the RoundingMode as parameter, it starts to be a lot of parameters. Well the idea is here, I trust the team to find the best way to add this if this idea is retained.

**Comment by ronshapiro** [comment]
Do any of the `java.time` utilities + [`Stopwatch.elapsed()`](https://github.com/google/guava/blob/f2be0be06ef49dee7c5dfcb3a0231c5ecaf5b621/guava/src/com/google/common/base/Stopwatch.java#L212) solve this need?

**Comment by kluever** [comment]
This could be solved by just not relying on our custom `toString()`, but instead writing your own static function to format the string.

**Comment by kevinb9n** [comment]
I think Ron/Kurt have the right idea. Stopwatch's job is yield up the `java.time.Duration`, not to mess with text.
