### ISSUE TITLE
RangeSet<C> could implement Predicate<C>

### ISSUE THREAD

**Issue by panchenko** [google/guava#2031]
`Range` implements it, so it would be natural if `RangeSet` also does.

**Comment by kevinb9n** [comment]
It's going to haunt us that Range does... because now the JDK has its own different Predicate interface.

Anyway, this was intentional. We avoid implementing the functional type directly except when were completely convinced that there could be no two different behaviors a user would expect or want it to have when used in that way.  A little bit of doubt in this case (should the predicate accept a C or a Range<C>) was enough to make us steer clear.
