### ISSUE TITLE
ImmutableMap.Builder can be subclassed outside of the package

### ISSUE THREAD

**Issue by cgdecker** [google/guava#2033]
It's non-final (since it's subclassed for the sorted variety, etc.) and has a public no-arg constructor. There may be other `Builder`s in this boat. We should consider deprecating the public no-arg constructor, given that having two ways to create a `Builder` is unusual and unnecessary in the first place.

**Comment by ronshapiro** [comment]
There seem to be a few subclasses internally of ImmutableMap.Builder. One does a null check on the value and ignores the `put` if it doesn't pass, and the others add a method which delegates to `put()` and only call that method. The latter cases are all used in the same file they're defined and could easily be migrated. There are also a few usages of a subclass only to be able to have a class initializer, which doesn't actually buy them much since the API is fluent already.

Note that if we decide to fix this, we should also fix it for `ImmutableSortedSet`. That has the same few kinds of subclasses, plus one that really should just be an `@AutoValue.Builder`.

One option here would be to make a `BaseImmutableMapBuilder` that's package-private and then have `ImmutableMap.Builder` be a simple shell over that, exposing the public constructor but making the class `final`. Then `ImmutableBiMap.Builder` and `ImmutableSortedMap.Builder` could extend `BaseImmutableMapBuilder`.

`ImmutableSortedMap.Builder` currently has no subclasses and seems like it should probably be `final` (`ImmutableSortedSet.Builder` is `final`).

These would all technically be breaking changes to non-`@Beta` APIs however.

**Comment by cgdecker** [comment]
Given that we're committing to not making breaking changes to non-`@Beta` APIs (with the exception of removing the `CharMatcher` constants), I don't think we can do this. Fortunately, I also don't think it's too big a deal, really. Most people won't do it, and those that choose to can just deal with that. It usually won't affect things across API boundaries since builders typically aren't passed around, and AFAIK it doesn't give other packages access to any internals that shouldn't be exposed... at the very least I'm sure it doesn't give them the ability to construct actual `ImmutableMap`s that violate its contract.

**Comment by cpovirk** [comment]
lowasser is about to make a change to `ImmutableCollection.Builder.addAll` that could theoretically break subclasses that assume it will always delegate to `add`. I'm not really concerned about that, but it's a concrete reason to be sad that we can never fix this.

If we're feeling paranoid, we can add documentation to the builder classes to recommend that no one subclass them. (If we're feeling _extremely_ paranoid, we can even deprecate the constructors, which have gotten even less attractive lately, since they don't support pre-sizing like the factory methods do. But I think that's clearly overkill.)
