### ISSUE TITLE
What's the point about CycleDetectingLockFactory (@Beta, I know...)

### ISSUE THREAD

**Issue by Petikoch** [google/guava#2042]
Hi there,

I'm trying to understand the CycleDetectingLockFactory class and how it can be useful.

I checked the unit tests and found one scenario with a false positive. I did another scenario with a real deadlock (involving two threads), which is not recognized.

So I'm wondering what is the benefit of the current class implementation? (If those two basic scenarios are not working?)

As far as I can guess, the only meaningful point about this implementation is, that the rule `all threads acquire the locks in the same order`(http://docs.oracle.com/cd/E19455-01/806-5257/6je9h0347/index.html) is enforced, is that right? After reading the javadoc again, I find this as `checking for cycles in lock acquisition order`. So, a better name for the class could be `IllegalLockAquisitionOrderDetectingLockFactory`. 

Thanks for your feedback and best regards from Switzerland, 
Peti

```
package com.google.common.util.concurrent;

import com.google.common.util.concurrent.CycleDetectingLockFactory.Policies;
import junit.framework.TestCase;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.locks.ReentrantLock;

public class CycleDetectingLockFactoryTest extends TestCase {

    private ReentrantLock lockA;
    private ReentrantLock lockB;

    @Override
    protected void setUp() throws Exception {
        CycleDetectingLockFactory factory =
                CycleDetectingLockFactory.newInstance(Policies.THROW);
        lockB = factory.newReentrantLock("LockB");
        lockA = factory.newReentrantLock("LockA");
    }

    //------
    // FALSE POSITIVE?
    //-----
    public void testDeadlock_twoLocks_falsePositive() {
        // Establish an acquisition order of lockA -> lockB.
        lockA.lock();
        lockB.lock();
        lockA.unlock();
        lockB.unlock();

        // The opposite order fails afterwards, although there is no deadlock ANYWHERE
        lockB.lock();
        lockA.lock();
    }

    //------
    // REAL DEADLOCK NOT RECOGNIZED?
    //-----
    public void testDeadlock_twoThreads_realDeadlock_notDetectedOrPrevented() throws InterruptedException {
        final CountDownLatch t1HasLockA = new CountDownLatch(1);
        final CountDownLatch t2HasLockB = new CountDownLatch(1);
        final CountDownLatch allThreadsFinished = new CountDownLatch(2);

        Thread t1 = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    //prepare
                    lockA.lock();
                    t1HasLockA.countDown();
                    t2HasLockB.await();

                    // now deadlock
                    lockB.lock();
                } catch (Exception ignored) {
                    // expected due to the use of CycleDetectingLockFactory
                    ignored.printStackTrace();
                } finally {
                    lockA.unlock();
                    lockB.unlock(); // just in case
                    allThreadsFinished.countDown();
                }
            }
        });
        t1.setDaemon(true);
        t1.start();

        Thread t2 = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    // prepare
                    t1HasLockA.await();
                    lockB.lock();
                    t2HasLockB.countDown();

                    // now deadlock
                    lockA.lock();
                } catch (Exception ignored) {
                    // expected due to the use of CycleDetectingLockFactory
                    ignored.printStackTrace();
                } finally {
                    lockB.unlock();
                    lockA.unlock(); // just in case
                    allThreadsFinished.countDown();
                }
            }
        });
        t2.setDaemon(true);
        t2.start();

        t1HasLockA.await();
        System.out.println("Thread 1 has Lock A");
        t2HasLockB.await();
        System.out.println("Thread 2 has Lock A");

        allThreadsFinished.await();
    }
}
```

**Comment by DarickTong** [comment]
Hi Petikoch,

Thank you for your questions and observations!

The CycleDetectingLockFactory does not detect deadlocks per se. It detects *potential* deadlocks by noticing when an application's lock acquisition patterns can form a cycle.

It is true that a cycle will not necessarily lead to a deadlock. lockAthenB() and lockBthenA() will never deadlock if the application only runs one thread, or if the two methods' execution is guarded by another lock. However, this type of serialization invariant is not enforceable by the compiler, and in large systems it's often easy to break such invariants and not notice until a deadlock happens. (For example, the "testDeadlock_twoLocks_falsePositive()" method can indeed deadlock if run concurrently in multiple threads.)

The philosophy of the CycleDetectingLockFactory is to prevent deadlocks by enforcing that, for any pair of locks, the application always acquires them in the same order. At the expense of potential false positives, this eliminates the reliance on higher-level invariants that are otherwise hard to verify.

That said, you're absolutely right that it does not catch everything! testDeadlock_twoThreads_realDeadlock_notDetectedOrPrevented() identifies a deficiency that's noted in an implementation comment: 

https://github.com/google/guava/blob/master/guava/src/com/google/common/util/concurrent/CycleDetectingLockFactory.java#L697

      void checkAcquiredLock(...) {
        ...
        // Note that there is a race condition here which can result in missing
        // a cyclic edge: it's possible for two threads to simultaneous find
        // "safe" edges which together form a cycle. Preventing this race
        // condition efficiently without _introducing_ deadlock is probably
        // tricky. For now, just accept the race condition---missing a warning
        // now and then is still better than having no deadlock detection. 
      }

If you have an idea of how to handle this race condition, please do submit a fix!

Thanks again for your thoughts contributions!

Darick

**Comment by Petikoch** [comment]
Dear @DarickTong ,

thank you very much for your explanations. 

I think I really understand now the "prevention"-approach using **enforcing lock acquisition order** and the difference to a "detection"-approach (finding out that there *is  now* a deadlock).

I wrote down my thoughts here: https://github.com/Petikoch/guava_cycledetection_example

It try to summarize this further:

Approach: "Enforcing lock acquisition order"

Good
* prevents 100% of the deadlock situations (if you run 100%  - line coverage - of your code in pre-production)

Bad
* false positives
* introduces a potential central bottleneck, because all the lock acquisition threads must pass here

Approach: "Hooking into the lock acquisition / lock releasing process and analyzing current lock-holding situation"

 Good
* no false positives

Bad
* doesn't prevent 100% of the deadlock situations, because in practice you are unable to cover all possible scenarios with tests
* introduces a potential central bottleneck, because all the lock acquisition / lock releasing threads must pass here

Regarding the implementation issue with the race-condition: I'll give it a try ;-)

Best regards from Switzerland,
Peti

**Comment by Petikoch** [comment]
Close for now. I open a new issue for the race-condition bug.

**Comment by Petikoch** [comment]
Opend https://github.com/google/guava/issues/2048
