### ISSUE TITLE
Can't seem to properly form a pull request

### ISSUE THREAD

**Issue by javajosh** [google/guava#2047]
So I found a minor bug while browsing the source in IntelliJ and figured, heck, why not fix it? So I forked guava, built it, made my change, pushed and created a pull request, complete with affable wit.

   https://github.com/google/guava/pull/2045

The CLA bot wasn't happy. I suspected it was because I signed the CLA under javajosh@gmail.com, but my `git config user.email` was a different email. So I changed the value, reverted, created a new branch 'javajosh' and merged my change from master, pushed, and crafted a new pull request. Yet this did not, apparently, correct the problem:

   https://github.com/google/guava/pull/2046

I am flummoxed.

**Comment by cgdecker** [comment]
Hmm, looking at the commit from your second pull request (https://github.com/javajosh/guava/commit/8b472b14a14a8c60094535a5631d6fdee862530b) I see the commit author is set to `Josh Rehman <josh@joshrehman.com>`. I think it's probably because what you did ("changed the value, reverted, created a new branch 'javajosh' and merged my change from master") didn't actually change the commit itself at all.

You'd need to use `git commit --amend --author "New Author Info <email>"` to actually change it.
