### ISSUE TITLE
Adding additional precondition checks for blank / empty

### ISSUE THREAD

**Issue by cchesser** [google/guava#2053]
I would like to add more checks which can be applied on the [Preconditions](http://docs.guava-libraries.googlecode.com/git-history/release/javadoc/com/google/common/base/Preconditions.html) class. These checks would include:
* checkBlank(String)
* checkNotBlank(String)
* checkEmpty(String/Collection)
* checkNotEmpty(String/Collection)

All of these would throw an IllegalArgumentException if the check fails. Would it be acceptable to expand Preconditions to these new checks? I would be happy do to the pull request if so.

**Comment by lowasser** [comment]
I don't believe we're likely to want support for these, for a couple reasons --

- "blank" is a term we've avoided referring to in Guava, because where we've seen it used in the past, it refers to an ill-specified definition of whitespace.  We would prefer users to refer explicitly to CharMatcher.is(' '), CharMatcher.WHITESPACE, or some other unambiguous definition.
- Preconditions is deliberately relatively minimal.  There's not that big a win between checkEmpty(Collection) and checkArgument(Collection.isEmpty()), and checkArgument is unambiguous about which exception it throws.

I'm not sure how you wanted these to handle nulls, either, but if you wanted "empty" to mean "empty or null," see http://stackoverflow.com/questions/6910002/google-guava-isnullorempty-for-collections for our thoughts on that.

**Comment by cchesser** [comment]
Thanks @lowasser for the clarification. We have noticed a lot of "cookie-cutter" code patterns around some of these checks (in some cases doing multiple function calls within the precondition), which is why I wanted to suggest adding these. 

For empty / blank checks, I was considering failing the check if what was supplied was null, by throwing an IllegalArgumentException in that scenario.

I assume the checkEmpty(String) / checkNotEmpty(String) is also not wanted? Ex. checkNotEmpty would have to be non-null and length > 0.

**Comment by lowasser** [comment]
> I assume the checkEmpty(String) / checkNotEmpty(String) is also not wanted? Ex. checkNotEmpty would have to be non-null and length > 0.

Yes, I believe so, for similar reasons.

**Comment by cchesser** [comment]
OK, well I will go ahead and close this out. Thanks for the feedback.

**Comment by cpovirk** [comment]
IIRC, there is at least some sentiment on the team that we'd be better off without `Strings.isNullOrEmpty`, too :)

That said: In practice, I think there tend to be more APIs in existence that return "string or null" than "collection or null." For example, we see often this with methods that return the values of HTTP parameters. It might be nice if HTTP APIs more commonly offered a `getParameterString` method that returned the empty string instead of null, but that's not within our power to change. What we do want to do is encourage people to return an empty string or empty collection when practical. One way we do that is by offering `Multimap`, which can replace a `Map<K, Set<V>>` and eliminate the need to worry about null returns. Another way is by stubbornly refusing to add this API for a decade or so :)
