### ISSUE TITLE
EvictingQueue doesn't proxy equals/hashcode to its delegate Queue

### ISSUE THREAD

**Issue by scr** [google/guava#2064]
When using [hamcrest assertions](http://hamcrest.org/JavaHamcrest/), I was surprised that the following didn't pass:

```
EvictingQueue<Integer> lastFive = Stream.of(1, 2, 3, 4, 5, 6, 7, 8, 9, 10).collect(Collectors.toCollection(() -> EvictingQueue.create(5));
EvictingQueue<Integer> expected = EvictingQueue.create(5);
expected.addAll(Arrays.asList(6, 7, 8, 9, 10));
assertThat(lastFive, is(expected));
```

Whereas the following did:

```
EvictingQueue<Integer> lastFive = Stream.of(1, 2, 3, 4, 5, 6, 7, 8, 9, 10).collect(Collectors.toCollection(() -> EvictingQueue.create(5));
EvictingQueue<Integer> expected = Arrays.asList(6, 7, 8, 9, 10);
assertThat(new ArrayList<>(lastFive), is(expected));
```

If it's only for testing, no big deal, but I would have expected that two EvictingQueues could be compared to each other naturally especially if the delegate is.

**Comment by kevinb9n** [comment]
It's not actually delegating to your List; it delegates to an internal ArrayDeque, which (like every Queue (except the one that also implements List)) doesn't have value-based equality.

**Comment by kluever** [comment]
Could simplify your assertions a bit with [Truth](https://github.com/google/truth):

`EvictingQueue<Integer> lastFive = Stream.of(1, 2, 3, 4, 5, 6, 7, 8, 9, 10).collect(Collectors.toCollection(() -> EvictingQueue.create(5));
assertThat(lastFive).containsExactly(6, 7, 8, 9, 10).inOrder();`

**Comment by kluever** [comment]
@cpovirk said:
["Queue implementations generally do not define element-based versions of methods equals and hashCode but instead inherit the identity based versions from class Object, because element-based equality is not always well-defined for queues with the same elements but different ordering properties."](http://docs.oracle.com/javase/7/docs/api/java/util/Queue.html) This is true of ArrayDeque, so our equals() method would be delegating to an object that uses Object.equals(). The net effect of the proposed change will be no change in behavior.

Going to close this as WAI
