### ISSUE TITLE
Service listeners are not called reliably

### ISSUE THREAD

**Issue by Bombe** [google/guava#2067]
I have this class:

```java
public class Core extends AbstractIdleService {

    @Override
    protected void startUp() throws Exception {
    }

    @Override
    protected void shutDown() throws Exception {
    }

}
```

…and this unit test:

```java
public class CoreTest {

    private final Core core = new Core();
    private final AtomicBoolean started = new AtomicBoolean();
    private final AtomicBoolean stopped = new AtomicBoolean();

    @Before
    public void setupCoreListener() {
        core.addListener(new Listener() {
            @Override
            public void running() {
                System.out.println("running");
                started.set(true);
            }

            @Override
            public void stopping(State from) {
                System.out.println("stopping");
                stopped.set(true);
            }

            @Override
            public void terminated(State from) {
                System.out.println("terminated");
                stopped.set(true);
            }
        }, MoreExecutors.directExecutor());
    }

    @Test
    public void coreCanStartUp() {
        core.startAsync().awaitRunning();
        System.out.println("testing started");
        MatcherAssert.assertThat(started.get(), Matchers.is(true));
    }

    @Test
    public void coreCanShutDown() {
        core.startAsync().awaitRunning();
        core.stopAsync().awaitTerminated();
        System.out.println("testing stopped");
        MatcherAssert.assertThat(stopped.get(), Matchers.is(true));
    }

}
```

I would expect these tests to always succeed; the service listener is run in the same thread, the boolean is stored in an `AtomicBoolean` and yet, if I run this test multiple times it sometimes fails. On stdout I see:

```
testing started
running
running
stopping
testing stopped
terminated
```

So `core.startAsync().awaitRunning()` returns before the listener for `running` is called. Is that intended and correct behaviour?

**Comment by cpovirk** [comment]
There are two threads involved:

- the thread that runs `startUp` and then invokes the `running` listener
- the main test thread

Your use of `directExecutor` prevents that from increasing to three, but there are already enough threads for a race: The `startUp` thread releases the main test thread (`monitor.leave()`) before it starts running the listeners (`executeListeners()` -- see `AbstractService.notifyStarted()` for both calls).

How do you work around this? Well, it depends on what you really want your test to do. If all we're doing is verifying that the listeners eventually ran, we can use a `CountDownLatch` instead of an `AtomicBoolean`: `running()` calls `countDown()`, and `coreCanStartUp()` calls `await(5, SECONDS)` (or however long you want it to wait in the failure case, which you will hopefully never see).

**Comment by Bombe** [comment]
Well, bugger. That makes sense. Thanks. :)
