### ISSUE TITLE
Inaccurate documentation on immutable collections

### ISSUE THREAD

**Issue by shmosel** [google/guava#2081]
The documentation for `ImmutableList.of()` states the following:

> Returns the empty immutable list. This set behaves and performs comparably to Collections#emptyList, and is preferable mainly for consistency and maintainability of your code.

One notable difference between `ImmutableList.of()` and `Collections.emptyList()` is that the former throws an `UnsupportedOperationException` on `clear()` while the latter does not. Should that be considered behaving "comparably"?

Similarly for `ImmutableMap` and `ImmutableSet`.

EDIT: I also noticed the documentation says "Returns **the** empty immutable [list/map/set]." I suppose that's a mistake?

**Comment by cpovirk** [comment]
I think that's similar enough to count as "comparably," since code should typically not depend on the specific type of `RuntimeException` thrown. We probably avoided the word "identically" for reasons like the one you mention.

As for the question you added about "Returns **the** empty immutable [list/map/set]": That's our way of saying that the instance is a singleton so that you know you can call the method without allocating.

**Comment by eamonnmcmanus** [comment]
I'll note that it isn't a question of the particular exception thrown, but that `Collections.emptyList()` doesn't throw an exception at all for `clear()` (or for `remove` or `removeAll`). I agree that this still fits the description "comparably", though. It is also consistent with the method signature, which suggests an immutable list that happens to contain no elements rather than a special kind of list. So you would expect it to behave the same for `clear`, `remove`, etc. Those methods in `ImmutableList` throw an exception whether or not they would have an effect on the list contents.

The behaviour of `Collections.emptyList().clear()` is unspecified. Indeed, this text from the `Collections` class doc suggests that that is deliberate:
> The "destructive" algorithms contained in this class, that is, the algorithms that modify the collection on which they operate, are specified to throw `UnsupportedOperationException` if the collection does not support the appropriate mutation primitive(s), such as the `set` method. These algorithms may, but are not required to, throw this exception if an invocation would have no effect on the collection. For example, invoking the `sort` method on an unmodifiable list that is already sorted may or may not throw `UnsupportedOperationException`.

So code should not be relying on this behaviour anyway.

**Comment by shmosel** [comment]
Regarding the singleton return value, I would say it should either be documented clearly or not at all.

**Comment by cpovirk** [comment]
Oops, thanks for the correction, Éamonn.

Can you open a separate issue about documenting that the no-arg methods return a singleton?

**Comment by eamonnmcmanus** [comment]
I was going to open an issue about documenting singletonness, but in fact the existing documentation says "behaves and performs comparably to `Collections.emptyList()`", and the documentation for `Collections.emptyList()` says "Using this method is likely to have comparable cost to using the like-named field". Together those two statements already imply that this method returns a singleton object.

**Comment by shmosel** [comment]
I must disagree. `Collections.emptyList()` doesn't have to return a singleton. Assuming it does, `ImmutableList.of()` doesn't have to emulate that property. Assuming it does, "the" is a very obscure way of referencing that.

**Comment by eamonnmcmanus** [comment]
I don't see how `ImmutableList.of()` could "perform comparably to `Collections.emptyList()`" if it didn't return a singleton. However, since I had already written the bug report, I've gone ahead and submitted #2083 anyway.
