### ISSUE TITLE
Map conversion

### ISSUE THREAD

**Issue by tonycody** [google/guava#2115]
Maps.transformValues()
nonsupport key

```java
// Map<String,String> ——> Map<byte[],byte[]>
HashMap<String, String> fromHashMap = new HashMap<String, String>();
                HashMap<byte[], byte[]> target =
                    Maps.transformValues(fromHashMap, new Function<String, byte[]>() {
                        public byte[] apply(String input){
                            return input.getBytes();
                        }
                    });

// commons-collection
Map map = MapUtils.transformedMap(hash, new Transformer() {
                    public Object transform(Object input){
                        return ((String) input).getBytes();
                    }
                }, new Transformer() {
                    public Object transform(Object input){
                        return ((String) input).getBytes();
                    }
                });
```

**Comment by lowasser** [comment]
Maps.transformValues, and the rest of Guava's transformation methods, deliberately provide *views* -- not copies of the original collection, but views -- that can be supported efficiently.  Mapping keys cannot be supported efficiently as a view.

**Comment by trejkaz** [comment]
Mapping keys can be supported efficiently as a view, if the mapping is bidirectional.

**Comment by cpovirk** [comment]
It can, but we found that few bidirectional mappings are completely one-to-one, and when they're not we end up with weird behavior.

Anecdote: We once introduced `Sets.transform`, implemented with a bidirectional mapping. We kept it private because we were worried about misuse, using it only in one carefully selected implementation. Then, months later, we discovered... our mapping wasn't one-to-one, and we had a bug as a result :)

One thing that we could consider, though, is a `MapStream`/`EntryStream` (https://github.com/google/guava/issues/2632). There, it would make sense for us to provide a `mapKeys` method that, unlike our existing `transformValues`, etc. methods, would be applied as a one-time mapping, not as a live view.

(It would be nice if we could remove the live-view methods entirely someday (which also might save us from having to come up with a name for the versions that accept `java.util.Function` instead of `c.g.c.base.Function`). But the migration from live views to one-time computation has the potential to break people.)
