### ISSUE TITLE
possible for one final update of InternetDomainName (psl) before 19.0 release

### ISSUE THREAD

**Issue by jgangemi** [google/guava#2120]
would it be possible to ensure `InternetDomainName` rolls out w/ the latest version of the PSL (or as close to it as you can get) before release?

i don't know when the official release is slated for, but according to this site, https://iwantmyname.com/domains/new-gtld-launch-dates, there are new tlds on the horizon and depending on how quickly mozilla updates, it'd be nice to see as many of these included in the next release.

it'd also be great to see something happen w/ #1123 /  #475

**Comment by kevinb9n** [comment]
I think we can probably do this. You should be seeing a version that's current as of May 15, is that correct?

**Comment by jgangemi** [comment]
yes, i believe so.

**Comment by kevinb9n** [comment]
This is done (possibly not mirrored out yet, but will be).

**Comment by jgangemi** [comment]
awesome, thank you!!

do you have a target date (i realize it could change) for the 19.0 release?

**Comment by ndedrickson** [comment]
I will second the vote for #1123, _enthusiastically_.

I'm using this as part of an application feature that runs comparisons of various competing websites. Having a static list of TLDs per Guava release means that any new public suffix created since the last release (in this case, over half a year back) will trigger an `IllegalStateException` when it is used with `InternetDomainName.topPrivateDomain()`.

New TLDs are being released more frequently in the past, and I cannot imagine that problems arising from a static, infrequently-updated list are unique to my own use cases.  The ability to dynamically update the TLD list in Guava would be an immense improvement to this area of usability.

**Comment by cpovirk** [comment]
Done in https://github.com/google/guava/commit/2b8b6fd9f3da35b0a7c28316a8167092bafd6179

Note that we have since done *another* update in https://github.com/google/guava/commit/3a604328c28919480caea60e754debb8ec84b75b. That one may or may not make release 19.
