### ISSUE TITLE
Consider JSR-107 support for guava cache

### ISSUE THREAD

**Issue by patric-r** [google/guava#2177]
It would be nice and helpful if guava would support [JSR-107 Java Temporary Caching API](https://jcp.org/en/jsr/detail?id=107) - either out-of-the-box or by providing an adapter.

**Comment by ben-manes** [comment]
You really don't want it. Its horribly designed, error prone, and slow. The TCK is buggy and provides very poor coverage. The API is not friendly and the annotations are racy (non-atomic).

The implementations I've reviewed, written by the spec authors, do not even honor the API contract (e.g. ordered events are in fact not always ordered). The spec specifies the implementation algorithms to ensure that all match the design and quirks of the original reference, Ehcache. This requires extensive bridge code to reimplement features due to how over specified they are defined in the JavaDoc and TCK.

I don't think Guava can adequately implement the spec without abandoning most of the value of the cache. The team would probably discourage usage after having gone through the implementation exercise and not want to support it.

You can see my [adapter](https://github.com/ben-manes/caffeine) for a Guava-like cache. However, I'd recommend you look into the JSR and further advise you to avoid it if possible.

**Comment by kevinb9n** [comment]
Thanks for explaining so well, Ben.

**Comment by ben-manes** [comment]
It looks like @ocafebabe is attempting to implement a [guava-jcache](https://github.com/ocafebabe/guava-jcache). I don't think it will be able to pass the TCK and be fully thread-safe (e.g. entry processors are supposed to be atomic, expiry is required to be called on every operation so it can't map to guava's). When Guava is updated to JDK8 with `compute` support then I think this could be a full implementation. Until then, it is probably good enough if the caveats are acceptable.

**Comment by ocafebabe** [comment]
Indeed, I tried to run the TCK against my [guava-jcache](https://github.com/ocafebabe/guava-jcache) implementation and some tests don't pass but mostly because Guava doesn't support all the JSR-107 features (like "store by value" for instance)... But personally I don't need all the fancy JSR-107 features anyway! Let's face it, most of the time all you want from a caching solution is simply put and get operations. And in my case I also need the cache loading option since values are provided by the database but this already supported very well by Guava.

The two main reasons I had initially when I started working on this project was to be able to use Guava as my caching provider with the added value of a CacheManager (this is very handy when you need to force the invalidation of a specific cache from a caching service) and also have the possibility to plug a different caching solution (like EhCache, Hazelcast, etc.). And both are already working very well with the current state of my project!

Is there an ETA for the Guava update to JDK8?

Comments and/or suggestions are welcomed :)

**Comment by ben-manes** [comment]
The last updated plan said [mid 2016](https://groups.google.com/d/msg/guava-discuss/ZRmDJnAq9T0/-HExv44eCAAJ).

You may enjoy browsing through [Caffine's JCache adapter](https://github.com/ben-manes/caffeine), which is a Java 8 rewrite of Guava's cache. I think you could use many of the same techniques (event ordering via future chains, computes). The only race that may be hard to tackle is that Guava's removal notifications are asynchronous, but the removal JSR event must be fully ordered. That is solved in Caffeine by introducing a `CacheWriter`. I think you can be resolve that too, but it is a little more tricky.

**Comment by ocafebabe** [comment]
I just realized that you're the author of Caffeine! I looked at this project very closely before starting to work on my own implementation. And honestly I wanted to use it but my biggest issue is the Java 8 requirement! At work we still rely on some Java libraries that aren't compatible with Java 8 yet. So for now we're stuck with Java 7! But I will revisit Caffeine as soon as we port everything to Java 8!

Thanks for you feedback!
