### ISSUE TITLE
Make Iterables#toCollection public

### ISSUE THREAD

**Issue by jochenseeber** [google/guava#2179]
I was searching for a way to convert an Iterable to a Collection, and Guava already has it. Sadly, it's not public...

Use case: I am creating a class where the API uses Iterable (because it's the right thing to do there), but have to call a 3rd party component that requires a Collection.

**Comment by ogregoire** [comment]
What about `Lists.newArrayList(Iterable)` or `ImmutableList.copyOf(Iterable)`?

**Comment by jochenseeber** [comment]
Works, but always creates a copy. Iterables.toCollections does not if it is passed a collection.

**Comment by cpovirk** [comment]
This method is quite possibly the right thing for your use case, but I would predict that it would be hard to add to Guava without encouraging misuse.

Most users who want a `Collection` are going to want a specific type of `Collection`: a `Set` that has a fast `contains()` implementation, a `List` that has fast random access, or whatever. The main exception, of course, is exactly your use case: Someone wrote an API that should have accepted `Iterable` but doesn't.

There are a couple things to watch out for even in that case. First, will the method mutate or store the given `Collection`? If so, do you want mutations it makes to be reflected in your original `Iterable`? Do you want changes to your original `Iterable` to affect the `Collection` you passed in? Again, for some use cases, you won't need to care, but for a general-purpose API, we need to nail this down. And under the current API, the answer is "It depends." To reflect this, we'd probably have to rename the method to "castOrCopyToCollection."

But what about the case where the method you're calling really does just iterate over the input, not modify or store it? In that case, the distinction I make above doesn't matter. But now someone is going to tell us that we should just provide a `Collection` *view* of the underlying `Iterable`, since there's no need to copy it. So if we restrict ourselves to that use case, we probably want `Iterables.asCollection()`. But then will users get bit when someone calls its an O(n) `size()` implementation in a loop?

A final irony in all this is that `Iterables.toCollection()` is not actually an ideal tool for how we use it, either: We use it only to implement `Iterables.toArray()`, but that means that we end up making an extra copy that we don't need. That's not a big deal, but we would get better performance if we just wrote the array-expansion logic ourselves.
