### ISSUE TITLE
First put is not evicted

### ISSUE THREAD

**Issue by yaitskov** [google/guava#2229]
Hi,

The following test fails on the last line.
First item is not evicted.
It fails for version 18 and 19 rc2.

```
         Cache c = CacheBuilder.newBuilder()
                .concurrencyLevel(4)
                .maximumSize(1000)
                .expireAfterAccess(10000L, TimeUnit.SECONDS)
                .build();

        for (int i = 0; i < 1000;  ++i) {
            c.put(i, "v" + i);
        }
        assertNotNull(c.getIfPresent(0));
        for (int i = 1000; i < 1003;  ++i) {
            c.put(i, "v " + i);
        }
        assertNull(c.getIfPresent(1));
        assertNull(c.getIfPresent(2));
        c.cleanUp();
        assertNull("BB " + c.getIfPresent(0), c.getIfPresent(0));
```

**Comment by lowasser** [comment]
I'm not sure why you would expect this test to pass?  Guava does not guarantee a specific eviction policy  that would specify which items would be evicted.

The current implementation is approximately per-segment LRU, which would _not_ evict the least-recently used entries from the cache as a whole, but only the least-recently-used entries that happened to be hashed into the cache segment that overflowed.  Even so, that policy is not specified and is subject to change.

**Comment by ben-manes** [comment]
`getIfPresent(0)` is an access, so that entry moves from the least recently used status to the most recently used. If instead `asMap().containsKey(0)` is used then the tests passes. That's a fluke, as @lowasser explains. It can be deterministic if setting `concurrencyLevel(1)`, at which point strict LRU is enforced. Guava uses that trick for its unit tests, but it is not part of the API contract.
