### ISSUE TITLE
How to run only selected test cases?

### ISSUE THREAD

**Issue by antoaravinth** [google/guava#2235]
I'm trying to run only one of the selected test cases via `mvn` like this:

```
mvn -Dtest=UntrustedInputFutureTest#testSetFutureThenInterrupt test
```

But this doesn't work, `mvn` says `There are no tests to run.`. 

How should I run only one test case?

**Comment by Richa28** [comment]
Hi,

You are not able to run this test case using maven because this is defined using junit.framework.TestCase. This can be run by overriding the runTest() method or by creating a testSuite.

**Comment by cpovirk** [comment]
[Docs](http://maven.apache.org/surefire/maven-surefire-plugin/examples/single-test.html):

> NOTE : This feature is supported only for Junit 4.x and TestNG.

(Guava is stuck on JUnit 3 for GWT reasons.)

The best you can do that I'm aware of is to filter by filename:

```
./mvn -Dtest.include="**/UntrustedInputFutureTest.java" test
```

\[edit: The following GWT part became unnecessary many years after my post.\]

That will still run all the GWT tests, so you probably want something like:

```
./mvn -Dtest.include="**/UntrustedInputFutureTest.java" -Dgwt.test.include="NothingWillMatchThis" test
```

(Hopefully I got those right. I haven't been able to test them as thoroughly as I'd like because of some [problems with GWT deps](https://groups.google.com/d/topic/google-web-toolkit/Ty78TNg58iA/discussion) at the moment.)
