### ISSUE TITLE
Workaround for JDK issue JDK-8143647

### ISSUE THREAD

**Issue by ogregoire** [google/guava#2342]
Recently a [question on StackOverflow](http://stackoverflow.com/q/34472616/180719) showed that it was impossible to run such a portion of Java 8 code (compile-time is okay):

    public final class SampleMain {
      public static void main(String[] argArr) {
        final ArrayListMultimap<Void, Void> arrayListMultimap = ArrayListMultimap.create();
        arrayListMultimap.clear();
        final Consumer<ArrayListMultimap> arrayListMultimapConsumer = ArrayListMultimap::clear;
        arrayListMultimapConsumer.accept(arrayListMultimap);
      }
    }

This issue comes from the fact that some public methods are last defined in a package-private parent class. It has been referenced as issue [issue JDK-8143647](https://bugs.openjdk.java.net/browse/JDK-8143647) from the JDK and is fixed, but the fix is yet to be released.

So to workaround the JDK issue and protect Guava users from it, is it possible to look for each method that is last defined in a package-private parent class and overwrite those methods in public implementations with a rather simple call `super.method()`?

**Comment by kluever** [comment]
If you use the interface type as the type (`ListMultimap` instead of `ArrayListMultimap`), this should work fine. Or if you use a lambda instead of a method reference, it should also work.

The added pain of adding NO-OP methods to all of our collection types is probably too much to work around this soon-to-be fixed issue.
