### ISSUE TITLE
Test suites incorrectly call TestSetGenerator.order

### ISSUE THREAD

**Issue by cdman** [google/guava#2349]
The [javadoc for TestContainerGenerator.order](https://github.com/google/guava/blob/master/guava-testlib/src/com/google/common/collect/testing/TestContainerGenerator.java#L66) states:

> This method runs only when CollectionFeature#KNOWN_ORDER is specified when creating the test suite. It should never run when testing containers such as HashSet, which have a non-deterministic iteration order.

However, 74 tests (out of 450) fail with the code below which (as described by the documentation) expects TestContainerGenerator.order not to be called and throws an UnsupportedOperationException for it:

````java
public final class JavaUtilCollectionsTests {
  public static Test suite() {
    TestSuite suite = new TestSuite("HashSet");
    suite.addTest(SetTestSuiteBuilder.<Integer>using(new TestSetGenerator<Integer>() {
      @Override
      public SampleElements<Integer> samples() {
        return new SampleElements<Integer>(-7, 0, Integer.MIN_VALUE, 42, Integer.MAX_VALUE);
      }

      @Override
      public Integer[] createArray(int length) {
        return new Integer[length];
      }

      @Override
      public Iterable<Integer> order(List<Integer> insertionOrder) {
        throw new UnsupportedOperationException();
      }

      @Override
      public Set<Integer> create(Object... elements) {
        List<Integer> values =
            Arrays.stream(elements).map(o -> (Integer) o).collect(Collectors.toList());
        return new HashSet<>(values);
      }
    }).named("HashSet")
        .withFeatures(CollectionSize.ANY, CollectionFeature.GENERAL_PURPOSE,
            CollectionFeature.ALLOWS_NULL_VALUES, CollectionFeature.SERIALIZABLE_INCLUDING_VIEWS)
        .createTestSuite());
    return suite;
  }
}
````

The expected result would be for all the tests to pass.

**Comment by cpovirk** [comment]
Thanks.

As best I can tell, `order()` is called only from other `order()` implementations and from `AbstractContainerTester.getOrderedElements()`.

`getOrderedElements()` is called from:
- `expectUnchanged`
- `createOrderedArray`

The problem is `expectUnchanged`, which doesn't document the `KNOWN_ORDER` requirement and is unsurprisingly used in various places that it shouldn't be.

The easy way out for us here is probably to say that `order` can return the elements in whatever order it wants if the container doesn't have `KNOWN_ORDER`. (This is in fact the "default" behavior of classes like `TestStringSetGenerator`, which we use for `HashSet` in `TestsForSetsInJavaUtil`/`OpenJdk6SetTests`.) This is a spec change, but given what you've shown here, I would expect it to be a positive change for everyone.

**Comment by cdman** [comment]
Changing the documentation to allow to just return the list if the order can not be guaranteed sounds good to me.

**Comment by cpovirk** [comment]
Sorry for the extremely slow responses to your bug reports here. I do appreciate the reports.

**Comment by cdman** [comment]
@cpovirk - no problem, I appreciate them being fixed. And thank you for this extensive test-suite, it really helps in sussing out the bugs from 3rd party collection frameworks!
