### ISSUE TITLE
Add a Consumer<T> instead of Function<T,Void>

### ISSUE THREAD

**Issue by hepin1989** [google/guava#2449]
As it is,otherwise I have to write a `return null` or invent the wheel of `Consumer<T>`.

**Comment by cpovirk** [comment]
Common interfaces like `Consumer` are useful primarily because of the APIs that require them. Since Guava doesn't have `forEach` or similar methods, libraries can declare their own `Consumer` types and get basically the same functionality.

For cases where a common type is necessary, we recommend the `Consumer` in Java 8. This won't help Android users or those stuck on older versions of Java, but given that we can usually get by without a common type, anyway, we don't see the need to supply one.

**Comment by hepin1989** [comment]
@cpovirk I came from scala background,but currently have to use java 7 with guava,so I think something like `foreach`,`lastIndexWhere` things would be nice.
But yes,Guava currently not have these things,so does the `Consumer` thanks anyway.

**Comment by Sawon90** [comment]
Support Java8 on android or provide us Consumer<T> interface on guava.
