### ISSUE TITLE
Potential problems of MutableGraph vs optional mutation methods on Graph

### ISSUE THREAD

**Issue by jbduncan** [google/guava#2452]
I noticed recently that `MutableGraph` was split away from `Graph`, so I was curious as to why Sun Microsystems didn't do the same with the interfaces in the Java Collections framework. I googled it up and found [this StackOverflow answer](http://programmers.stackexchange.com/a/289372), which I think gives a very convincing explanation as to why they opted to go for optional, `UnsupportedOperationException`-based mutation methods rather than mutable sub-interfaces.

Has the Guava team considered the advantages and disadvantages of both approaches for `com.google.common.graph`?

**Comment by kevinb9n** [comment]
First note that the Graph API is still going through a lot of changes as we
prepare for release.

I haven't seen that Stack Overflow post. I'm not sure what this means:

Set could have no direct implementations, instead having MutableSet and
ImmutableSetas subinterfaces which are then used for implementing classes.
This has the same issue as above: at some point in the hierarchy, an
interface has conflicting invariants. One says "this set must be mutable"
and the other says "this set cannot change."


That is, I don't see the conflict they are talking about. In our case,
MutableGraph and ImmutableGraph are sibling types. If you interact with
something of type Graph, yeah, it might be mutable or might not be, but
that's what you're signing up for by choosing that type.

Btw, here's the official answer
<http://docs.oracle.com/javase/1.5.0/docs/guide/collections/designfaq.html#1>
to
this question for Collections.  It has mostly to do with interface
overload, a problem we aren't facing in the Graph realm.  And it's
definitely not kidding when it says this is the most controversial aspect
of the Collections design.



On Wed, Apr 13, 2016 at 3:38 PM, Jonathan Bluett-Duncan <
notifications@github.com> wrote:

> I noticed recently that MutableGraph was split away from Graph, so I was
> curious as to why the Java Collections framework didn't do the same. I
> googled it up and found this StackOverflow answer
> <http://programmers.stackexchange.com/a/289372>, which I think gives a
> very convincing explanation as to why Sun Microsystems opted to go for
> optional, UnsupportedOperationException-based mutation methods rather
> than mutable sub-interfaces.
>
> Has the Guava team considered the advantages and disadvantages of both
> approaches?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/google/guava/issues/2452>
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by jrtom** [comment]
To expand a little bit on what @kevinb9n said, the reason that common.graph isn't particularly facing interface overload is that we've basically made the decision that just about everything type-wise will be handled by runtime checks.  This is because trying to capture the following options:
* graphs {do, do not} allow parallel edges (graphs that have || edges are normally called "multigraphs")
* graphs {do, do not} allow self-loops (graphs that have self-loops or || edges are called "pseudographs")
* graphs have {directed, undirected} edges

and so on; this is only a partial tally of properties.  Using compile-time types for each of these combinations would have been a disaster.

The decision to make `MutableGraph` a subinterface of `Graph` came pretty late in our design process.  We'd considered it a while back, but at the time we decided that we should probably stay consistent with the JCF convention for collections/maps, in part because at the time more of our type system manifested in separate interfaces (e.g. directed vs. undirected).

In this particular case, creating separate `Mutable*` interfaces also resolved a design issue that we had with `Graph` vs. `Network`: `Graph` is a natural supertype of `Network`, but `addEdge(n1, n2)` simply doesn't make sense for `Network`.  

I personally prefer designs in which we don't have to worry about throwing `UnsupportedOperationException` because the methods simply don't exist where they don't make sense.  And I think that it's beneficial to have a visible signal that something _can_ be modified.

**Comment by jbduncan** [comment]
Hi @kevinb9n and @jrtom, thank you both for your explanations. I can see that things aren't as clear-cut as I first imagined.

On a side note, if you ultimately decide that having `MutableGraph` as a sub-interface is the right thing to do, I wonder if it'd be worth adding a note to `Graph` that if one is using `Graph` directly, they shouldn't assume the impl is immutable (even if the interface has no mutation methods), due to `MutableGraph` being a sub-type. (It certainly wasn't obvious to me at first that `Graph`s could be anything but immutable.)

I also wonder it'd be worth recommending the use of `MutableGraph`/`ImmutableGraph` over `Graph` to avoid this sort of confusion. I imagine this would be similar to how `List` and `Set` are encouraged over `Collection` (or `(List|Set)Multimap` over plain `Multimap` for that matter).

**Comment by kevinb9n** [comment]
I think those are both good points.


On Thu, Apr 14, 2016 at 12:08 PM, Jonathan Bluett-Duncan <
notifications@github.com> wrote:

> Hi @kevinb9n <https://github.com/kevinb9n> and @jrtom
> <https://github.com/jrtom>, thank you both for your explanations. I can
> see that things aren't as clear-cut as I first imagined.
>
> On a side note, if you ultimately decide that having MutableGraph as a
> sub-interface is the right thing to do, I wonder if it'd be worth adding a
> note to Graph that if one is using Graph directly, they shouldn't assume
> the impl is immutable (even if the interface has no mutation methods), due
> to MutableGraph being a sub-type. (It certainly wasn't obvious to me at
> first that Graphs could be anything but immutable.)
>
> I also wonder it'd be worth recommending the use of MutableGraph/
> ImmutableGraph over Graph to avoid this sort of confusion. I imagine this
> would be similar to how List and Set are encouraged over Collection (or
> (List|Set)Multimap over plain Multimap for that matter).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/google/guava/issues/2452#issuecomment-210103637>
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by jrtom** [comment]
I believe that the current Javadoc for the graph types addresses the above request:
https://google.github.io/guava/releases/23.0/api/docs/com/google/common/graph/Graph.html

If further clarification is desired, please reopen this issue.

**Comment by jbduncan** [comment]
Yep, the javadoc clarifies things enough for me, so thanks @jrtom!

**Comment by jbduncan** [comment]
Well, actually, it's the [wiki](https://github.com/google/guava/wiki/GraphsExplained#mutable-and-immutable-graphs) that explains it, but the Graph javadoc links to it, so that's fine for me. :)
