### ISSUE TITLE
Collections2.transform function type

### ISSUE THREAD

**Issue by TV4Fun** [google/guava#2455]
Is there a reason that `Collections2.transform` accepts a `Function<? super F, T>` as its second argument instead of a `Function<? super F, ? extends T>`? The latter is the type used by the underlying `TransformedCollection` type and would expand usability. It would also make in consistent with similar functions in other classes in `collect` like `Lists` and `Iterables`. In particular it would help resolve a certain ambiguity that comes up when overloading with this method in Java 8. Consider the following example:

``` java
public class Fns {
  public static <E, T> Collection<E> map(Function<? super T, E> fn, Collection<T> coll) {
    return Collections2.transform(coll, fn);
  }

  public static <E, T> List<E> map(Function<? super T, ? extends E> fn, List<T> coll) {
    return Lists.transform(coll, fn);
  }

  public static <E, T> List<E> map(Function<? super T, ? extends E> fn, T[] coll) {
    return map(fn, Arrays.asList(coll));
  }
}
```

This code works in Java 7, but in Java 8, the third overload generates an ambiguous reference error, because the compiler is not sure which of the first two overloads to use. This can be fixed by making the first version accept a `Function<? super T, ? extends E>`, but of course, this won't work with Collections2. If the type of the function argument to `Collections2.transform` could be changed, it would make our migration to Java 8 much easier.

**Comment by kevinb9n** [comment]
I would fix this problem by removing the superfluous "? extends" from the
second and third functions. It doesn't serve any valuable purpose. Yes, we
messed up with Lists.transform(); it was an accident, and got baked in that
way, but hopefully you can still get your signatures right.

Here's an excerpt from an internal resource that tries to explain the
situation.

"Pass-through" types

In some less common cases, a type is neither being produced nor consumed,
only "passed through" to the return type:

public static <T> Iterator<T> filter(

   Iterator<T> input, Predicate<? super T> predicate) { ... }

Here, predicate consumes Ts, so by the PECS rule it needs the super. And as
mentioned above, we don't put a wildcard on the returned iterator. But what
about the input iterator? It produces Ts, so it needs extends, right?

Not quite. It turns out that we don't need any additional wildcard here.
Remember that the goal of adding wildcards is "to ensure that all callers
with legal inputs will be able to invoke the method," and this is already
the case with the signature shown above. You can invoke it with an
Iterator<Integer> and a Predicate<Number>, just as you should be able to.
And you'll get an Iterator<Integer> back, which is exactly what you should
get.

The only effect of adding extends to the input iterator is that it lets the
user arbitrarily choose to store the result in a variable of type
Iterator<Number> instead. In other words, we've used the occasion of
invoking the filter method as a convenient opportunity to "upcast" the
iterator at the same time, for no particular reason that has anything to do
with *filtering*. And note that only some upcasts work; if we wanted
Iterator<Object> back -- which is *no less reasonable* than wanting
Iterator<Number> -- it wouldn't work.


We could, of course, have gone the other way and opted for promiscuous
wildcards everywhere, and we actually sunk dozens of hours into a quest to
figure out which of these two philosophies was the "right" one. Then we
gave up.


On Thu, Apr 14, 2016 at 6:54 PM, Joel Croteau <notifications@github.com>
wrote:

> Is there a reason that Collections2.transform accepts a Function<? super
> F, T> as its second argument instead of a Function<? super F, ? extends T>?
> The latter is the type used by the underlying TransformedCollection type
> and would expand usability. It would also make in consistent with similar
> functions in other classes in collect like Lists and Iterables. In
> particular it would help resolve a certain ambiguity that comes up when
> overloading with this method in Java 8. Consider the following example:
>
> public class Fns {
>   public static <E, T> Collection<E> map(Function<? super T, E> fn, Collection<T> coll) {
>     return Collections2.transform(coll, fn);
>   }
>
>   public static <E, T> List<E> map(Function<? super T, ? extends E> fn, List<T> coll) {
>     return Lists.transform(coll, fn);
>   }
>
>   public static <E, T> List<E> map(Function<? super T, ? extends E> fn, T[] coll) {
>     return map(fn, Arrays.asList(coll));
>   }
> }
>
> This code works in Java 7, but in Java 8, the third overload generates an
> ambiguous reference error, because the compiler is not sure which of the
> first two overloads to use. This can be fixed by making the first version
> accept a Function<? super T, ? extends E>, but of course, this won't work
> with Collections2. If the type of the function argument to
> Collections2.transform could be changed, it would make our migration to
> Java 8 much easier.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/google/guava/issues/2455>
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by sreejit123** [comment]
Hi, could you please let me know when we may expect this to be resolved?

**Comment by cpovirk** [comment]
A change here would have help a small number of users, and it stands a chance of breaking others, so we will probably end up living with this wart forever :(

**Comment by sreejit123** [comment]
In that case can we have another transform method?

**Comment by cpovirk** [comment]
The easiest thing is probably for you to cast:

    Collection<Super> output = (Collection) transform(input, function);

If you want to avoid the unchecked cast, you can call `Collections.unmodifiableCollection` instead.
