### ISSUE TITLE
The type com.google.common.collect.Constraint/Constraints is not visible

### ISSUE THREAD

**Issue by BinFive** [google/guava#2579]
i can't get access to the class of Constraint or Constraints, the compiler said they are not public. So how can i use these classes under a new java project?Any help guys?

**Comment by jbduncan** [comment]
`Constraint(s)` has, to the best of my knowledge, always been non-public. I don't really know why it was included in Guava to begin with, but you're not supposed to use it yourself - Guava itself uses it for implementation purposes only.

The recommended way of doing what `Constraint` does is to either use `Preconditions` or, if `Preconditions` makes your code difficult to read or it simply doesn't meet your needs, use combinations of if statements and exception throwing as you normally would.

**Comment by BinFive** [comment]
Thanks ! i just use Guava for the first time, and didn't know that Constraint(s) are suppose to be non-public . i just saw someone had use them before, Ok, forget it. Again, really appreciate for your reply!

**Comment by jbduncan** [comment]
Oh okay, I didn't realise you were a first-time user of Guava!

In that case, I'd strongly recommend that you read the Guava [user guide](https://github.com/google/guava/wiki) and explore the javadoc (latest version (19.0)[http://google.github.io/guava/releases/19.0/api/docs/]), as they will introduce you the sorts of things which Guava can do for you in a nice, readable fashion.

I presume you already know how to actually use Guava itself with a build tool like Maven or Gradle or within your IDE? If not, you may need to search for a tutorial on how to get Guava set up, as I believe the README assumes you're already familiar with how to do so.

**Comment by BinFive** [comment]
Sure thing, i will have a try : )

**Comment by jbduncan** [comment]
:+1:

(On a side note, I find it curious that you saw someone use `Constraints` before.

Maybe it was public in an earlier version of Guava? Or maybe the person you saw created a package called `com.google.common.collect` in their app, put a class there, and called `Constraints` from within that class.

I believe that's legal Java, because `Constraints` is only package-private (not completely private), and so his class would have _technically_ been in the same _package_ as `Constraints` and been able to access it, even though the 2 classes would've been in different directories.

**But this is really bad practice, so don't do it in your own code.** :wink:)

**Comment by kluever** [comment]
FWIW, `Constraints` *was* public from Guava 3.0 to 15.0, but the idea of a List/Set that has "invisible" constraints on it was not a great one, so we deprecated and eventually removed public visibility from those APIs.

I'm actively working on removing `MapConstraints` from Guava as well (which has already been deprecated for quite some time). For similar reasons, it was not a great idea to begin with.
