### ISSUE TITLE
IPv6 address validation error.

### ISSUE THREAD

**Issue by tiwarivikash** [google/guava#2587]
InetAddresses.isInetAddress("fe80::8b2:d61e:e5c:b333%15") returns false for a valid IPv6 address. Does this method not support Link-Local IP address?

**Comment by vijaykcm** [comment]
Why does your string ends with "%15"? Is that a typo?

**Comment by tiwarivikash** [comment]
Number after '%' is scope id. Please see following link for more details -
http://superuser.com/a/99753

**Comment by vijaykcm** [comment]
I see. Thank you. I looked at the code and tests, and it looks like link-local addresses with zone indices are not supported.

**Comment by noahlz** [comment]
So they're not supported....could they be?

**Comment by tiwarivikash** [comment]
Is there a reason why it is not supported?

**Comment by kluever** [comment]
At the very least, we should document that the method does not support IPv6 addresses with scope IDs.

**Comment by carl-mastrangelo** [comment]
+1 ing this issue, It's affecting my code base as well.   The move to IPv6 would be eased if Guava could support this, considering how widely used it is.   

I'm happy to submit a patch to just ignore everything after the `%` if the Guava team is interested.

**Comment by kluever** [comment]
A few clarifying questions:

1. Is there a specific format for scope IDs? The linked S/O answers seem to indicate that they can be numbers (e.g., `1` or `3`) or characters and numbers (e.g., `eth0`).
2. Are scope IDs only valid on IPv6 addresses?
3. Should anything after the `%` just be dropped on the floor when parsing?

**Comment by carl-mastrangelo** [comment]
@kluever If dropping the `%` and parsing as a v6 address results in a valid address, I think that is sufficient.  I don't see an ABNF grammar in a quick search to the RFCs, but I don't think that is a serious issue.    As long as it matches the value that `Inet6Address` returns should be enough, which just appends it to the end.   It should be a goal of InetAddresses to parse:   `InetAddresses.forString(inet6Address.getHostAddress())`

**Comment by kluever** [comment]
@carl-mastrangelo Thanks - do you have any addresses you'd like me to explicitly include in the unit tests? I've got a patch ready.

**Comment by kluever** [comment]
@cpovirk pointed out the following references:

- https://tools.ietf.org/html/rfc6874#section-2
    - `ZoneID = 1*( unreserved / pct-encoded )`
- https://tools.ietf.org/html/rfc3986#section-2.3
    - `unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"`
- https://tools.ietf.org/html/rfc3986#section-2.1
    - `pct-encoded = "%" HEXDIG HEXDIG`

**Comment by cpovirk** [comment]
Sorry, I should have read more: RFC 6874 specifically discusses how to format scope IDs _in the context of a URL_.

It does say: "A \<zone_id\> SHOULD contain only ASCII characters classified as "unreserved" for use in URIs."

But this is only a SHOULD, not a MUST, and consequently it goes on to describe escaping schemes for cases in which this is not the case.

**Comment by cpovirk** [comment]
As for dropping the scope ID:

While we're not implementing a web browser here, RFC 6874 at least says:
"It would therefore be highly desirable for a browser to remove the ZoneID from a URI before including that URI in an HTTP request."

That's at least a small point in favor of dropping it.

As a practical matter, we almost have to: Java's `Inet6Address` permits only 2 kinds of scope IDs: numeric and `NetworkInterface`. `NetworkInterface` can seemingly be an arbitrary string -- but only if it corresponds to an actual interface on the machine running the code. (And we don't have access to provide our own implementation of `InetAddress` or `NetworkInterface` ourselves, even if we wanted to.)

**Comment by kluever** [comment]
See also the section at the bottom of the class docs for [`Inet6Address`](https://docs.oracle.com/javase/8/docs/api/java/net/Inet6Address.html):

> The general format for specifying the scope_id is the following:
> `IPv6-address%scope_id`

**Comment by carl-mastrangelo** [comment]
@kluever Sure: `0:0:0:0:0:0:0:1%eno1`   is what I get on my machine when parsing `::1` with a `NetworkInterface`.

> As a practical matter, we almost have to: Java's Inet6Address permits only 2 kinds of scope IDs: numeric and NetworkInterface. NetworkInterface can seemingly be an arbitrary string -- but only if it corresponds to an actual interface on the machine running the code. (And we don't have access to provide our own implementation of InetAddress or NetworkInterface ourselves, even if we wanted to.)

Yup, ran into the same problem.   For my own unit test I tested this by using Assume and iterating the NetworkInterfaces:

https://github.com/Netflix/zuul/blob/b9f517cd46426ddde470bf088acf8eba6b258c3c/zuul-core/src/test/java/com/netflix/netty/common/SourceAddressChannelHandlerTest.java#L86-L110

**Comment by kluever** [comment]
Thanks Carl - I added that address to my test cases and it passes.

Churning this change through all of the Google tests, but I can't imagine there will be much of an issue. Will get it sync'ed out after that.

**Comment by carl-mastrangelo** [comment]
@kluever & @cpovirk thanks for the fast turn around time!   Looking forward to the next release.

**Comment by cpovirk** [comment]
Greetings from the year 2024!

We are considering a follow-up change to make `forString`, `toAddrString`, and `forUriString` actually include the scope ID in the returned `InetAddress` instance, rather than discard it as they do now.

If anyone happens to see this comment and has concerns, please let us know. In the meantime, we'll continue our research and testing.

**Comment by capotter-r7** [comment]
Greetings from later in 2024 @cpovirk ! The follow up change you mentioned above is fairly painful for us in 2 respects. I'm referring specifically to this [commit](https://github.com/google/guava/commit/3f61870ac6e5b18dbb74ce6f6cb2930ad8750a43) which introduces the fairly strange (IMO) requirement that the network interface in a parsed `InetAddress` is an actual interface on the machine running the code, as you mentioned above. 

First point - `isInetAddress` was not similarly updated and thus doesn't do any inspection of the scope. This means when we've got an IPv6 address with an "invalid" scope that we're trying to parse, `isInetAddress` will return true but a subsequent call to `forString` throws. As a consumer of this class I'd expect those two methods to agree on what a valid `InetAddress` is. 

Secondly - introducing the requirement that an IPv6 scope is valid on the machine running the code in order to instantiate an `InetAddress` is quite painful for us. It is a pretty significant bummer that we cannot model IPv6 addresses that are not valid on the particular machine doing the modeling. Ideally we would be able to treat the scope as just a string without trying to resolve it

**Comment by capotter-r7** [comment]
> Are you in a position in which you can strip off the scope ID before passing it to Guava? It sounds like you had been getting by OK without the scope ID, so I gather that you don't need a way to put that scope ID into the InetAddress instance?

Yeah I think this is the only way forward really. In many cases we receive value which could be either an IP address or a hostname, so we first check whether it can parse as an IP address using isInetAddress which why it bites us that a subsequent attempt to fully parse after that fails. This probably gives some support to your later point about which of "This doesn't look like an IP address at all" vs "I cannot make an InetAddress out of this" we actually want.

> The general principle that I've been hearing from people who know about networking (i.e., not me) is that, if machine x sees an IPv6 address with a scope from machine y on it, then something has gone wrong.

Sure, that's true if you're trying to parse IPv6 addresses with the intent of sending traffic to that address. Our use case is parsing IPv6 addresses to model events observed on other machines. 

> Arguably it's better for the Guava method to fail loudly in this case than for the calling code to fall back to some kind of "This doesn't look like an IP address at all" logic.

Yeah I kind of get this perspective as mentioned above, especially considering its a change in behavior from the previous ignoring of scope. But in the end something is either valid or not, and the javadoc pretty clearly says that isInetAddress `Returns {@code true} if the supplied string is a valid IP string literal, {@code false} otherwise.` and that forString `@throws IllegalArgumentException if the argument is not a valid IP string literal`. The definition of a valid IP string is now unclear if those two methods disagree.

Ultimately I suppose all of this is a moot point and out of guava's hands, given its impossible for either of us to instantiate an `Inet6Address` in the way that I need it to be for this use case. This leaves us have no real choice other than to continue to strip the scope as you say, then make our own class that wraps Java's `InetAddress` in order to properly support IPv6 with scope that isn't valid on the machine running the code.

**Comment by cpovirk** [comment]
Thanks. I will fix the `forString` Javadoc to have a correct `@throws` clause. (There might be another method or two that requires a similar change.)

And yeah, if I get a time machine to 20 years ago, I would strongly consider putting a proper `IpAddress` class into Guava instead of writing a bunch of utilities that operate on `InetAddress`. Then it could (along with avoiding other `InetAddress` quirks) represent any address with any scope ID. (The use case of modeling events from other machines sounds like a plausible reason to want that, at least to network-ignorant me.) But I'm sure that an `IpAddress` class would bring its own downsides—like the fact that `ipAddress.toInetAddress()` could fail if the scope ID doesn't match one on the system... which no one would expect... :)
