### ISSUE TITLE
Maps#subMap on TreeMap causes IAE "fromKey out of range" 

### ISSUE THREAD

**Issue by simon04** [google/guava#2602]
Using `Maps#subMap` from #1907 on a `TreeMap` twice instance causes IllegalArgumentException "fromKey out of range", when the latter range is coarser than the first one:

``` java
TreeMap<Integer, Boolean> treeMap = new TreeMap<Integer, Boolean>(ImmutableMap.of(1, false, 2, false, 3, false, 4, false, 5, false));
Maps.subMap(Maps.subMap(treeMap, Range.closed(2, 4)), Range.closed(1, 5));
```

My use case is to apply restrictions (sometimes based on userinput) on a `TreeMap<Long, ?>` (where `Long` corresponds to timestamps) at different spots in the application.

Tested w/ d67899df652c8a889c578a53a639d4c399925e2c.

**Comment by lowasser** [comment]
I believe this is the JDK's bug, not ours?

**Comment by lowasser** [comment]
That is, all we're doing is calling the TreeMap's subMap methods, IIRC.

**Comment by dimo414** [comment]
You might consider keeping track of the original `NavigableMap` and the current `Range`, and intersecting the `Range` as you receive new input, e.g.

```
public class MapViewport<K extends Comparable<? super K>, V> {
  private final NavigableMap<K, V> map;
  private Range<K> range;

  // constructor
  // setters for range such as intersection, union, and set

  public NavigableMap<K, V> getView() {
    return Maps.subMap(map, range);
  }
}
```

This has the added advantage of avoiding constructing recursively nested views.

As Louis says, `NavigableMap` is [documented](docs.oracle.com/javase/8/docs/api/java/util/NavigableMap.html#subMap-K-boolean-K-boolean-) to "*throw an IllegalArgumentException on an attempt ... to construct a submap either of whose endpoints lie outside its range.*" and the `Maps`/`Sets` methods simply delegate to the appropriate `NavigableMap` methods. I'd agree it'd be reasonable for `NavigableMap` to silently accept wider view ranges rather than fail, but that's the existing behaviour.

**Comment by simon04** [comment]
Thank you both for taking the time to investigate this behavior. I agree that it is a JDK issue and documented behavior.
