### ISSUE TITLE
Add "count all" ability to Multiset

### ISSUE THREAD

**Issue by Sharon-Ko** [google/guava#2623]
Nice addition - to get the count of all occurrences in the map (instead of iterate)

**Comment by kevinb9n** [comment]
This is `size()`.

**Comment by Sharon-Ko** [comment]
No, size() returns the number of keys. I'm interested in the number of values.

**Comment by kluever** [comment]
> The size() of a Multiset is the total number of all occurrences of all elements.
https://github.com/google/guava/wiki/NewCollectionTypesExplained#multiset

**Comment by kevinb9n** [comment]
It helps to not think of a Multiset as having "keys and values". It is a Collection, so it has just "elements"; these elements might look like [a, a, b, b, b, c]. The size of that Multiset would be 6. (It also has a "distinct elements" view which looks like [a, b, c].)

This is confusing because most of us realize that a Multiset would naturally be *implemented* as a Map. But it implements Collection, so it has to behave like a Collection at an API level.

If you prefer something that both works like a Map and *looks* like a Map, we have this:
https://google.github.io/guava/releases/20.0/api/docs/com/google/common/util/concurrent/AtomicLongMap.html

**Comment by jbduncan** [comment]
@Sharon-Ko Did you perhaps mean to talk about Multi**map** rather then Multi**set**?

If so, the javadocs for `Multimap.size()` should clear up matters for you. :)

**Comment by Sharon-Ko** [comment]
Sorry, my mistake. Thanks
