### ISSUE TITLE
Striped<Lock> deadlock when use different key in concurrent thread

### ISSUE THREAD

**Issue by flym** [google/guava#2653]
we use striped<Lock> generate lock to gurantee sync operation.but we detect thread dead lock when multi thread run.

example:

```
thread1->getLock(A1)->getLock(B1)

thread2->getLock(A2)->getLock(B2)
```

all use striped.get(key) and lock.lock then run...

i read the code,found that guava **only** use key hashcode and size to identity bucket,when identify same bucket,it may return the wrong lock.
as before,when getLock(A2),it may return B1 lock. just then same bucket.'

i think it must use the **strict** equals to get the right lock,just as the concurrentHashMap do it.

**Comment by Maaartinus** [comment]
I ran into exactly this some time ago and I'm afraid you can't use `Striped` when both threads need multiple locks and you don't know which in advance. The goal of `Striped` is to reduce the number of needed locks and this can be only done by mapping multiple inputs onto the same lock. You were unlucky getting
```
A1 -> L1 <-B2
A2 -> L2 <- B1
```
and you can't avoid the deadlock by changing the order as you don't know the mapping.

I'm afraid, there's no solution involving `Striped`, unless you know all locks a thread needs upfront. In case you do, then you can use `Striped.bulkGet` so you get the locks in a fixed order.

Otherwise, if you need to lock based on identity, then you can
- lock on the object themselves
- or lock on a `Cache<YourObject, YourLock>` using weak keys.

If you need to lock based on `equals`, then you can
- use a `WeakHaskMap<YourObject, YourLock>`

**Comment by flym** [comment]
ok, i finally use the internal impl such as 
```
lockStriped = new MapMaker().weakValues().initialCapacity(size).makeMap();
lockStriped.computeIfAbsent(key, t -> new ReentrantLock());
```

**Comment by saikiran939** [comment]
Even though issue is closed..just a thought why can't we use two Striped locking instances (one for A related locks and second for B related locks) ?

**Comment by flym** [comment]
@saikiran939 

the reason not only the two instance. 
I look the source,  tow DIFFRENT key may return the same lock, THIS is the question. I MUST guarrenty diffrent key mus return diffrent lock.

**Comment by saikiran939** [comment]
Understood.

But what I understood is A1 and B1 are resolving to same lock - A2 and B2 are resolving to same lock ? If that is the case I thought having two striped instances could solve the issue.

**Comment by flym** [comment]
I reread @Maaartinus  write thing. It want reduce lock num, but i wont that, to reduce lock, i think weak reference can do it. I need is real lock like sync, but he says the impl not satisfy my need.
