### ISSUE TITLE
New sparse table type

### ISSUE THREAD

**Issue by SoniEx2** [google/guava#2664]
I'm writing a music tracker and I need a sparse table that does everything listed below:

- Fast insertion of elements, at any point.
- Fast removal of elements, at any point.
- Fast insertion of rows and columns, at any point.
- Fast removal of rows and columns, at any point.
- Fast sorted iteration.
- Fast slices/subtables. E.g. if the table has 200 columns and 100 rows (not necessarily densely populated), I wanna be able to get a subtable from row 10 to row 20 and column 20 to column 30. The subtable should have comparable performance to the original table, e.g. remove(1,1) in the original table should be as fast as remove(1,1) in the subtable, even if the subtable is in the middle of the original table.
- Fast indexing is NOT required, and subtables are meant to mitigate this.

**Comment by lowasser** [comment]
This sounds like it could be satisfied by TreeBasedTable, except with more sub-table view methods?

**Comment by liach** [comment]
For iteration, caches of predecessor and successor may speed up the iteration to be O(1) (Ex. the one in [TreeMultiSet.java](https://github.com/google/guava/blob/master/guava/src/com/google/common/collect/TreeMultiset.java#L538-L539)), but the java `TreeMap`'s iteration performance is actually O(log(size)), making `TreeBasedTable` slower in iteration.

**Comment by lowasser** [comment]
IIRC TreeMap's iteration is worst-case O(log(size)) for each next() call, but is always amortized O(1)?  That is, iterating over a whole TreeMap is always O(n) in total even if some of those next() calls take longer than others.

If I remember the analysis correctly, the iteration walks each edge of the tree at most twice: once on the way down, and once again on the way up, so the total number of edge walkings is at most 2n, so the whole iteration is O(n) and the average time among all the calls to next() is O(1).

**Comment by liach** [comment]
Here is an analysis of @SoniEx2's requests:
(C: columns' size; R: rows' size)
>- Fast insertion of elements, at any point.

TreeBasedTable: Always O(log(C)+log(R))
>- Fast removal of elements, at any point.

TreeBasedTable: Always O(log(C)+log(R))
>- Fast insertion of rows and columns, at any point.

TreeBasedTable: Rows O(log(R)), Columns O(R*log(C))
>- Fast removal of rows and columns, at any point.

TreeBasedTable: Rows are O(log(R)), Columns O(R*log(C))
>- Fast sorted iteration.

TreeBasedTable: O(R*C) (linear time)
>- Fast slices/subtables. E.g. if the table has 200 columns and 100 rows (not necessarily densely populated), I wanna be able to get a subtable from row 10 to row 20 and column 20 to column 30. The subtable should have comparable performance to the original table, e.g. remove(1,1) in the original table should be as fast as remove(1,1) in the subtable, even if the subtable is in the middle of the original table.

For this one, creating a view would be O(1), all other operations are the time above, but a clone would be way slower in creation. (guess linear time)
>- Fast indexing is NOT required, and subtables are meant to mitigate this.

I do not understand what you mean by "mitigate". :confused:

**Comment by SoniEx2** [comment]
Views should be invalidated if the backing table is modified. The reason for this is that they should hold direct references to the internal data structures so the subtable is actually smaller than the real table, thus providing faster access times.

A subtable at (100, 100) should have the same performance (NOT complexity) as one at (1, 1), given that both have the same size.

**Comment by lowasser** [comment]
The definition of a "view" in the convention of the Collections framework is something that reads through to the backing collection, and reflects any modifications made to it.  I think we'd be pretty leery of violating that approach?  

That approach also has significant performance benefits of its own: getting the view itself takes constant time, so it doesn't do any more work than it has to, especially if you just want it for a very simple operation: e.g. copying parts of the internal data structure would be overkill if you just wanted the size of a particular sub-range of the tree.  If you wanted to have "direct references to the internal data structures", it's not clear how you'd expect that to work.  You could copy that entire section of the internal binary search tree, but as alluded to above that's depressingly expensive.  But if you don't do any copying...what do you do?  If one of the elements in your sub-range happens to be the root of the entire data structure's tree, then you're carrying the whole thing around anyway; you're not actually saving anything.  And with either approach, you're violating decades of precedent of how Java's collections have always been built and how developers have expected them to work.  Additionally, we'd need to build a whole new binary search tree implementation, which we're generally pretty leery of: we made a special exception for TreeMultiset because we believed subMultiset().size() was a really important operation to optimize; that "histogram"-style queries where you asked "how many elements are in this range?" were a key use case.

Finally: how big is your data structure expected to get that O(log n) isn't acceptable?  I would tend to expect, I confess, that by the time O(log n) becomes a serious performance bottleneck, you should be using an actual database instead of an on-heap collection implementation.

**Comment by SoniEx2** [comment]
Maybe this is a very specialized use-case after all... Sorry.

**Comment by liach** [comment]
>Additionally, we'd need to build a whole new binary search tree implementation, which we're generally pretty leery of: we made a special exception for TreeMultiset because we believed subMultiset().size() was a really important operation to optimize; that "histogram"-style queries where you asked "how many elements are in this range?" were a key use case.

@lowasser For the balanced binary tree, I have a suggestion of data structure: https://www.scribd.com/document/3072015/10-%E9%99%88%E5%90%AF%E5%B3%B0-Size-Balanced-Tree
This type of tree called "Size Balanced Tree" maintains a size field instead of a height field compared to AVL Tree.
