### ISSUE TITLE
Add Splitter.toArray(String)

### ISSUE THREAD

**Issue by ogregoire** [google/guava#2679]
Please consider adding the method `splitToArray(String)` to `Splitter`.

## Why do I want it?

1. Because I often use arrays internally when reading speed matters more than the rest.
2. Because `Splitter.splitToList(String)` was added in release 15 and an array counterpart seems totally acceptable for the same reasons `Splitter.splitToList(String)` was added..
3. Because splitting to arrays is the default Java implementation (`String.split(String)`) and I'd kind of expect `Splitter` to provide if not the same behavior (luckily) at least the same output type.
4. Because repeating `String` at least once is too verbose for such a simple use case. All alternatives need the text `String` to be written at least one extra time.

## What alternatives can I use?

I saw several ways to write this but none are really convincing:

### Guava one-liner

    String[] split = Iterables.toArray(splitter.split(text), String.class);

I'm not convinced by this, especially when I see that [StringsExplained](https://github.com/google/guava/wiki/StringsExplained) still recommends using `Lists.newArrayList(splitter.split(text))` even though `Splitter.toList(String)` exists. Also, since it's obvious we're using `String`s, I don't see why I'd have to repeat `String` several times.

### Inline, no cast, but reflection

     String[] split = splitter.splitToList(text).toArray(new String[0]);

This is rather easy to write in one line, but has the strong disadvantage to internally use reflection (because you rarely get an array of length 0 when you split from an unknown length). Again, the repetition of `String` as a type narrower is annoying.

### Inline, cast

    String[] split = (String[])splitter.splitToList(text).toArray();

The casting is rather obvious, but using Guava, I don't expect to cast very often, actually. There are lot of tools that help us avoid this. Once more we have to declare the expected return type when all I want is to split `String`s.

### Optimized (?)

    List<String> splitList = splitter.splitToList(text);
    String[] split = splitList.toArray(new String[splitList.size()]);

Probably the best answer in regards to speed (hopefully), but is on two lines because it has to use a variable. Also, this is totally redundant

**Comment by Stephan202** [comment]
The fourth variant [may](https://shipilev.net/blog/2016/arrays-wisdom-ancients/) in practice not be faster than the second variant.

**Comment by lowasser** [comment]
I believe the intended idiom is #2: "Inline, no cast, but reflection."

Observations, one at a time:

- Something ArrayList-like will _have_ to get used internally, because we don't know ahead of time how many elements to expect.  We're going to be doing dynamic resizing.
- I would expect "Inline, cast" to fail at runtime with a ClassCastException.  An `Object[]` is not-a `String[]`.
- It may be counter-intuitive, but `new String[0]` is _faster_ than `new String[splitList.size()]`.  https://shipilev.net/blog/2016/arrays-wisdom-ancients/ is a ludicrously thorough document explaining how and why.

If we were to add a utility method to do this, I would implement it as `splitToList(string).toArray(new String[0])`.  I don't think any other implementation could do better.
