### ISSUE TITLE
Don't put Exception in CacheStats.toString()

### ISSUE THREAD

**Issue by f7sharp11** [google/guava#2683]
Please avoid putting Exception with a capital E into strings.  These end up in logs and cause headaches for both manual and automated things that look for such a string.  I've seen lots of regexes changed from 'Exception' to '[^d]Exception' to work around this.  Which will work fine until someone throws an exception that ends with a d.

```
  @Override
  public String toString() {
    return MoreObjects.toStringHelper(this)
        .add("hitCount", hitCount)
        .add("missCount", missCount)
        .add("loadSuccessCount", loadSuccessCount)
        .add("loadExceptionCount", loadExceptionCount)
        .add("totalLoadTime", totalLoadTime)
        .add("evictionCount", evictionCount)
        .toString();
  }
```

**Comment by kluever** [comment]
I don't think we should change this just because some times people grep for `Exception`?

**Comment by cpovirk** [comment]
Yeah, I think this would also imply that no one should never include "Exception" in a method name. For that matter, it would imply that no one should ever use "Exception" in a class name, since presumably you're grepping only for the first line of a logged exception. Possibly you'd have better luck grepping for something like `^[\w.]*Exception:` (or something else adapted to your logging format) or at least for `Exception\b`. Or you can just pipe the result through `grep -v loadExceptionCount`.
