### ISSUE TITLE
Graphs.transform*

### ISSUE THREAD

**Issue by ogregoire** [google/guava#2685]
When I'm creating my graph, I don't know all the nodes/edges, so I use proxies like the ids of the nodes and the ids of the edges while registering the edges and nodes as they come in. Think of this as a stream being parsed where the node 1 says "I'm linked to 2 and 4", but we haven't parsed 2 nor 4 already.

When I'm done creating it, I'd like to have a copy of the graph but with the actual nodes and edges. So similarly to all the `Maps.transform*` methods, I'd like to have `Graphs.transform*` methods where applicable.

The only alternative I see is to create proxy items before creating the graph, but that's a heavy burden on the user,

**Comment by jrtom** [comment]
Interesting.  I'd have to think about what the API for such a thing would look like, but I'm certainly familiar with the use case (this is a pretty common case for reading a graph in from some common graph formats).

So to expand slightly, what you're asking for a method like this (as well as similar ones for other types):

```java
MutableGraph<T> transformNodes(Graph<N> graph, Function<N, T> nodeTransformer) {
  MutableGraph<T> transformedGraph = GraphBuilder.from(graph).build();
  for (N node : graph.nodes()) {
    transformedGraph.addNode(nodeTransformer.apply(node));
  }

  for (EndpointPair<N> endpoints : graph.edges()) {
    transformedGraph.addEdge(
      nodeTransformer.apply(endpoint.nodeU()), nodeTransformer.apply(endpoints.nodeV()));
  }
  
  return transformedGraph;
}
```

**Comment by lowasser** [comment]
I observe that doing this as a copy would be inconsistent with the other transform methods, but doing this as a view seems impractical: you'd need bidirectional conversion, I'd expect. =/

**Comment by jrtom** [comment]
@lowasser You could do it as a view fairly straightforwardly using Collections2.transform() on the returned Sets; this would require more boilerplate (because you'd have to override each affected method) but would otherwise look (in terms of implementation) internally much like Graph.transpose().

The point of my code above was to make sure that I correctly understood the specification, not necessarily as a concrete proposal.  :)

**Comment by jrtom** [comment]
@lowasser Why would you expect that you might want bidirectional conversion?

**Comment by lowasser** [comment]
I'm not sure I follow?  Collections2.transform returns a Collection, not a Set, isn't that a dealbreaker?  We don't *have* a Sets.transform because you can't do contains efficiently.

**Comment by jrtom** [comment]
@lowasser Ah, I see what you mean, that's why you would need a bidirectional conversion in order to make a view work.  `Collections2.transform()` would work but would be inefficient for contains() checks.

Which explains, also, why Maps.transform*() doesn't include anything that transforms the keys, just the values.

In any case, in the specific use case mentioned here, the original graph (built using the IDs and not anything else) is just going to be thrown away, so I don't know that building a copy would be a big deal.

Coming back to the original question: @ogregoire, another option that you could use would be to populate the graph with the final node objects, but:
(1) have `equals()` and `hashCode()` for the node objects be based only on the IDs
(2) populate the rest of the node fields as they're available; you could do this by maintaining a `Map<NodeId, Node>` yourself, so you could efficiently access the node objects you'd added.

That would probably be more efficient than creating a transformed copy of the original graph.

**Comment by ogregoire** [comment]
Thanks for your considerations, both of you.

What you showed as example, @jrtom, is exactly what I'm looking for. I'm mostly working with value graphs at the moment so I'd expect indeed more methods than the one you developed.

Regarding your solutions 1 and 2, while I didn't think of them (it's the first time I work with graphs), they don't seem very Guava-esque.

**Comment by jrtom** [comment]
@ogregoire I wasn't very clear in my last post: (1) and (2) together are part of a unified strategy.

Also, (1) is necessary if the nodes are to be mutable; otherwise you might be changing the hashcodes of the nodes as you populate them, which would break things.  (See this section of the common.graph User's Guide: https://github.com/google/guava/wiki/GraphsExplained#graph-elements-nodes-and-edges)

I understand that the performance of the transformation isn't necessarily the most important consideration to you in the context of deserialization.

A third option would be to create the graph based only on the node IDs, and maintain a map from node IDs to node objects, but then you'd have to carry that map around.

**Comment by jrtom** [comment]
This is not an unreasonable thing to want to do, but I'm not sure that it's sufficiently broadly useful for us to include it in Guava.  Closing this for now; if someone wants to chime in and say "hey, I want that too" then we can reconsider.

(In the meantime, the above code should work just fine for anyone that needs this capability.)

**Comment by jbduncan** [comment]
@jrtom I actually wonder if it's a bit premature to close this issue, because Bazel's BUILD_file_generator has a [function](https://github.com/bazelbuild/BUILD_file_generator/blob/dfa872bb8f60d679707a53f2dd2eb93b106710bf/src/main/java/com/google/devtools/build/bfg/ClassToSourceGraphConsolidator.java#L60-L91) which is vaguely similar to what I understand this issue is requesting, and it specifically comes with a note saying:

```text
// TODO(bazel-team): Migrate this function into Guava graph library
```

**Comment by jrtom** [comment]
That's a good observation, although the Bazel team hasn't contacted us to ask for that capability (and that comment has been sitting there since the file was created over a year ago).  :)

(Just curious: how did you happen to come across that?)

Also, that particular method does specialized checks that the transformation code above doesn't (and wouldn't) do, so they actually might want to do a two-stage transformation: first, check the nodes to see whether any of them are illegal by their standards (and filter self-loops), and second, do the actual transformation.

**Comment by jbduncan** [comment]
(@jrtom I just happened to discover the project when browsing the [bazelbuild](https://github.com/bazelbuild) org page a few days ago (Bazel's interested me for a while now), and in turn I got curious about the project's implementation, so I skimmed over its internal files. I just happened to view a particular file, and in the process I found that particular comment.

Kind of a cool coincidence, I'd say. :smiley:)

**Comment by jbduncan** [comment]
Okay, sounds like a good reason to keep this issue closed for now then. Anything to keep the open issues reasonably less cluttered is a good thing in my book. :+1:

**Comment by Sadgrinner** [comment]
Hoping to help others that also want this feature, I wanted to add a comment revising @jrtom 's example method at the top.

You can't use this directly:
```
MutableGraph<T> transformNodes(Graph<N> graph, Function<N, T> nodeTransformer) {
    MutableGraph<T> transformedGraph = GraphBuilder.from(graph).build();
    // ...
}
```
... because the `GraphBuilder.from(graph).build()` line wants to return a `MutableGraph<N>`, not `MutableGraph<T>`.

You'll get an error message like this:
> "Incompatible types.  Required MutableGraph<T> but 'build' was inferred to MutableGraph<N1> : no instance(s) of type variables exist so that T conforms to N"

My alternate suggestion (which is strictly for directed graphs) is this:

```
    private <N, T> Graph<T> isomorphicTransformation(final Graph<N> originalGraph,
                                                     final Function<N, T> nodeTransformer) {
        MutableGraph<T> transformedGraph = GraphBuilder.directed().build();
        Map<N, T> originalNodesToNewNodes = Maps.newHashMapWithExpectedSize(originalGraph.nodes().size());

        // transform each node of the originalGraph into a new object suitable for the transformedGraph
        // and add each new node object to transformedGraph in the same order as the originalGraph
        originalGraph.nodes().forEach(originalNode -> {
            T newNode = nodeTransformer.apply(originalNode);
            transformedGraph.addNode(newNode);
            originalNodesToNewNodes.put(originalNode, newNode);
        });

        // now add each edge so the transformedGraph has the same edge mappings as the originalGraph
        originalGraph.edges().forEach(endpointPair ->
                transformedGraph.putEdge(
                        originalNodesToNewNodes.get(endpointPair.nodeU()), originalNodesToNewNodes.get(endpointPair.nodeV())));

        return transformedGraph;
    }
```

This version uses more memory, since it stores each of the transformed nodes into a Map.

That was an acceptable tradeoff for my use case; I was running into an error with this part in the original suggestion:
```
  for (EndpointPair<N> endpoints : graph.edges()) {
    transformedGraph.addEdge(
      nodeTransformer.apply(endpoint.nodeU()), nodeTransformer.apply(endpoints.nodeV()));
  }
```

In particular, note how the original suggestion calls `nodeTransformer.apply` multiple times - once when adding the nodes, and again when adding the edges.  If you happen to have a poorly-defined hashCode and equals method on your nodes, what this means is your "isomorphic" graph ends up having more nodes than it is supposed to have!

Thus, if you're willing to accept the higher memory costs of storing the transformed nodes in a Map (in order to guarantee they're created once and only once), you ensure that your end graph is indeed isomorphic to the original input graph.  This may also be a better solution if your `Function` that does the node transformation is super-slow, too.

**Comment by jrtom** [comment]
@Sadgrinner that's a good point, thanks for the catch.

A simpler approach would be to modify my original snippet to adapt the code from `GraphBuilder.from()` that creates a new instance based on an existing one:

```java
GraphBuilder<T> builder =
    (originalGraph.isDirected() ? GraphBuilder.directed() : GraphBuilder.undirected())
        .allowsSelfLoops(originalGraph.allowsSelfLoops())
        .nodeOrder(graph.nodeOrder())
        .expectedNodeCount(originalGraph.nodes().size())
        .build();

// etc.
```

That said, I agree that if the `Function` is super-slow that your version would be faster...but it's also the case that if the `Function` is super-slow that it could easily be made to do its own caching, and it's probably better for the transformation function to not worry about that.

As for your concern about poorly-defined `hashCode()` and `equals()` methods: that's already mentioned in the spec here: https://github.com/google/guava/wiki/GraphsExplained#elements-must-be-useable-as-map-keys

That is, trying to use node objects that have broken `hashCode()/equals()` methods is already going to cause trouble (and would with your Map-based solution as well).

**Comment by Sadgrinner** [comment]
@jrtom That's better for sure!

Note though that this line:
```
        .nodeOrder(graph.nodeOrder())
```
won't work for the same `T`-versus-`N` problem: the original input graph's `.nodeOrder()` will return `com.google.common.graph.ElementOrder<N>`, whereas the `GraphBuilder<T>` demands an `ElementOrder<T>`.

Any suggestions there?

**Comment by jrtom** [comment]
@Sadgrinner whoops, another good catch.  :)

The most obvious way to deal with that is to just brute-force it, something like (I haven't checked the code below, just winging it):

Where this gets tricky

```java
static <T> ElementOrder<T> transformedNodeOrder(Graph<?> graph, @Nullable Comparator<T> comparator) {
  switch graph.nodeOrder() {
     case UNORDERED: return ElementOrder.<T>unordered();
     case INSERTION: return ElementOrder.<T>insertion();
     case SORTED: return ElementOrder.<T>sorted(checkNotNull(comparator));
     default: throw new IllegalStateException(...);
}
```

and then call `transformedNodeOrder(originalGraph, comparator)` instead of `graph.nodeOrder()`.

I think that should do it.  Needless to say, for cases where you don't have a comparator you should probably overload this method so that you don't have to supply one.
