### ISSUE TITLE
Publish ReverseListIterator

### ISSUE THREAD

**Issue by guai** [google/guava#2706]
Pls make ListIterator impl used here com.google.common.collect.Lists.ReverseList#listIterator a separate public class and/or provide static method to create it somewhere.
Now I can reverse list itself but not listIterator

**Comment by jbduncan** [comment]
@guai Can you explain why you want this static method to be exposed? Have you already considered `Lists.reverse(theList).listIterator()`? If so, can you explain why it doesn't meet your needs?

**Comment by guai** [comment]
That's exactly it. I have some API method returning ListIterator and not list itself. And then I need to iterate it in reverse order. Actually wrap it in reverse iterator and pass to another already existing class which accepts iterator. ListIterator is itself an iterator. So this Reverseing anonymous class from ReverseList#listIterator does exactly what I need.

**Comment by guai** [comment]
Of course I can do it once again myself, but its already there hidden. I think expose it is a good idea

**Comment by lowasser** [comment]
It's not actually clear to me that we can expose that API at all without the greater context of the list, because I think you need the `size()` to compute the index information for the reverse iterators.  (Confirmed by looking at the implementation.)

Do you really not have any control over this problematic API that's not giving you the List?

**Comment by guai** [comment]
@lowasser, I have the control. And I already did it. But my rule of thumb when I deal with collections is to check if there something already done in guava. In this case it is, but hidden.
Is there any smell in code that returns a ListIterator instead of List which I'm not aware of?
I see no problem in this API.

**Comment by jbduncan** [comment]
@guai I can't speak for @lowasser, but I think the main problem with an API that returns `{List}Iterator` is that if one needs to go through (or traverse over) the elements in the `{List}Iterator` more than once, or in a different order (like reverse order), then the only option is to _copy_ the elements in the `{List}Iterator` into an intermediate data structure, like an `ArrayList`. Understandably, this copying wouldn't be memory or time efficient.

If your API were to return `Stream`, then that would be a little bit better because one could then perform functional operations like `map` and `filter` easily. However, in this case it doesn't solve the problem that you need to reverse it, as Streams can only be traversed once like {List}Iterators.

In this case, if you could make this API of yours return a `List`, then that would allow you to create your own "reverse view" class and solve your problem efficiently. This is because (1) lists have a finite number of elements that you can query with `size()`, and (2) you can easily access elements in a list in reverse order using `get(size() - index + 1)` (as shown in Lists.ReverseList#reverseIndex) without putting them into a new list.

And since Guava already provides a reverse "view" class for lists via  `Lists.reverse`, you don't even need to implement this reverse-view class yourself. Thus, if you can somehow make your API return a `List`, you can then easily write `Lists.reverse(yourList).iterator()` and pass the resulting iterator to your other API, solving your problem efficiently both memory- and time-wise.

I hope this helps.

**Comment by guai** [comment]
@jbduncan, but ListIterator doesn't have to be backed by a list. Its just something traversable in both directions. API may do something more than just be a list, it may (I dunno) notify some other services about content being iterated etc.
To implementing a list is more of a trouble. And in this case one should implement ListIterator anyway. To return custom ListIterator looks quite reasonable to me.

I don't like the assymetry here. Its like a blind spot. Some useful class was written but I cannot use it.

**Comment by jbduncan** [comment]
Hi @guai,

> but ListIterator doesn't have to be backed by a list.

You're right, it doesn't.

But if it isn't backed by a list, then that would surprise maintainers in the future, wouldn't it? I'd argue that misusing `ListIterator` like this makes this API harder to understand and use.

Is this API something you have control over? If so, I'd encourage you to replace its return type with a custom interface that has whichever methods from `ListIterator` that are needed.

If not, then I think the most reasonable solution would be something like,

```java
ListIterator<T> listIterator = theListIteratorReturningApi();
Iterator<T> reverseIterator = Lists.reverse(ImmutableList.copyOf(listIterator)).iterator();
theReverseIteratorAcceptingApi(reverseIterator);
```

> To return custom ListIterator looks quite reasonable to me.

Please correct me if I missed something, but by my understanding (and [@lowasser's](https://github.com/google/guava/issues/2706#issuecomment-271952523) apparently), it's not possible to implement an efficient reverse-view of a `ListIterator` unless it's backed by a list, because the reverse-view needs to call `backingList.size()` to implement `nextIndex()` and `previousIndex()` in O(1) time.

**Comment by lowasser** [comment]
I'm not sure I buy that, though.  A ListIterator, unlike a normal Iterator, has index information, and that really seems to make it invariably attached to a List.  The AbstractSequentialList implementation skeleton lets you implement a List with nothing more than the ListIterator and the size(), which is also the minimum you need to reverse a ListIterator anyway.

**Comment by jbduncan** [comment]
@lowasser summarised it nicely for me. :)

**Comment by guai** [comment]
Ok then. Gone inventing the wheels :(
