### ISSUE TITLE
Allow injection of clock into ExpiringMemoizationSupplier to allow for testing

### ISSUE THREAD

**Issue by mokah** [google/guava#2727]
To allow testing of ExpiringMemoizationSupplier, a second constructor with `@VisibleForTesting` should be added that allows the injection of a clock. 

Right now it is being tested by calling `Thread.sleep(x) `but an injection of a clock would be a better way to test, I believe. Thoughts?

**Comment by cgdecker** [comment]
It could be a slight improvement, perhaps, but I'm not sure it's worth it in this case.

The main reason I say that is because `ExpiringMemoizingSupplier` is `Serializable`, and changing it to have a `Ticker` field to allow for this testing would also require making our system time `Ticker` serializable... I don't know that that's something we'd want to do, because it doesn't have any state or data to actually serialize and instead just relies on the system clock.
