### ISSUE TITLE
MutableGraph removeEdge throws ConcurrentModificationException if iterating through adjacentNodes()

### ISSUE THREAD

**Issue by sudharsannr** [google/guava#2739]
I have seen that the documentation suggests that the accessor methods on mutable graph throws `ConcurrentModificationException` while iterating through `adjacentNodes()`. I have a sample dfs that removes edges while performing dfs:
```
private Set<EndpointPair<String>> backEdges(MutableGraph<String> g, String root, String current, Set<String> visited,
			Set<EndpointPair<String>> backEdges)
	{
		visited.add(current);

		for (String n : g.adjacentNodes(current))
		{
			if (!visited.contains(n))
			{
				backEdges(g, current, n, visited, backEdges);
			}
			else if (!n.equals(root))
			{
				// Found a back-edge
				EndpointPair<String> edge1 = EndpointPair.ordered(current, n);
				EndpointPair<String> edge2 = EndpointPair.ordered(n, current);

				logger.info("Removing edge {} {}", edge1.nodeU(), edge1.nodeV());
				// Remove from graph
				g.removeEdge(edge1.nodeU(), edge1.nodeV());
				g.removeEdge(edge2.nodeU(), edge2.nodeV());

				// Add to result set
				backEdges.add(edge1);
				backEdges.add(edge2);
			}
		}

		return backEdges;
	}
```

A node is removed and immediately the iterator throws exception. Is there a way that this could be avoided though only `removeEdge()` is applied here?

**Comment by jbduncan** [comment]
Hi @sudharsannr. There are at least two solutions for this unfortunate little problem with the spec of `MutableGraph` that I can think of:

1. In the for-loop, copy the `g.adjacentNodes(current)` into an `ImmutableSet`. This prevents ConcurrentModificationException because the newly-created immutable set is never modified in the for-loop:
```java
for (String n : ImmutableSet.copyOf(g.adjacentNodes(current))) { // copy prevents CME
    ...
}
```
2. If copying the nodes is too expensive memory- or time-wise for your needs, try _recording_ the edges to remove within the for-loop, and then remove them all after exiting the for-loop. Something like below (I've not run it through a compiler or tested it, so YMMV):
```java
		visited.add(current);

		List<ImmutableList<String>> edgesToRemove = new ArrayList<>();
		for (String n : g.adjacentNodes(current))
		{
			if (!visited.contains(n))
			{
				backEdges(g, current, n, visited, backEdges);
			}
			else if (!n.equals(root))
			{
				// Found a back-edge
				EndpointPair<String> edge1 = EndpointPair.ordered(current, n);
				EndpointPair<String> edge2 = EndpointPair.ordered(n, current);

				logger.info("Removing edge {} {}", edge1.nodeU(), edge1.nodeV());
				// Record to remove from graph later
				edgesToRemove.add(ImmutableList.of(edge1.nodeU(), edge1.nodeV()));
				edgesToRemove.add(ImmutableList.of(edge2.nodeU(), edge2.nodeV()));

				// Add to result set
				backEdges.add(edge1);
				backEdges.add(edge2);
			}
		}
		// Remove recorded edges from graph now
		for (ImmutableList<String> e : edgesToRemove) {
			g.removeEdge(e.get(0), e.get(1));
		}

		return backEdges;
```

**Comment by jrtom** [comment]
@jbduncan I'm not sure what problem you're referring to, exactly.  How does the MutableGraph spec differ from what you think it should be?

If you're iterating over the nodes adjacent to a particular node, and you're removing edges while you're doing that, then you may be modifying adjacency relationships, and so throwing a CME sounds like exactly what I would expect to happen.  (Even if I hadn't been leading this project.  :) )

(Note that we have to do exactly this when a node is removed from the graph, because all incident edges must also be removed--so we have to be careful to do this in such a way as to not trigger a CME.)

So yes, either of @jbduncan's solutions would work, although the effects are not identical in general (they might be in this case, I haven't worked it through in detail).

If you create a copy [1] of the adjacent nodes (Solution (1)), it may make a difference in what order you visit the adjacent nodes, because the modifications you might do can be affected by previous modifications.  

If you record the elements to remove and then remove them all at once in a second pass, then the modifications will (in effect) all happen in parallel and can't affect one another.



[1] it need not be an immutable copy, it just needs to not be a view into the graph)

**Comment by sudharsannr** [comment]
Option 1 would work. Option 2 would not work since it is a recursive call and cannot defer removing the edge at the end. My guess is that when edges are removed, successor and predecessors would be affected.

**Comment by jbduncan** [comment]
Hi @jrtom, apologies, I realise with hindsight that it was strong of me to refer to the CME-throwing behaviour of MutableGraph as a "problem".

What I'd meant to say was, when I first encountered the CME-throwing behaviour of MutableGraph whilst iterating over one and adding new nodes to it in one of my personal projects, I was rather surprised by the CME because I didn't expect it. (I think I experienced this before the very well-written piece on Graph in the wiki was written). However, having thought about it, I understood (and still do understand now) why it throws CME, and your explanation of why it throws CME summarises it quite nicely. :)

**Comment by jrtom** [comment]
@jbduncan no worries, I'm always open to the idea that I might have made a mistake.  :)

Glad to hear that the wiki has been helpful.
That said, if you think that there's some way in which this issue needs to be better highlighted there (or elsewhere, e.g., in the Javadoc), please file a bug.  Accurate and helpful documentation is important to us.
