### ISSUE TITLE
Any interest in a PR making BloomFilter lock-free?

### ISSUE THREAD

**Issue by Valloric** [google/guava#2748]
As part of my work at LinkedIn, I've created a lock-free version of Guava's `BloomFilter` class (technically, a lock-free version of the `BitArray` class inside `BloomFilterStrategies`). **Would Guava upstream be interested in seeing a PR for this change?** The PR would naturally come with extra tests.

### Short overview

Our use-case involves a hundred+ threads doing a total of millions of read QPS on the bloom filter with ~20 QPS of writes. So I wrapped the bloom filter with a read-write lock. This wasn't performant enough though on the read side; after lots of benchmarks and analysis, the root cause was the write lock; even removing the read locks (which of course introduces race conditions, but was done for the sake of a benchmark) made no difference for read path perf... but removing both read _and_ write locks improved read perf greatly (but it would of course be terribly unsafe). My guess is that it was exclusive access to the cache line that stored the lock data that caused excessive CPU cache bus traffic, but I don't have data to back that up.

Replacing the internals of the BitArray so that it used an `AtomicLongArray` for the `data` member along with compare-and-swap usage (plus an `AtomicLong` for the `bitcount` member) improved perf substantially.

This is all on a modern server CPU with 24 logical CPUs (12 cores) + HotSpot Java 8 JVM.

**Comment by lowasser** [comment]
I took a crack at this once but never really focused on it.  If you've got something tested successfully in production, I'd love to see it.

**Comment by Valloric** [comment]
Great! I'll send a PR. It might take a bit because:

1. I have a lot of stuff on my plate right now. :)
2. I need to sort out the CLA business.
3. I stripped out all the serialization bits for our `LockFreeBloomFilter` fork; you guys definitely want to keep those so it will require a bit of work.

**Comment by Valloric** [comment]
Got the code into shape for a PR. Waiting on internal legal review (part of getting CLA stuff squared away). I'm told this will take about a week.

**Comment by ben-manes** [comment]
Are you using a Bloom-1 design ([paper](http://www.cise.ufl.edu/~tali/1569342377.pdf), [fix](http://sci-hub.cc/10.1109/TPDS.2014.2378268))? Otherwise you'll run into races that may not be acceptable. However, it requires a slightly different equation per the second paper.

**Comment by Valloric** [comment]
@ben-manes I haven't referred to the literature before going down the lock-free path (I probably should have) because my intention was not to create the most optimal implementation (like the one memory access version the paper you cite advocates), but merely a superior one to what's currently in Guava. I erred on the side of: 1) simplicity of implementation, 2) correctness) and 3) "good enough" performance.

I'd _love_ to hear your thoughts on the code (once my legal team clears it for publishing).

This change also wasn't the only one that contributed to perf in our fork of the BloomFilter; actually the biggest benefit came from switching away from Murmur3 as the hash function and [using xxHash from the Zero Allocation Hashing project](https://github.com/OpenHFT/Zero-Allocation-Hashing) along with the Kirsch-Mitzenmacher approach exhibited in the MURMUR128_MITZ_32 strategy. 

[JMH](http://openjdk.java.net/projects/code-tools/jmh/) benchmarks on the BloomFilter with representative data for our service showed the xxHash approach taking ~93ns for `mightContain` vs ~440ns for the MURMUR128_MITZ_64 strategy that's used by default. 

The third change I made (which I very much doubt Guava upstream would like to merge) was to rip out the `Funnel` business, hardcode String as the BloomFilter key (it's the only key type we use) and use a custom `toAsciiBytes` String -> byte[] conversion function [mentioned on this page as the fastest approach.](http://java-performance.info/charset-encoding-decoding-java-78/) I benchmarked various other Charset conversions (including the "unencoded chars" approach Guava uses) and the custom function was consistently 30% faster.

We can get away with that since we know all our keys are ASCII Strings, but Guava can't.

**Comment by ben-manes** [comment]
Guava's BloomFilter is a bit of an odd result. Initially there were claims that a BF was too slow as one would have to use a `SecureRandom` to have a good distribution and dynamically configure `k` hash functions. I jumped in having just written one as interview practice (as impractical and not intended to be viewed) using a normal hash function, bitwise ops, and deriving multiple due to reading [Less Hashing, Same Performance: Building a Better Bloom Filter](https://www.eecs.harvard.edu/~michaelm/postscripts/rsa2008.pdf). Someone else wrote a blog analyzing that proposal, which unblocked the Guava team. But I wasn't involved otherwise past that initial thread and a brain dump over lunch.

The use of allocation surprised me and I think its the dominant cost of Guava's implementation. It makes sense as a very elegant API, but also a poor fit for data structures where performance matters. Usually one builds data structures where the internals bypass elegant APIs because performance matters. So Guava's is more of a good example to learn from for average cases, but not when performance is important.

That then begs the question of whether Guava wants a fast implementation. The library is best viewed as having clean APIs, excellent code, and good enough for the simple common cases. But when performance and special cases emerge, its best to deviate away. Which leads to your custom implementation being the right approach for you, but may not fit the precedent the Guava team has set.

If @lowasser is interesting in driving this forward iterating on your proposal, then maybe we should dig into the latest research to see what other gems we can incorporate.

**Comment by Valloric** [comment]
> The library is best viewed as having clean APIs, excellent code, and good enough for the simple common cases. But when performance and special cases emerge, its best to deviate away. Which leads to your custom implementation being the right approach for you, but may not fit the precedent the Guava team has set.

I agree. I think it's perfectly fine for Guava to aim for a reasonable and sound implementation that works well in a wide variety of cases even if that leaves some perf on the table. When someone really needs lots of perf, it's a great base to start from (Apache v2 FTW); it certainly saved me a ton of time since I didn't have to write everything from scratch.

Though IMO it also makes sense to improve that base perf when possible without impacting the traits you mentioned (generality, API, etc). The lock-free PR I have sitting on my machine is a fairly small diff. It doesn't change the external APIs at all and strictly improves perf. Since common  bloom filters use-cases are write-light and read-heavy and atomic _reads_ (not writes) are free on x86 (and x86-64) because of that architecture's memory model, even the single-threaded use-case won't be negatively affected. And that's without mentioning that a single-threaded use-case for a bloom filter is... rare.

**Comment by Valloric** [comment]
Just wanted to drop a note saying that I haven't forgotten about this; my patch is winding its way through our internal legal review. Sorry about the delay folks!

**Comment by Valloric** [comment]
I've received all the legal approvals; I plan on sending the PR later today.

**Comment by Valloric** [comment]
Posted the PR: https://github.com/google/guava/pull/2761
