### ISSUE TITLE
Evaluate if ForwardingCollection should forward spliterator()

### ISSUE THREAD

**Issue by ChristianCiach** [google/guava#2775]
I am not entirely sure about this, but shouldn't ForwardingCollection also forward calls to spliterator()?

The JavaDoc has a default method method warning that states:

> This class does not forward calls to default methods. Instead, it inherits their default implementations. When those implementations invoke methods, they invoke methods on the ForwardingCollection. 

While this may be true, I think spliterator() could be an exception. Let's assume I want a ForwardingList to delegate its calls to an ArrayList. An ArrayList is easily splittable and overrides spliterator() to use its efficient implementation of Spliterator.

In this case, when using a ForwardingList and not overriding spliterator() manually, the default spliterator() implementation of the List interface will be used, which is a slow iterator-based implementation.

What do you think? Am I overlooking something? Or is this by design?

**Comment by cpovirk** [comment]
It's by design, more or less.

I think the problem arises only when people override methods. As an extreme example, suppose that an author has created a `ForwardingTransformingList` that overrides all getters and setters to apply a function to each value before/after forwarding. The only thing the author wouldn't override would be `size()`, since transforming individual elements doesn't affect size. If we suddenly start forwarding `spliterator()`, then its users start seeing the untransformed items when they use streams.

I don't know if that particular example ever comes up (though it might), but I think that similar cases do. For example, I think that we have something like this: An `unmodifiableMap` implementation defines a `forwardingUnmodifiableEntrySet` method that wraps each entry in `unmodifiableEntry` before returning. If we start forwarding its `spliterator()` calls, then users can access the underlying modifiable entries.

For what it's worth, we suspect that [many forwarding collections already have bugs like this](https://github.com/google/guava/issues/1575), where users don't override all methods that they should. But the problem is worse for default methods, where the users couldn't override before. And in theory, Java could introduce new default methods at any time, so, even if we were writing `ForwardingCollection` today, we might have chosen not to forward any `default` methods, just to set a clear policy.

**Comment by ChristianCiach** [comment]
Thanks, that's a good explanation!
