### ISSUE TITLE
LinkedListMultiMap.get(key).iterator() inconsistent behavior on key->value removal

### ISSUE THREAD

**Issue by alsemenov** [google/guava#2796]
Here is the sample code that demonstrates the problem:
```java
	@Test
	public void testRemoveDuringIterate1() {
		ListMultimap<String, Integer> map = LinkedListMultimap.<String, Integer>create();
		map.get("one").add( 1);
		map.get("one").add( 2);
		map.get("one").add( 3);
		map.get("one").add( 4);
		map.get("one").add( 2);

		Iterator<Integer> it = map.get("one").iterator();
		assertTrue(it.hasNext());
		assertEquals(Integer.valueOf(1), it.next());
		map.remove("one", 4);
		List<Integer> remain = new ArrayList<>();
		it.forEachRemaining((e)->remain.add(e));
		assertEquals(Arrays.asList(2,3,2), remain);
	}

	@Test
	public void testRemoveDuringIterate2() {
		ListMultimap<String, Integer> map = LinkedListMultimap.<String, Integer>create();
		map.get("one").add( 1);
		map.get("one").add( 2);
		map.get("one").add( 3);
		map.get("one").add( 4);
		map.get("one").add( 5);

		Iterator<Integer> it = map.get("one").iterator();
		assertTrue(it.hasNext());
		assertEquals(Integer.valueOf(1), it.next());
		map.remove("one",2);
		List<Integer> remain = new ArrayList<>();
		it.forEachRemaining((e)->remain.add(e));
		assertEquals(Arrays.asList(3,4,5), remain);
	}
```

First test passes, but second fails on last check, `remain` is [2,3,4,5] instead of expected [3,4,5]
I would expect that iterator either ignores all changes, or respect them all.

**Comment by alsemenov** [comment]
I suggest the following fix https://github.com/alsemenov/guava/commit/5562a2392823ad346c570d18cd177d8e88897852

**Comment by cpovirk** [comment]
Thanks, but: ["If the multimap is modified while an iteration over any of those collections is in progress, except through the iterator's methods, the results of the iteration are undefined."](http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/collect/LinkedListMultimap.html). It's possible that we could guarantee the results, but the JDK generally does not, likely because it requires some extra work, could prevent future implementation changes, and ties the user to a particular choice of multimap.
