### ISSUE TITLE
Feature Request: Allow custom Equivalence instance for elements in common.graph.{Graph|ValueGraph|Network}

### ISSUE THREAD

**Issue by jbduncan** [google/guava#2814]
In my dissertation software, I have an instance of `MutableGraph<Equivalence.Wrapper<CustomDataClass>>`, where the associated `Equivalence` is `Equivalence.identity()`.

It involves some difficult-to-read boilerplate during interaction, due to need to create and unwrap the `Wrapper` instances. The alternative is to make `CustomDataClass`'s `equals` and `hashCode` be identity-based rather than value-based, and whereas I could do that, it feels dirty as `CustomDataClass` is supposed to be value-based (as if it were an `@AutoValue` class, or a `case class` or `data class` from Scala or Kotlin).

If I could specify upfront when creating the graph that the equality and hash codes of nodes are  determined by `identity()`, then that would eliminate a good amount of boilerplate in my code.

This could probably be expanded to accept any `Equivalence` rather than just `identity()`. However, it's not clear to me if it could be also be expanded to `ValueGraph`s and `Network`s; I suspect it would be useful sometimes for edge values to have a different `Equivalence` to nodes, so that would make things more complicated.

**Comment by jrtom** [comment]
Can you back up a minute and explain what it is that you're trying to accomplish, i.e., what problem you're trying to solve and how your data structures relate to it?

For starters, why do you need Equivalence in the first place?

**Comment by jbduncan** [comment]
@jrtom For my dissertation, I'm trying to model the order of "events" in a hypothetical concurrent software system:
- `CustomDataClass` is the value class - a blueprint for individual events.
- `MutableGraph` is the data structure that determines how the events are ordered.
- Each event is a node in the graph.
- A directed edge from `nodeU` to `nodeV` means that `nodeU` happens before `nodeV`.

Each event contains an "entity" (e.g. a networked computer) and a "message" (e.g. bits down the wire).
That's all fine, but when I insert an event into the `MutableGraph<CustomDataClass>`, I have a potential situation where if an event has an equal entity and message to an event that's already in the graph, then the new event doesn't get inserted. This happens for 2 reasons:
- `CustomDataClass.equals()` equates instances by the value of their entity and message, so the two events are considered "equal"
- `common.graph.Graph`s cannot contain 2 or more equal nodes

It's a problem because 2 or more events with an equal entity and message may occur during the lifetime of a concurrent software system (for the purposes of my dissertation). Since graphs reject equal nodes, I need a different solution.

My solution is to wrap each event with `Equivalence.identity()`. This causes two distinct events which coincidentally have equal entities and messages to _not_ be considered equal by the graph (because `==` is now used for equality), which allows both events to be inserted.

However, this means that the `MutableGraph` now contains `Wrapper<CustomDataClass>`s rather than plain `CustomDataClass`s. This introduces visual indirection, which makes code that I wrote to work with the graph harder for me to read, understand again, and update.

I hope this clears things up.

**Comment by jrtom** [comment]
Thanks for the explanation, that does clear things up.

What you describe is similar to the reason why @Bezier89 proposed the `ValueGraph` type in the first place; he wanted to have non-unique edge values, and using `Equivalence` objects or similar to manage this does make the code kind of ugly-looking.

Probably the API for such a thing--if we were to provide it--would involve adding an option to the *Builder classes, and probably to the `Graph`/`ValueGraph`/`Network` interfaces (so you could recover the `Equivalence` instance from the graph, to enable things like creating another graph with the same properties). 

I would need to be convinced that we should make these changes, though: 
* I suspect that there are relatively few people who would need this capability, so I'm not sure it would be worth the additional API load
* I'm pretty sure that it would mess with the implementations that we have something fierce.  :/

If you really need to use `Equivalence`, I'm afraid that your current solution, or providing a custom implementation of your own, is probably your best bet.

That said:

For the system that you're trying to model, it's not clear to me that any two nodes _should_ be equal.  In particular, the triple (computer, message, timestamp) seems like it would uniquely (and appropriately) identify an event, because a computer can't send two of the same message at exactly the same timestamp [1].  (And presumably you have to have timestamps because otherwise you wouldn't know how to induce edges.)
 
Perhaps there's a reason why your model is constructed such that there can be identical events, but I don't know what that reason would be.

Going a bit wider still: the definition of your topology seems a bit weird.  Specifically, I'm not sure why "x happened before y induces an x->y edge" makes for an interesting graph.  Can you say more about what you're doing with this graph, and how you decided on your model?

(This is probably way more detail than you were expecting to come out of this conversation, so if you'd like to take this to email, LMK and we'll figure that out.)

[1]  Well, with multiprocessor systems and parallel I/O buses, maybe, but at that point it might be worth modeling the different processors as different entities anyway.

**Comment by jbduncan** [comment]
I'd be very happy to answer your questions @jrtom, but as I've not explained the full story and the details are rather academic, I agree with you that it would be best to take this to email.

My email address is available on my profile; I can't seem to find yours, so how would you like to do this?

**Comment by cpovirk** [comment]
For what it's worth, @kevinb9n, at least, has pushed back heavily against supporting custom equivalences (specifically for `MapMaker`, but his point was more general). He's pushed heavily for the `Equivalence.Wrapper` solution (on top of which you may wish to wrap the graph yourself to provide an API that speaks the underlying types you want).

I haven't thought about this in as much detail as he has, so I'll just say "I agree" and leave it to him to copy and paste from a "Equivalence/MapMaker" thread last year or otherwise weigh in if he's so inclined :)

**Comment by jrtom** [comment]
@jbduncan email sent.  :)

**Comment by jrtom** [comment]
Based on the discussion up to this point, I think that we have pretty much arrived at not adding support for the requested feature.  Sorry for the inconvenience.  

If you (or someone else) comes up with more compelling arguments for providing this capability later, then we can reopen this issue.
