### ISSUE TITLE
Get weight for connected nodes

### ISSUE THREAD

**Issue by ankit2771991** [google/guava#2823]
I am using MutableValueGraph and has  graph structure as 
1,1 -> 0
1,2 -> 2
2,2 -> 0
2,3 -> 3
3,3 -> 0

now if i get edge value for (1,2) it returns 2 but for (1,3) it returns null
its their any way to make it return 5(i.e 2+3) or should i use any other data structure for this purpose

**Comment by jrtom** [comment]
@ankit2771991 `ValueGraph.edgeValue(u, v)` returns the value of the edge between `u` and `v` if there is one, and throws otherwise: [Javadoc](https://google.github.io/guava/releases/21.0/api/docs/com/google/common/graph/ValueGraph.html#edgeValue-java.lang.Object-java.lang.Object-)

So I'm not sure what you mean by "it returns null for (1,3)", since it should throw in that case.

What you're asking for is effectively the length of a path between 1 and 3.  We're considering releasing capabilities for shortest paths and/or distances, but they likely won't be available until Guava 23.
