### ISSUE TITLE
InternetDomainName.topPrivateDomain() improvement 

### ISSUE THREAD

**Issue by datasunny** [google/guava#2847]
InternetDomainName.topPrivateDomain() use mozilla's PSL to find top private domain. While there're two sections of data in mozilla's PSL file: 'ICANN DOMAINS' and 'PRIVATE DOMAINS'. In many cases, user of this function doesn't care about the 'PRIVATE DOMAINS' and is expecting 'amazonaws.com' as the result calling this function on 'xxx.s3.amazonaws.com'. Therefore a parameter to indicate whether 'PRIVATE DOMAINS' should be included or not will be a nice improvement.

**Comment by Harkaran** [comment]
@kluever is this issue still relevant, if it is I would like to take it on as my first contribution to guava as I am currently working on some domain validation on my own anyway.

**Comment by rbarazzutti** [comment]
`InternetDomainName` has a method named `topDomainUnderRegistrySuffix()` that does this.
(since version 23.3)

from Javadoc :_
For example, for ` x.adwords.google.co.uk` it returns `google.co.uk`, since `co.uk` is a registry suffix. Similarly, for `myblog.blogspot.com` it returns `blogspot.com`, since `com` is a registry suffix.

I think that this issue might be closed

Cheers
