### ISSUE TITLE
Make API for Monitor work better with Java 8

### ISSUE THREAD

**Issue by electrum** [google/guava#2853]
The `SafeBox` example for `Monitor` is much more verbose than expected. We can do better:

```java
public class SafeBox<V> {
  private V value;
  private final Monitor monitor = new Monitor();
  private final Monitor.Guard valuePresent = guard(monitor, () -> value != null);
  private final Monitor.Guard valueAbsent = guard(monitor, () -> value == null);

  public V get() throws InterruptedException {
    try (LockedMonitor ignored = monitor.autoEnterWhen(valuePresent)) {
      V result = value;
      value = null;
      return result;
    }
  }

  public void set(V newValue) throws InterruptedException {
    try (LockedMonitor ignored = monitor.autoEnterWhen(valueAbsent)) {
      value = newValue;
    }
  }
}
```

**Comment by ChristianCiach** [comment]
I think it's awkward to ignore a return value just to be able to use the Monitor with try-with-resource. 

I fully support the creation of Guards using a BooleanSupplier, though! I wonder why @cpovirk explicitly excluded Monitor in his search query at issue #2785.

**Comment by electrum** [comment]
@ChristianCiach agreed, though I think it's nicer than try/finally. Too bad try-with-resources doesn't let you elide the resource variable (compared to `with` in Python where the `as xxx` is optional).

**Comment by cpovirk** [comment]
> I wonder why @cpovirk explicitly excluded Monitor in his search query at issue #2785.

I think that that search was for top-level classes with a single `abstract` method, and `Monitor` happened to be one. A search for nested classes might well have turned up `Monitor.Guard` (and perhaps more).

And sorry, I thought I'd replied to this, but obviously I never did. I think I'd meant to run it by the main remaining author of `Monitor`. I'll do that tomorrow.

**Comment by cpovirk** [comment]
This seems reasonable, but since it's an API change, it would need to go through our internal API Review process. That means it needs someone internal to drive it. I'll float the idea to people looking for such a project, but I can't promise anything soon. Sorry.

**Comment by jsampson** [comment]
Original author of Monitor here (no longer at Google but still occasionally contributing). Just noticed this issue.

FYI, we did at least implement "creation of Guards using a BooleanSupplier" a little while back. It's an instance method called [newGuard](https://google.github.io/guava/releases/26.0-jre/api/docs/com/google/common/util/concurrent/Monitor.html#newGuard-java.util.function.BooleanSupplier-). @cpovirk, I wonder if it's time to change the examples in the class javadoc to use newGuard and save 8 lines of code. 😀 There are also a couple of typos in the javadoc for the method itself that could be fixed.

Beyond that, I actually did a complete redesign/rewrite a few years ago that's both easier to use (lambdas for all guards and tasks) and higher performance (built on primitives instead of wrapping a lock), but it's complicated enough that no one at Google has found the time to review it. 😉 Perhaps I should just put it up on GitHub myself to crowdsource the review.

**Comment by cpovirk** [comment]
Oh, oops, so we did :) Thanks. It would be good to do the docs at some point. I know these things tend to languish on my to-do list, though, so interesting parties might consider a pull request.

**Comment by jsampson-gw** [comment]
Okay, here you go! https://github.com/google/guava/pull/3236

**Comment by jsampson-gw** [comment]
As of Moe Sync #3261, the example in the class javadoc uses `newGuard` and therefore looks a lot closer to what was suggested in this issue.

Take a look: https://github.com/google/guava/blob/e2cf262d89c65a701de72df20c38808640e7e86c/android/guava/src/com/google/common/util/concurrent/Monitor.java#L167-L192

I propose closing this issue because I think that this is the best we can do with Monitor. I'll follow up with @cpovirk via email to discuss next steps for my more radical redesign ideas. 🙂

**Comment by cpovirk** [comment]
There's potentially still try-with-resources (like https://github.com/google/guava/issues/1608), though that's a more complex issue. But it probably does make sense to close this specific issue and track the overall try-with-resources request there. Thanks.

**Comment by jsampson-gw** [comment]
FYI, I've posted the API for my complete redesign/rewrite of Monitor as a feature request here: #3265
