### ISSUE TITLE
Maps.immutableEnumMap(TransformedEntriesMap): transformEntry called twice

### ISSUE THREAD

**Issue by perceptron8** [google/guava#2854]
I wanted to copy map returned by `Maps.transformValues` using `Maps.immutableEnumMap. Double transformation really surprised me.

`transformEntry()` was called twice per entry:
1. [Maps.java#L150](https://github.com/google/guava/blob/fce5e62628a1eb3eab4dfdb7b6f2ce7fa3567557/guava/src/com/google/common/collect/Maps.java#L150) (null-check),
2. inside [`EnumMap(Map)`](https://docs.oracle.com/javase/8/docs/api/java/util/EnumMap.html#EnumMap-java.util.Map-) constructor.

This may be not the most elegant solution, but

```
for (Map.Entry<K, ? extends V> entry : map.entrySet()) {
  checkNotNull(entry.getKey());
  checkNotNull(entry.getValue());
}
return ImmutableEnumMap.asImmutable(new EnumMap<K, V>(map));
```

could be replaced with something similar to:

```
Class<K> keyType = (Class<K>) map.keySet().iterator().next().getDeclaringClass();
EnumMap<K, V> enumMap = new EnumMap<>(keyType);
for (Map.Entry<K, ? extends V> entry : map.entrySet()) {
  K key = checkNotNull(entry.getKey());
  V value = checkNotNull(entry.getValue());
  enumMap.put(key, value);
}
return ImmutableEnumMap.asImmutable(enumMap);
```

It would be a little less efficient than using `EnumMap(map)` constructor in case of non-views (`put()` vs `putAll()`)~~, so additional `instanceof TransformedEntriesMap` check may be desirable~~.

I know that i can use `ImmutableMap.copyOf` before passing transformed map to `Maps.immutableEnumMap` or use `Maps.toImmutableMap` collector, but I decided to let you know what happened as you may have similar usages in your code base.

**Comment by cpovirk** [comment]
@lowasser , any idea why we need null checks at all, given that `EnumMap` will do them? The checks date from http://go/34322860-null-checks

**Comment by cpovirk** [comment]
My mistake: EnumMap permits null _values_.

**Comment by perceptron8** [comment]
Please ignore `instanceof TransformedEntriesMap` note I made initially. This method should behave in a fully predictable way regardless of `map`' type (non-guava views etc.), so just make sure that `getValue()` is called once). By the way, `(Class<K>)` cast is unnecessary.

**Comment by cpovirk** [comment]
> It would be a little less efficient than using `EnumMap(map)` constructor in case of non-views (`put()` vs `putAll()`)

Only in the case of copying from an `EnumMap`, it seems? (And we could use `clone()` for that case if we really want.)

Actually, maybe what we should do is just perform the null checks _after_ copying to the `EnumMap`?

**Comment by perceptron8** [comment]
> Actually, maybe what we should do is just perform the null checks after copying to the `EnumMap`?

@cpovirk That's clever, but it won't be as lazy as `ImmutableMap.copyOf(map)` which throws on first null key/value. This, again, could be surprising.

**Comment by cpovirk** [comment]
"Not lazy" in the sense that, if the transformation function returns `null`, we might transform other values before throwing? That seems probably tolerable.

(Arguably even the current behavior is "tolerable," but really what I mean is that it's sad but only about as sad as lazy views often are, which is why we've soured on them :) I guess my underlying feeling here is that I wish that we didn't have to make the code even marginally more complicated (basically, "things like calling `getDeclaringClass` :)) to micro-optimize performance for people who are using an API that's generally micro-performance-hostile... if that makes any sense. So I like the "clever" thing.)

**Comment by lowasser** [comment]
PSA: since I got assigned, I am implementing the long thing.

**Comment by perceptron8** [comment]
> "Not lazy" in the sense that, if the transformation function returns null, we might transform other values before throwing? That seems probably tolerable.

Yes, that's what I meant. If this little "over-transformation" is tolerable, I don't mind at all! :) Just, please, don't transform twice.

Good luck, @lowasser! ;)

**Comment by cpovirk** [comment]
I think we should in general reserve the right to iterate more than once if we _really_ want, but I the current code is smelly and worth fixing independent of that -- e.g., it could produce maps with null values under concurrent modification -- and I certainly view one-time iteration as a good thing overall. (Well, OK, I suppose it does mean that users may come to rely upon it, but Louis is adding a test so that we don't break them unintentionally, and I doubt we'd really have a reason to ever change the behavior back in this case.)

**Comment by perceptron8** [comment]
Thank you! :)

**Comment by cpovirk** [comment]
And thanks for the report, even though I have spent half this thread playing devil's advocate :)
