### ISSUE TITLE
Joiner withKeyValueSeparator: error when value is Array

### ISSUE THREAD

**Issue by NicolaSpreafico** [google/guava#2860]
I'm using Guava 20 because my runtime is fixed to Java7 (App Engine Standard)
```
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>20.0</version>
</dependency>
```

Here is a simple code
```
public static void main(String[] args) {
    Map<String, String[]> map = new HashMap<>();
    map.put("one", new String[] {"a", "b"});
    map.put("two", new String[] {"c", "d"});
    map.put("three", new String[] {"e", "f"});

    String join = Joiner.on("\n").withKeyValueSeparator("/").join(map);
    System.out.println(join);
}
```

And here is the output
```
one/[Ljava.lang.String;@53e25b76
two/[Ljava.lang.String;@73a8dfcc
three/[Ljava.lang.String;@ea30797
```

It seems that the `Arrays.toString()` method is not properly managed when an array need to be outputted

For the moment I managed the problem like this
```
Maps.EntryTransformer<String, String[], String> mapTransformer = new Maps.EntryTransformer<String, String[], String>() {
    @Override
    public String transformEntry(String key, String[] value) {
        return Arrays.toString(value);
    }
};

Map<String, String> map2 = Maps.transformEntries(map, mapTransformer);
String join = Joiner.on("\n").withKeyValueSeparator("/").join(map2);
System.out.println(join);
```

**Comment by lowasser** [comment]
This seems a special case of a more general question, which is -- to what extent should APIs that convert objects into strings deal specially with arrays?

Right now, essentially nothing I'm aware of does this.  No JDK collection has a `toString()` that deals specially with arrays.  I don't believe (?) the JDK even has a method for taking an arbitrary `Object` and using `o.toString()` if it's a normal Object and an appropriate `Arrays.toString` otherwise.  It seems like Java has just given up on this, in a lot of ways.

**Comment by kevinb9n** [comment]
> I don't believe (?) the JDK even has a method for taking an arbitrary `Object` and using 
> `o.toString()` if it's a normal Object and an appropriate `Arrays.toString` otherwise.

This is a tangent, but it *kind of* does, in the form of

```
String s = Arrays.deepToString(new Object[] { o });
return s.substring(1, s.length() - 1);
```

However, these "deep" methods are the exceptions that prove the rule; in every other case arrays are not given this kind of special treatment, and I agree that Joiner shouldn't either. Try to avoid using arrays as much as possible.
