### ISSUE TITLE
Add Java 8 / lambda friendly helper for CacheLoader

### ISSUE THREAD

**Issue by electrum** [google/guava#2892]
Almost every usage of `CacheLoader` only needs to implement `load()`, so being able to do that with a lambda would be helpful. Something like this:

```java
public static <K, V> CacheLoader<K, V> cacheLoader(LoaderFunction<K, V> loader)
{
    return new CacheLoader<K, V>()
    {
        @Override
        public V load(K key)
                throws Exception
        {
            return loader.load(key);
        }
    };
}

public interface LoaderFunction<K, V>
{
    V load(K key)
            throws Exception;
}

**Comment by jrtom** [comment]
Why not just a Function?

**Comment by kashike** [comment]
`Function` cannot throw.

**Comment by lowasser** [comment]
Note there already _is_ this for a bare `Function`: https://google.github.io/guava/releases/22.0/api/docs/com/google/common/cache/CacheLoader.html#from-com.google.common.base.Function-

**Comment by ben-manes** [comment]
I still don't understand why the Supplier version typed the key as Object...

**Comment by electrum** [comment]
@lowasser, thanks for the tip! I never noticed that method. It would be nice to have a version for functions that throw checked exceptions.

**Comment by kevinb9n** [comment]
@ben-manes The type returned is `CacheLoader<Object, V>` because that's what the thing it returns is. It's a loader which is capable of accepting any Object, and returns a V. We could "pretend" that it's only capable of accepting some subtype of Object, but what would be the benefit of that?

**Comment by kevinb9n** [comment]
To the main question, I feel that creating doubled versions of everything to accommodate checked exceptions is a thing of the past. It's not worth it; you just have to tunnel them.

**Comment by ben-manes** [comment]
@kevinb9n The reason is that users prefer their collections to be typed, if only for consistency in their code. The current form forces the cache to be `Cache<Object, V>`, whereas developers are used to be restricting to `Cache<K, V>`. That makes it incompatible with other builder steps, like `RemovalListener`, if the key has meaning outside of the loader. Its not a big deal, but in the few cases where it seemed appropriate the end result didn't use it.

Using utilities like jOOλ's `Unchecked` tricks like
```java
CacheBuilder.newBuilder()
    .build(CacheLoader.from(Unchecked.function(key -> {
      return value;
    })::apply);
```
 can work around exceptions. It looks worse in isolation, but the extra noise drops out with real build logic. (You can add `Unchecked.RETHROW_ALL` to propagate as the original checked exception if needed)

**Comment by electrum** [comment]
In general, I agree with tunneling exceptions, but forcing users to do that here seems broken since CacheLoader and LoadingCache already support checked exceptions.

**Comment by kevinb9n** [comment]
> The current form forces the cache to be `Cache<Object, V>`

Does it? `CacheBuilder.build` has a `? super K` for this reason.
https://google.github.io/guava/releases/22.0/api/docs/com/google/common/cache/CacheBuilder.html#build-com.google.common.cache.CacheLoader-

**Comment by ben-manes** [comment]
aha, so now I understand, thanks! :)

Somehow that escaped me and I always thought it was forcing the key type, which seemed weird given the people involved.

**Comment by kevinb9n** [comment]
I have definitely discovered a number of lambdas being provided to this method that are turning checked exceptions into unchecked. Some proportion of those may be justified, some not. On the other hand, most people just use getUnchecked() (or do the chain-and-forget conversion to a RuntimeException somewhere else) anyway, so I'm not sure how big a deal this is.

Worse, I think we'd be forced to use a different method name instead of `from`, so most users wouldn't find this version anyway. I'm going to close this.

**Comment by crazybob** [comment]
Would love something like this so I don't have to remember that incantation in the simple case:

  /** Creates an in-memory cache backed by the given function. */
  public static <K, V> LoadingCache<K, V> create(Function<K, V> function) {
    return CacheBuilder.newBuilder().build(CacheLoader.from(function::apply));
  }

**Comment by ben-manes** [comment]
Well, perhaps consider `Caffeine.newBuilder().build(key -> ...)`?
https://github.com/ben-manes/caffeine
