### ISSUE TITLE
Publish API Docs that have no Beta functionality included

### ISSUE THREAD

**Issue by mbrinkma** [google/guava#2898]
In order to minimize the risk of integrating `@Beta`-annotated functionalities (especially in libraries), it would be nice to have API Docs including only the non-`@Beta`-parts of Guava.

See also issue #2657 .

**Comment by cgdecker** [comment]
I think that making our `@Beta` checker available so that you can get compiler errors if you try to use an `@Beta` API is more important for solving this (and that is something we'd like to do soon), but this doesn't seem like a bad idea either.

The main issue I have with this is that we already have several different versions of our Javadoc (normal Guava, android, GWT...) and this would be combinatorial with that, so we'd need a no-beta version of _each_ of those as well. It would be nice if there were some way to set filters on what you see to exclude `@Beta` APIs, but as far as I know Javadoc doesn't provide anything like that.

**Comment by ronshapiro** [comment]
#2657 is the issue for the BetaChecker. I'm going to close in favor of that.

**Comment by mbrinkma** [comment]
ok!
