### ISSUE TITLE
Lombok stopped working after Guava upgrade

### ISSUE THREAD

**Issue by marcingrabda** [google/guava#2918]
Hi,

Do you have any idea why Lombok annotation processor stopped working after upgrading Guava from 16.0.1 to 23.0? I have a lot of dependencies in my project, so it might be something else, because I tried creating a sample project with only guava and lombok, and it worked just fine, but it's still Guava upgrade causing problems.

Regards,
Marcin

**Comment by jbduncan** [comment]
Hi @marcingrabda.

That's not really a lot of information to go by. We may be able to help you if you can provide us with a [MVCE](https://stackoverflow.com/help/mcve). You may actually find that in producing the MVCE, you locate what's causing Lombok to stop working for you. :)

Hope this helps.

**Comment by jbduncan** [comment]
Alternatively, since you've apparently said that you created a MVCE of your own in private (which I missed first time, sorry!), you could try building up your MVCE to gradually look more like the project you're dealing with that has the Lombok problem. I hope that it would allow you to locate the source of the problem.

Hope this helps again.

**Comment by marcingrabda** [comment]
I just tried doing it, but ended up with something that compiled/worked fine :) In case I give it one more try, I will let you know, if I found anything.

**Comment by ronshapiro** [comment]
This is quite vague - if you're able to dissect the issue and get back to us with something specific, feel free to comment.
