### ISSUE TITLE
Consider supporting interface default / static method via desugar in Android branch?

### ISSUE THREAD

**Issue by oasisfeng** [google/guava#2922]
With the progress of Java 8 adoption in Android toolchain, especially the maturity of [desugar](https://developer.android.com/studio/write/java8-support.html#supported_features), the core Java 8 language features (not APIs) are now commonly used in Android development.

Currently the Android branch is fully Java 7 compliant, effectively departed from the evolution of the mainstream of Guava library. As more and more Guava functions take advantages out of Java 8 language features, especially lambda and interface default / static method, for more convenient APIs, we Android developers are still bound by the old Java 7 coding style, just because of the libraries we are using.

Please consider adopting interface default / static method in the Android branch of Guava in a future version, like some popular Java 8/9 backport libraries (such as [Android Retro-stream](https://github.com/retrostreams/android-retrostreams)).

**Comment by cpovirk** [comment]
We do promise Java 7 compatibility at the moment (see [README](https://github.com/google/guava/blob/c2c98c55c6bec6477bf2b5a9e82f9cb08c0c962c/README.md)), so we can't use those features yet.

We have been considering trying to adopt desugar as part of our compilation process so that we can use lambdas, etc. in our implementations, but that won't be of much help to you :(

**Comment by oasisfeng** [comment]
Got that, The word "android" in the branch name is a little misleading, I thought it was made solely for Android development.

Hope some day in the future, we could ditch the 1.7 source compatibility and move on. But at present, Android is still in painful version fragmentation, desugar is our only consolation for that.
