### ISSUE TITLE
Strongly recommend merge some part of apache commons components into guava

### ISSUE THREAD

**Issue by iamybj** [google/guava#2935]
Right now, I, my company and a lot of other people use both apache commons and guava.
Each apache common and guava can not cover the other.  Commons has some useful commponents  like IOUtils, BasicThreadPool....
So, why not merge apache commons into guava? and then people can use only one lib.

**Comment by kluever** [comment]
We've carefully designed Guava throughout the years, and are unlikely to simply drop in an existing set of APIs.

If you have specific APIs or use cases in mind (besides "this entire class of utilities"), we'd love to hear them. Maybe you can tell us the top 5 most commonly used APIs that you're still relying on Apache Commons for, and we can let you know if we have anything like this internally.

**Comment by PierceHanley** [comment]
What would be the advantage of doing this?  You'd have a slightly shorter list of dependencies, but it's not like that would save any space in the deployed application, since you'd still actually end up with the classes in the JAR file.

And on the downside, it would *increase* deployment size for people who had only been using Guava. There would need to be a process for incorporating features and bugfixes from the Apache components, which would have to be coordinated with releases of the main Guava APIs. And transitive dependencies on the Apache artifacts would have class conflicts with their copies in the Guava APIs.

I feel that libraries, especially ones that provide "core" utilities, should usually err on the side of being *more* modular.¹ Apache does this with their components: IO, Lang, Collections, etc. are all managed as separate dependencies. Spring has gotten a lot better about it, too.

Guava might be getting to the borderline, doing more and more unrelated things in one dependency (`common.graph` in particular, while excellent when you need something like it, seems less universally-relevant than the other packages). It's only because they're very disciplined about the API quality that the expanding scope hasn't made the library really cumbersome or turned releases into a logistical nightmare.²

So without a compelling benefit to a straight merge, I'd suggest rethinking this per @kluever's suggestion: what exact functionality do you need from commons? Is it worthwhile to suggest it as a core addition to Guava instead of copying Apache's code verbatim?

¹ This can go too far, as in [the case](https://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/) of Node's left-pad library, but is still a good general guideline.
² Not publicly, at least.
