### ISSUE TITLE
How can I get a live view of Map<K,V> from collection<V>?

### ISSUE THREAD

**Issue by cao19920425** [google/guava#2952]
Now,I have a need that get a live view of Map<K,V> from collection<V>.
Originally,i thought Maps.uniqueIndex was what I wanted.
But,i found that the Maps.uniqueIndex return type is ImmutableMap,it don't update when the collection<V> update.

For example:
```
class TestGuavaA {
    public TestGuavaA(Long id,String code, String type, String author) {
      super();
      this.id = id;
      this.type = type;
      this.code=code;
      this.author = author;
    }
    private Long id;
    private String code;
    private String type;
    private String author;

    @Override
    public String toString() {
      return ToStringBuilder.reflectionToString(this, ToStringStyle.NO_CLASS_NAME_STYLE);
    }
  }
```
I want to get a Map<Long,TestGuavaA> idToObjects,a Map<String,TestGuavaA> codeToObjects from a collection<TestGuavaA>,and modifications to the backing collection are read through to the two returned map.
This like Maps.asMap ,but is inverse.

How can i do it?

**Comment by cao19920425** [comment]
Or how can i get a live view of Map<K,V> from Map<T,V>.
For example:I want to get a Map<Long,TestGuavaA> idToObjects from a Map<String,TestGuavaA> codeToObjects,and modifications to the backing map are read through to the two returned map.

**Comment by lowasser** [comment]
Guava does not provide a way to do this because there is no possible efficient way to do this.  Since there is no way to be informed of modifications to a collection from the outside, the only possible map implementation would be to do a full linear search of the collection on every query.  Moreover, there is no way to guarantee the Map contract from the outside, that keys are unique, short of verifying every invariant on every query to the Map.

A much better solution to your problem would be to write your own class that simultaneously managed the collection and map views of all your data -- a lightweight database, more or less -- and ensured that they stayed in sync externally.

Guava tries not to provide APIs where we think people would have misleading expectations as to their performance characteristics, and this is definitely such a case.

**Comment by cao19920425** [comment]
Thank you.I know why we can't get a live view.
But how about this idea that use decorator pattern and observer pattern to create a Map of  keep update?
What's wrong about my thinking?

**Comment by cgdecker** [comment]
I think you could do something like that; it's similar to what Louis is suggesting, but I think he's suggesting that rather than try to use the `Collection` and `Map` APIs directly for this, you create your own class that just does what you need (using `Map`s and such under the hood as needed). Something like this for example:

```java
class TestGuavaADatabase {
  void add(TestGuavaA a);
  void remove(TestGuavaA a);
  Set<TestGuavaA> getAll();
  TestGuavaA getById(long id);
  TestGuavaA getByCode(String code);
}
```

**Comment by lowasser** [comment]
Also, you can't add observers to an arbitrary Collection.  You could maybe wrap another collection in an observer and get a _new_ collection, but that doesn't make the underlying Collection safe for use, and it adds lots of weird edge cases in that your wrapped collection can have new kinds of errors if there's e.g. a key conflict in the maps.  It just gets...weird.  It's much simpler, clearer, and usually cleaner to write the class Colin and I outlined.  You can even, if you choose, have the class provide _unmodifiable_ external `Collection` and `Map` views, and it works so long as you only allow the contents to be modified via the database object.

**Comment by cao19920425** [comment]
Thank you.
