### ISSUE TITLE
Fix Javadoc links to javadoc.io

### ISSUE THREAD

**Issue by cpovirk** [google/guava#2965]
This might work: https://stackoverflow.com/a/37702441/28465

**Comment by cgdecker** [comment]
I guess the link offline option copies the other projects' Javadoc into the Javadoc generated for Guava? It would be nice to avoid that, just because I worry a little bit about about increasing the size/number of files in the gh-pages branch (and the guava repo in general). It's already going to be increasing faster than it was before because of making releases much more often. On the other hand, since it's mostly just annotations and Guava already has a lot of Javadoc (and because, well, maybe the size of the repo doesn't really matter), maybe it's not that big a deal.

**Comment by cpovirk** [comment]
linkoffline still links to an already published online source. It just requires you to have the package-info file locally rather than pulling it from online.

**Comment by cgdecker** [comment]
Ohh, nice!

**Comment by ben-manes** [comment]
I do exactly this in Gradle and it works perfectly.

**Comment by cpovirk** [comment]
Gave this a quick shot. Created local versions of package-info for jsr305 and j2objc-annotations. But I can't seem to get jsr305 to win out over the JDK for javax.annotations. And I'd previously noticed that j2objc-annotations doesn't have any `@Documented` annotations (though probably it should). So no real progress so far.

Luckily, we may switch off jsr305 (#2960), which would solve that problem, at least.

**Comment by cpovirk** [comment]
Need `<detectJavaApiLink>false</detectJavaApiLink>`. Now to see if, with that, I can get both jsr305 and JDK links to work.

**Comment by cpovirk** [comment]
Have it working.
