### ISSUE TITLE
Immutable / Unmodifiable ConcurrentMap

### ISSUE THREAD

**Issue by rdicroce** [google/guava#2974]
Guava has immutable and unmodifiable versions of Map and SortedMap (which also satisfies NavigableMap) but nothing for ConcurrentMap, as far as I can tell. Neither does the JDK itself or commons-collections. Immutable and unmodifiable ConcurrentMap implementations would be useful for satisfying bounds checking.

**Comment by jbduncan** [comment]
Hi @rdicroce. Can you explain what you mean by "bounds checking"?

I ask as I struggle to understand why an unmodifiable concurrent map would be useful, as AFAICT it's kind of the whole point for concurrent maps to be mutable; they're mutable in such a way that multiple threads can safely write to and read from a given map in overlapping time intervals.

If all you want is for the map to be read and not written to, then AFAICT wrapping it in `Collections.unmodifiableMap([...])` or copying it with `ImmutableMap.copyOf([...])` should be enough.

If I've misunderstood something, please do let me know. :)

**Comment by cpovirk** [comment]
We used to have `ImmutableMap` implement `ConcurrentMap`, but it turned out not to help anyone, so we backed it out. I, too, am interested to hear about "bounds checking."

**Comment by rdicroce** [comment]
In my case, we had a ConcurrentMap<X, ConcurrentMap<Y, Z>>. We want to get something out of the inner map, but it's possible the key doesn't exist in the outer map. So we used outerMap.getOrDefault(outerKey, ImmutableMap.of()).get(innerKey). But that fails bounds checking because ImmutableMap doesn't implement ConcurrentMap, so we had to change the type to ConcurrentMap<X, Map<Y, Z>>.

So I suppose what I'm really looking for is something like Collections.emptyMap() for ConcurrentMap. A Guava Table could also satisfy this particular case, but I don't see any implementations of it that are thread-safe.

**Comment by cpovirk** [comment]
Ah, interesting. I will run `ImmutableMap implements ConcurrentMap` by a few people to get their general impressions.

Obviously no workarounds are particularly appealing, but I feel obligated to list a few, anyway:

- write it longhand
- use `unmodifiableMap` on the input to convert it to a `ConcurrentMap<X, Map<Y, Z>>`, and then use `getIfAbsent`
- store an empty map and pinky-swear not to modify it
- write a static `getIfAbsent` method with more convenient generics

**Comment by cpovirk** [comment]
(We do provide [`Tables.synchronizedTable`](http://google.github.io/guava/releases/snapshot-jre/api/docs/com/google/common/collect/Tables.html#synchronizedTable-com.google.common.collect.Table-) for thread-safe tables, but I don't know how its performance would compare to truly concurrent collections in your use case.)

**Comment by rdicroce** [comment]
A synchronized Table would be a bad idea in our case. We're storing some timestamps so we can quickly determine if a client has the current version of a resource, so we can avoid a DB call. Which means this map gets hit on every request.

**Comment by cpovirk** [comment]
Makes sense.

Other alternative: With Java 8, you could probably just declare your field as a `Map<X, Map<Y, Z>>`, since `getOrDefault` is available on `Map` nowadays. Then you can pass an `ImmutableMap` to `getOrDefault`.

**Comment by rdicroce** [comment]
We did ultimately change the field declaration, but that removes a compile-time safety check. The inner map needs to be thread-safe, so now it is possible for someone to accidentally put a regular Map (e.g. HashMap) that's not thread safe in there.

**Comment by cpovirk** [comment]
Initial reaction has been kind of lukewarm, so we'll likely leave things as they are, sorry.

A couple points:

- Our understanding is that the JDK people view `ConcurrentMap` as sort of a wart: They would have liked to just add the concurrency-oriented methods to `Map` itself, but `default` methods didn't exist yet. Now that `default` methods exist, `ConcurrentMap` doesn't serve as much purpose
- To the extent that `ConcurrentMap` does serve a purpose, it's mostly to document atomicity and memory-consistency effects, which don't make sense for an immutable map. Admittedly, it does also document general thread-safety, but even non-`ConcurrentMap` maps like `synchronizedMap` are thread-safe (as is nearly any other `Map` as long as you don't write it).

But mostly, people just found it weird to implement `ConcurrentMap`. That was true back when `ImmutableMap` did implement `ConcurrentMap`, and that's why we backed it out.
