### ISSUE TITLE
Download of guava gives HTTP ERROR 503

### ISSUE THREAD

**Issue by leder11011** [google/guava#2998]
Hi all,

I cannot download the guava jar from here:
https://github.com/google/guava/wiki/Release21

The error page is shown: HTTP error 503

Best regards
Gerrit

**Comment by leder11011** [comment]
Now the guava-23.0.jar is corrupt...

![image](https://user-images.githubusercontent.com/3330116/33317079-6e2c93e2-d436-11e7-8a9a-5ed0fe165845.png)

**Comment by fdesu** [comment]
@leder11011 
Using **Release21** link wouldn't get you to version 23 jar file :)

Maybe shall try maven central https://mvnrepository.com/artifact/com.google.guava/guava?

**Comment by JakeWharton** [comment]
That's not maven central, that's a third party index. search.maven.org is
maven central.

**Comment by fdesu** [comment]
@JakeWharton thx for correction
anyway, both of them contain a proper jar of proper version

**Comment by ronshapiro** [comment]
I'm not sure what the original issue is but I downloaded it fine.

**Comment by jbduncan** [comment]
@ronshapiro I think the download link for the 21.0 jar was just temporarily suffering from a glitch of sorts, leading to a 504 HTTP error - I tested it myself a couple of days ago, and got a similar error to @leder11011 - but I'm sure it's fixed itself now, because I tried downloading the 21.0 jar again just now and the problem's disappeared. :)
