### ISSUE TITLE
{Int,Long}Math.saturatedNegate

### ISSUE THREAD

**Issue by PhilippWendler** [google/guava#3012]
Negating ints and longs in Java with unary minus or multiplication with -1 does not produce a negated result, if the input is `Integer.MIN_VALUE` or `Long.MIN_VALUE`, respectively. This is a similar problem like overflows due to addition or multiplication, for which Guava provides various methods that throw exception on overflow (e.g, `IntMath.checkedAdd`) or saturate (e.g., `IntMath.saturatedAdd`).

For negation, Java itself provides `Math.negateExact`, which throws an exception on overflow, but there is nothing like `saturatedNegate`. Thus I propose to add `IntMath.saturatedNegate` and `LongMath.saturatedNegate` to Guava. These methods would return the respective `MAX_VALUE` if the input is the `MIN_VALUE` of int or long.

While this is only a small utility, its value comes from the fact that having this methods would highlight the problem and motivate developers into always using these methods instead of assuming "this won't happen here". I guess that in most of the code, `saturatedNegate` could be a standard replacement for overflow-prone negations. I also intend to submit a suggestion for an error-prone bug pattern that flags such negations and suggests replacement with `Math.negateExact` or `saturatedNegate`.

**Comment by lowasser** [comment]
Do you have any particular plan for how to recognize "overflow prone negations"?

**Comment by PhilippWendler** [comment]
Any non-constant expression that is negated with a unary minus or multiplication with -1 could be considered as error-prone. For our code base, I would like a check that just forbids this, because being forced to use a method instead is acceptable if the utility method proposed here exists.

Compared to `saturatedMultiply(-1, x)` I think `saturatedNegate` is much more obvious to read and write. Especially developers who are not familiar with overflowing negations would certainly wonder why this is done, whereas for `saturatedNegate` a quick look at its Javadoc would clear it up.

**Comment by lowasser** [comment]
I guess I'm trying to figure out if I believe this method is worth its weight if you're _not_ willing to go that far, to forbid every negation out there.

**Comment by PhilippWendler** [comment]
I would say yes. If the method is present, developers might be more willing to use it instead of just using an overflowing negation.

**Comment by cpovirk** [comment]
From the negation bugs I've seen, I'd guess that the fix is rarely going to be `saturatedNegate`. I'm used to seeing cases that make me say, "If you want a random number between 0 and n, ask for it; don't create a random int and then play with `abs` and `%`" (or the same thing but with hash codes -- possibly we should have an API for that, or people should use `%` first and then `abs`). Even in the couple "math-y" cases I found from a quick search, the fix doesn't use a saturated negation:

http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/d6401129327e/src/share/classes/java/time/Instant.java#l927
http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/d6401129327e/src/share/classes/java/lang/Integer.java#l399

Maybe the cost of adding this isn't too high (since it fits naturally with existing methods in a fairly lightly used class), but it just might have zero prospective users. I know you've made the case that it's there to raise awareness, but it may raise awareness in the wrong way by suggesting that the problems that do exist are the kind that would be best addressed by `saturatedNegate`. Maybe the results of an Error Prone check would turn up more prospective users than I'd expect. But currently, I think it's hard to justify adding this.

**Comment by cpovirk** [comment]
Sorry, I'm conflating `abs` and negation above.

Anyway, I think we need some use cases here. If some surface from an Error Prone check or your manual investigation, I'd be interested. But for now, I'm closing this.
