### ISSUE TITLE
Reimplement default methods Predicate.and|or|not to get pretty toString()

### ISSUE THREAD

**Issue by tomaszalusky** [google/guava#3029]
In Guava, `Predicates.and(p1,p2).toString()` returns `"Predicates.and(<toString of p1>,<toString of p2>)"` since `toString()` is invoked on `AndPredicate` class. This is great feature for debugging or logging, for which the Guava `Predicate` still has worth for me even in Java 8.

In Java 8, `p1.and(p2).toString()` returns `"some.ClassName$$Lambda$524/7624130891@4c78d6ba"` since `toString()` is invoked on lambda. But fluent `.and()` is great feature too and totally acceptable reason why for example [this issue](https://github.com/google/guava/issues/334#issuecomment-269697414) was closed.

Since `com.google.common.base.Predicate` extends `java.util.function.Predicate`, why not to merge advantages of both and override default `com.google.common.base.Predicate.and()` method to return `AndPredicate`?

    default Predicate<T> and(Predicate<? super T> other) {
        Objects.requireNonNull(other);
        return Predicates.and(this, other);
    }

The predicate could be built either simply with `Predicates.and()` as shown (which results in degenerated tree with depth *O(n)* for *n* `and()s`) or applying some technique to keep `components` list flattened.

Thanks!

**Comment by lowasser** [comment]
I have mixed feelings about doing this, on a few levels.  Under the assumption that you're using Java 8 at all, I'm not sure you "ought" to be using Guava's functional features at all -- you should be using lambdas everywhere you can, and I'm not sure you should be using c.g.c.b.Predicate.  Under those conditions, it doesn't seem like this change would really add any extra benefit.

**Comment by cgdecker** [comment]
I agree with Louis. Our `Predicate` extends `java.util.function.Predicate` simply to help with compatibility between the two, not to improve on it. `java.util.function.Predicate` is the new and better version, not the other way around.

In my opinion, if anything this should be a feature request for the JDK to improve the `toString()` of the `Predicate` returned by `Predicate.and`... but I think they're unlikely to do this, because the prevalence of lambdas is going to make the `toString()` of functional objects not particularly readable in general, and overriding `toString()` on `and` would require making it not a lambda anymore, with (hand wave) potential performance impact.

I'm going to close this; if someone feels differently, we can reopen.

**Comment by tomaszalusky** [comment]
Thanks for response, though it's sad for me to hear such result. I tried to concentrate on area where `java.util.Predicate` is obviously not a "better version".

I will deal with it and find some workaround.
