### ISSUE TITLE
Faster lookups for non-empty ImmutableSortedSet and Map

### ISSUE THREAD

**Issue by lptr** [google/guava#3038]
`RegularImmutableSet` and `RegularImmutableMap` allow O(1) lookups via their hash table. `RegularImmutableSortedSet` and `RegularImmutableSortedMap` uses less memory, but requires O(log n) binary search to locate keys. An implementation that guarantees sortedness while retaining fast lookups at the cost of more memory would be useful.

One way to implement this would be to add methods in the `Builder` like `optimizeFor(Optimization,.LOOKUP_SPEED)` vs `optimizeFor(Optimization,.MEMORY_USAGE)`. Copy methods could also take a parameter like this, i.e.: `ImmutableSortedSet.copyOf(Collection<T>, Optimization)`.

**Comment by lowasser** [comment]
I would tend to consider this a contract violation: sorted collections should use the comparator and the comparator alone to check key equality, and should have the same behavior as the mutable sorted collections when a comparator is not consistent with equals.

If you want this behavior, you can easily enough just do `ImmutableMap.copyOf(new TreeMap<>(map))`, since `ImmutableMap` retains insertion order.
