### ISSUE TITLE
Add (last)indexOf accepting some sort of equals() override

### ISSUE THREAD

**Issue by rafalkrupinski** [google/guava#3042]
Many methods working on collections has versions accepting both Comparable and Comparator, where Comparator effectively allow users to override compareTo(T) method.

Please add the following variations of List.(last)indexOf() that would effectively allow users to override equals(Object) method.

- <code> int indexOf(List<T > list, T e, Function<T,?>keyExtractor)</code>
    return index of such element that keyExtractor.apply(element).equals(keyExtractor.apply(e))
- <code> int indexOf(List<T > list, T e, BiPredicate<T,T>equals)</code>
    return index of such element that equals.test(element, e)
- lastIndexOf versions of the above
- versions with start/stop indices.

----
[update] - use BiPredicate instead of BiFunction

**Comment by jbduncan** [comment]
If this is considered a good idea by the Guava team, I would suggest replacing all declarations of `(Bi)Function` in @rafalkrupinski's API suggestion with `com.google.common.base.Equivalence`.

**Comment by cpovirk** [comment]
We have generally taken the position that "`equals` means interchangeable," and when it doesn't, we've steered people toward using `Equivalence` and storing `Equivalence.Wrapper` instances, rather than providing static methods for each use case. I understand wanting to avoid `hash`, but I don't think we want to create a separate ecosystem of methods for that purpose.

You might also consider something like `transform(list, keyExtractor).indexOf(e)`.
