### ISSUE TITLE
Closer does not support AutoCloseable

### ISSUE THREAD

**Issue by alamothe** [google/guava#3068]
Closer currently works only with `Closeable`. This issue is to support `AutoCloseable` which is more general

Closer seems originally conceived for pre-JDK7 when try-with-resources didn't exist.

However, it is much more useful than that. There are many situations where try-with-resources cannot be used while `Closer` can e.g.:
- we want to log exceptions separately if they come from create/body/close phases
- we want to have similar functionality inside a class which holds multiple resources (in this case try-with-resources cannot be used since the caller controls the object lifetime)

**Comment by cgdecker** [comment]
`Closer` was only created as a poor replacement for try-with-resources that is slightly better than trying to do it manually, and in general I'm leery of trying to support anything beyond that with it. This isn't as simple as adding a `register(AutoCloseable)` method. For example, the `rethrow()` and `close()` methods on `Closer` all throw `IOException`, because they're dealing with `Closeable` objects (whose `close()` methods throw `IOException`), not general `AutoCloseable`s which may throw any type of exception. Changing the exception types of these methods is not really possible at this point, and leaving  the exception types as-is means both that users supplying an `AutoCloseable` have to deal with an impossible checked exception type _and_ that any checked exceptions that they do throw (from `close()`, anyway) have to be rethrown wrapped in an unchecked exception. There are potential ways we could deal with this, but they all muddy the API to support use-cases the class wasn't designed for.

**Comment by alamothe** [comment]
Thanks for the response! It makes a lot of sense. 

In that case, I would maybe suggest having a separate, newer version of `Closer` (e.g. `Closer7`) which would be post-JDK7, while keeping the existing version JDK6 compliant. 

This version would be a lot simpler (e.g. no need to check if `addSuppressed` method exists) and work with `AutoCloseable` _only_ (which is more general than `Closeable`)

I went this way and implemented it for my own project. I'll let you judge whether would be useful enough to add to Guava. In my experience, in any more complex situation where creation and closing of resources are not happening at the same place (e.g. a class that holds multiple resources), try-with-resources cannot be used, and requires a utility like a `Closer`
