### ISSUE TITLE
KD Trees and QuadTrees

### ISSUE THREAD

**Issue by MartinHlavna** [google/guava#3093]
I have noticed that there is no implementation of QuadTree or KDTree. These structures can be in fact very helpful in searching dimensional spaces. Any ideas on implementing these structures? I think this would be great addition to Guava.

**Comment by netdpb** [comment]
The fact that no one (to my knowledge) has asked for either of these structures before suggests that there isn't a big need for them in Guava, although they're certainly useful.

Do you have a specific need for a general-purpose Quadtree or K-D tree API? Other than the data structures themselves, which are not difficult to write.

If you could convince us that either API would get a lot of usage, and is significantly better than the existing alternatives, then we would consider adding it to Guava. But until we have evidence that they will actually be used to solve people's problems, we tend to err on the side of not adding new APIs even if they're otherwise good ideas.

Closing for now. Thanks for the suggestion!

**Comment by MartinHlavna** [comment]
My personal use case is as this: 

I have data organised in 2D "grid." I need to perform nearest neighbor classification on these data. However, I have probable "location" in some much smaller space. This means that I only need to classify small portion of the data. This could be accomplished using range search on mentioned data structures. 

When I was searching for good implementation in the library I have noticed some Stack Overflow questions asking for these structures. I was not thinking about how many people really need these structures but I was thinking that because I will probably end up writing then on my own I could contribute then to somewhere. 

You have a good point that not many people need these structures in fact.
