### ISSUE TITLE
Javadoc for Multimaps.unmodifiableMultimap is misleading

### ISSUE THREAD

**Issue by stkelley** [google/guava#3140]
The Javadoc for [Multimaps.unmodifiableMultimap](https://github.com/google/guava/blob/7abf5990b29f19a7e8c458b63af73c88523e1820/android/guava/src/com/google/common/collect/Multimaps.java#L517-L518) (as well as the other `Multimaps.unmodifiable*Multimap implementations`) include this note:
```
   * <p>Note that the generated multimap's {@link Multimap#removeAll} and {@link
   * Multimap#replaceValues} methods return collections that are modifiable.
```
In all of these implementations the `removeAll` and `replaceValues` methods simply throw an `UnsupportedOperationException`, not returning anything much less a modifiable collection.

**Comment by cpovirk** [comment]
(I got curious... :))

Sounds like there's nothing subtle here, just a broken comment.

Internally, this comment was introduced in CL 7155959. That included the comment: "I realized that the removeAll and replaceValues methods could simply throw an UnsupportedOperationException." But that discussion seems to have been about changing the `ListMultimap`, etc. subclasses to `throw new UnsupportedOperationException()` rather than `return (List<V>) super.replaceValues(...)`. As far as I can tell, even before that CL, the methods did throw UOE.

Perhaps the comment was just copied from the synchronized implementations (and even slightly modified) without fully thinking it through.
