### ISSUE TITLE
Provide download links to the Guava JAR files

### ISSUE THREAD

**Issue by mojojojo94** [google/guava#3151]

**Comment by jbduncan** [comment]
Hi @mojojojo94. Good question! Unless you're using Maven or Gradle to manage dependencies like Guava for you, it's not that easy to find a compiled JAR file for the latest Guava version (25.0 at time of writing).

Try looking into http://central.maven.org/maven2/com/google/guava/guava/25.0-jre/. You should find guava-25.0-jre.jar there and be able to download it, which I believe is what you're after.

(Alternatively, if you're developing for Android, try looking into http://central.maven.org/maven2/com/google/guava/guava/25.0-android/ and searching for guava-25.0-android.jar instead.)

I hope this helps!

**Comment by jbduncan** [comment]
@cpovirk @cgdecker  I wonder if we should start providing again links to downloadable jars for each release in https://github.com/google/guava/releases, as what used to happen up until version 21.0.

WDYT?

**Comment by jbduncan** [comment]
@mojojojo94 I should note a caveat with downloading just the Guava jar by itself.

Downloading just the Guava jar means that you won't have access to Guava's own dependencies either, of which there are a few.

On the plus side, these dependencies aren't mandatory (by my understanding), as they just contain various annotations.

But if you intend to use Guava with tools like [error-prone](http://errorprone.info/), or if you intend to use the Java command-line options `-Werror` and `-Xlint:all`, then you'll likely have problems as described in https://github.com/google/guava/issues/2721.

**Comment by netdpb** [comment]
@jbduncan Not a bad idea.

**Comment by jrtom** [comment]
I'm pretty sure that there used to be download links from the main README file; I know because that's where I got the idea to do the same for JUNG (which still has them: https://github.com/jrtom/jung).

It could be that we removed those because it made it more of a pain to update when we started doing more frequent releases, I don't know.

**Comment by cgdecker** [comment]
I partly stopped doing this because A) I wasn't sure anyone did manual dependency management anymore, and B) you could get the jars from central.maven.org. But I guess we also aren't including the links to central.maven.org for the releases in the release notes now either.

I don't think it's worth including direct links in the main README; to me it seems preferable to just provide a link to the release page for the latest release from the README and provide any links specific to that release from there. I'm actually thinking about maybe getting rid of the release-specific stuff in our README (anything the references the version number) and just providing a link to the latest release via https://github.com/google/guava/releases/latest and/or a Github badge that uses that link. We might still want to include the general XML for including the dependency there, but with ${version} instead of an actual version number.

**Comment by cgdecker** [comment]
I've added links to jar file downloads to the release page for the latest release (30.1.1) and updated our script that generates the base release page format to include those links for future releases.
