### ISSUE TITLE
Exception caught while taking screenshot in Appium

### ISSUE THREAD

**Issue by mali5590** [google/guava#3160]
Issue: Exception caught while taking screenshot in Appium

Exception : Unexpected result for screenshot command: com.google.common.collect.Maps$TransformedEntriesMap instance

Maven Dependency: 
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>25.1-jre</version>
</dependency>

have tried with 24.1 - jre as well No luck :(

**Comment by jbduncan** [comment]
Hi @mali5590, that's an interesting bug report.

I'm personally unfamiliar with Appium, and I don't know if anyone on the Guava team is familiar with Appium themselves, so could you provide an [MCVE](https://stackoverflow.com/help/mcve) so that the Guava team can reproduce this when they get around to looking at this issue?

**Comment by jrtom** [comment]
I'm not familiar with Appium, but this sounds like a bug in Appium that happens to be triggered in a place where they're using the Guava library.  I'd try filing a bug there: https://github.com/appium/appium/issues
