### ISSUE TITLE
CaseFormat improvement: Translate accented characters

### ISSUE THREAD

**Issue by clessiomendes** [google/guava#3201]
Docs say explicitly that non ASCII characters are not guaranteed to be upper/lowercased when using CaseFormat. Think it should not be difficult to include special characters from the [Latin](http://www.madore.org/~david/computers/unicode/cstab.html#Latin-1) character set to expand the library coverage beyong English speaking users.
Currently, `CaseFormat.to(CaseFormat.UPPER_CAMEL, "MANÉ")` gives us ManÉ as result.

**Comment by ronshapiro** [comment]
Internationalization is a complicated problem space, and other libraries (like ICU4J) are better suited for handling these types of requests. I suspect that we probably won't want to take this on because it becomes very hard to cover all of the bases beyond ASCII, but I'll let @cgdecker and @cpovirk chime in too.

**Comment by cpovirk** [comment]
Yeah, `CaseFormat` is targeted mostly at names of identifiers in source code, and those usually contain only ASCII characters. We should probably document this better, but I don't envision branching out to internationalization use cases.
