### ISSUE TITLE
cache.Weigher.weigh() should return a long instead of an int

### ISSUE THREAD

**Issue by nartz** [google/guava#3202]
Currently, the `Weigher.weigh()` returns an `int`. However, setting the maximum cache weight (`.maximumWeight(long weight)`) uses a long. 
```java
public interface Weigher<K, V> {

  /**
   * Returns the weight of a cache entry. There is no unit for entry weights; rather they are simply
   * relative to each other.
   *
   * @return the weight of the entry; must be non-negative
   */
  int weigh(K key, V value);
}

```

**Proposal:**
Weigher#weigh to return a long, instead of an int. A use case would be when caching large files that have a large size in bytes (i.e. a 3gb file) - i understand this is not the main use case of this library.

**Positives:**
- Ability to have item weights that are greater than `Integer.MAX_VALUE`, possibly leading to less silent bugs when weight values are high (and might wraparound to negative)
- Type Parity with the types between `maximumWeight` and `Weigher.weigh()`

**Negatives:**
- Slight performance hit using an int
- Possible to workaround this by rounding or dividing, but thats more difficult

Other options would be more complicated, where this method is initialized using a type of numeric with a default of integer.

**Comment by ronshapiro** [comment]
Hm. This seems like an oversight from the beginning unless I'm missing something. There's even this explicit cast to an `int`: https://github.com/google/guava/blob/c9add81c4a0139747b23e8bf7054abbfb30b72e9/guava/src/com/google/common/cache/LocalCache.java#L267

I'm not sure there's a good way to change this without making a binary incompatible change, besides adding a `default` method in the Java 8 version.

**Comment by cgdecker** [comment]
I'm not sure that it's an oversight. I think the reason the maximum weight is a `long` is so that you can potentially hold a lot of things that have weights that are a significant fraction of the max single-entry weight (i.e. `Integer.MAX_VALUE`).

And that cast to `int` isn't really relevant because it only happens when a custom `Weigher` _isn't_ used, i.e. when each entry has a weight of 1.

**Comment by ben-manes** [comment]
Yes, everything @cgdecker said is correct. For real world usages, accounting down to the byte for large values (>4GB) doesn't offer much value and would increase the per-entry overhead. The largest user at the time was Cassandra, which divided when using CLHM's `Weigher` (predecessor library but similar interface). For advanced usages like theirs with millions of entries the concern is GC overhead for large heaps. By keeping the interface name and examples generic, rather than explicitly stating the unit, the choice was left to users rather than us hard coding assumptions.

**Comment by nartz** [comment]
I'm fine leaving this as is, as i understand keeping things simple and tight is usually a good thing; however, it might be nice to allow some sort of overriding that would let me use longs (or maybe this is already supported but im just not seeing it?)? I see the point about the cast performance hit as well with a generic type. 

 I can always divide by a thousand i guess of course, just makes things slightly more complicated on my side.

**Comment by cgdecker** [comment]
I'm going to go ahead and close this, because I think it's unlikely we'll want to do anything about this.
