### ISSUE TITLE
ClassPath returns empty ClassInfo when run under OpenJDK 10

### ISSUE THREAD

**Issue by JLLeitschuh** [google/guava#3249]
The following test success under JDK 8 but fails under OpenJDK 10.

Is there a different classloader that I need to use for JDK 10 that will allow me to walk the classpath?

```kotlin
class ExamplesTest {
    companion object {
        private val currentPackage = ExamplesTest::class.java.`package`.name
    }

    
    fun `examples test`() {
        val allTopLevelClasses =
            ClassPath
                .from(Thread.currentThread().contextClassLoader)
                .getTopLevelClasses(currentPackage)
        assertThat("Should not be empty", allTopLevelClasses, !isEmpty)
    }
}
```
```
java --version

openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment 18.3 (build 10.0.2+13)
OpenJDK 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

**Comment by cpovirk** [comment]
[The docs](https://google.github.io/guava/releases/snapshot-jre/api/docs/com/google/common/reflect/ClassPath.html) recommend `ClassLoader getSystemClassLoader​()`. Does that work?

**Comment by JLLeitschuh** [comment]
Same exact problem exists with `ClassLoader.getSystemClassLoader​()`.

**Comment by JLLeitschuh** [comment]
I think the reason behind this problem is that `ClassLoader.getSystemClassLoader​()` no longer returns a `UrlClassloader` under JDK 10.

**Comment by cpovirk** [comment]
What version of Guava are you using? Our tests of `ClassPath` against `ClassLoader.getSystemClassLoader()` passed under Java 10, but that's only because of changes we made in [23.1](https://github.com/google/guava/releases/tag/v23.1).

**Comment by JLLeitschuh** [comment]
This is my own mistake. Sorry. Updating to version `26.0-jre` fixed the problem. Thanks!

**Comment by cpovirk** [comment]
Thanks. That said, I've been debugging, and I'm seeing weird stuff.

- It looks like the object returned by the call to `ClassLoader.getSystemClassLoader()` from the Kotlin class is different than the one returned by the call to `ClassLoader.getSystemClassLoader()` from Guava's `ClassPath`??

- The one returned from the Kotlin call goes from being a `URLClassLoader` to not being one when I go from Java 8 to Java 10, as you note. But the list of URLs I get from the Java 8 loader contains only some URLs from the JDK, not anything from Kotlin, so the test fails for me under Java 8, too. (It also fails if I use `Thread.currentThread().contextClassLoader`.) And even if I edit `ClassPath` to force it to use `java.class.path` (the Java 10 / non-`URLClassLoader` behavior), that doesn't help because `java.class.path` contains only the Kotlin runtime. Or maybe I've gotten some of that mixed up along the way; it wouldn't surprise me.

Maybe the difference between what I'm seeing and what you're seeing has to do with how we're running the test. But I could easily imagine that problems here remain. Please let us know if you run into anything else.

**Comment by JLLeitschuh** [comment]
@cpiotr Thanks for digging into this, if I see additional weirdness I'll open a new issue.
