### ISSUE TITLE
Remove @Beta from the Striped

### ISSUE THREAD

**Issue by jsunsoftware** [google/guava#3253]
Similar to [issues/3251](https://github.com/google/guava/issues/3251)

**Comment by EarthCitizen** [comment]
This is incredibly frustrating. `Striped` is EXACTLY what I need, but I am making a library, and `Striped` is still `@Beta`, so I cannot use it. And, sadly, I am not aware of any alternative to Guava's implementation of this.

According to the JavaDoc of `Striped`, it has been around since Guava 13.0, which appears to have been released in 2012. As of this comment, that is approximately 10 years. How can the design not be finalized after 10 years? I don't get this.

Guava's infinitely long betas really deter me from using the library. Anything marked as `@Beta` is basically useless to me, and I imagine to many others. I appreciate the quality work that has been done, but 10 years just seems, from the outside at least, insane.

**Comment by kluever** [comment]
Apologies for the inexcusably long delay here. This is now fixed.
