### ISSUE TITLE
Remove @Beta from HashFunction/Hashing/HashCode

### ISSUE THREAD

**Issue by robeden** [google/guava#3284]
These classes have been around for a long time (since 11.0), so I would like to request they be de-beta'ed. They're great containers/abstractions so we would like to use them without fear of imminent breakage.

**Comment by flamespt** [comment]
I signed it!

**Comment by fictionic** [comment]
@flamespt Looks like it's still marked beta. Any ideas about what's going on?

**Comment by JeffGreen** [comment]
In fact in the com.google.common.hash package, the following classes are also marked as @Beta but have been around @since 11:

Funnels.java
HashFunction.java
HashCode.java
Hasher.java
Funnel.java
Hashing.java

Perhaps @Beta should be removed from all of them?

**Comment by consultantleon** [comment]
seems pretty hard to get the @Beta removed? just upgraded to 29-jre and Hashing is still @Beta ?!

**Comment by AParise1217** [comment]
Has there been any updates regarding this? It seems like a trivial code change to make.

**Comment by netdpb** [comment]
We're in the process of reviewing all our `@Beta` APIs with the intention of removing `@Beta` from all that have no serious outstanding API issues.

**Comment by GabrieRabelo** [comment]
Is there an alternative to use without with this @Beta notation?

**Comment by Xaerxess** [comment]
It seems that you recently [removed @Beta from multiple classes](https://github.com/google/guava/commit/6242bdd27bfa7a2223548a082c25a8ef97a951db) and [also from `HashFunction`](https://github.com/google/guava/commit/e1cc195cfb7ad4a3f24aaee6b8b63e441594a9b3) (came from an internal change?) but not from other classes from [com.google.common.hash](https://github.com/google/guava/tree/master/guava/src/com/google/common/hash) package, especially [`BloomFilter`](https://github.com/google/guava/blob/master/android/guava/src/com/google/common/hash/BloomFilter.java) and [`Funnel`](https://github.com/google/guava/blob/master/guava/src/com/google/common/hash/Funnel.java), which are part of Guava since version 11. 

Could you share your plans regarding "de-betizing" these two classes? How "risky" they are for users? (out of curiosity: how widely `BloomFilter` is used internally?) Or maybe you're planning to extract an interface from `BloomFilter` as mentioned in #2226? ;)

**Comment by bigPandaChina** [comment]
Why not delete @Beta from Hashing ?  The other have been deleted. Is there any problem with hashing?

**Comment by kluever** [comment]
Point of clarification: `@Beta` does not (and never has) meant that the API is "problematic".

> Beta APIs represent Guava features that we aren't ready to freeze for whatever reason: because the methods might not find enough users, because they might be moved, because their uses might be too narrow to include them in Guava.
> 
> That said, @Beta APIs are fully tested and supported, and treated with all the care and affection that the rest of Guava receives.
> 
> The biggest connotation of the @Beta annotation is that annotated classes or methods are subject to change. They can be modified in any way, or even removed, at any time. If your code is a library itself (i.e. it is used on the CLASSPATH of users outside your own control), you should not use beta APIs, unless you repackage them (e.g. using ProGuard).

Is the `@Beta` tag on `Hashing` causing you problems? If so, please elaborate.

**Comment by consultantleon** [comment]
Yes we receive a warning from some of our scanner tools and or Intellij.
It's an unsettling thought that you provided an API/event framework, that we've been depending on for many years (!!) now and our build still warns us of depending on beta features!
I can understand that such annotation is on a new feature at it's introduction, but years and 10th of releases later you expect beta releases to mature to stable longterm features.

**Comment by kluever** [comment]
Fixed via https://github.com/google/guava/pull/5862

**Comment by Xaerxess** [comment]
@kluever Did you discussed removing `@Beta` from `BloomFilter` and `Funnel(s)`? Should I create a separate issue?

**Comment by kluever** [comment]
We did not look at those. A separate issue would be great, thanks.

**Comment by Xaerxess** [comment]
@kluever I've created #5863.
