### ISSUE TITLE
need some information regarding rate limiter comments

### ISSUE THREAD

**Issue by vikrantch-hk** [google/guava#3308]
I was going through comments in RateLimiter, but was not able to understand inference of below comment, can someone please elaborate more

```This is in contrast to {@link java.util.concurrent.Semaphore} which restricts the
 number of concurrent accesses instead of the rate (note though that concurrency and rate are
 closely related
```

**Comment by netdpb** [comment]
The point is that `RateLimiter` controls the overall rate of access, while in contrast `Semaphore` controls how many accesses can happen concurrently (that is, simultaneously).

If you have more questions about this, please consider asking (or searching) on StackOverflow.com. I'll close this issue because this is our feature-request and bug tracking system, and it's not designed to answer general questions.
