### ISSUE TITLE
Striped.lazyWeakLock() returning different locks for same key.

### ISSUE THREAD

**Issue by jpsilvagallino** [google/guava#3323]
Hi all,

I believe this issue may be related to [this other closed issue](https://github.com/google/guava/issues/2477). From the thread I expected it to be resolved in version 23.3 and above, but I am still getting the same behavior in version 25.1-android (I have a dependency on Java 1.7).

If I run my code with the following lock:
`private final Striped<Lock> myLock = Striped.lazyWeakLock(100);`
`myLock .get(key).tryLock()...`

I obtain the following result:
`2018-11-22 16:41:14.630  INFO 7676 --- [pool-2-thread-1] myService                   : Obtaining lock with following value: false and lock hash = 1331131916 and key hash = 126843480`
`2018-11-22 16:41:14.782  INFO 7676 --- [ool-2-thread-99] myService                   : Obtaining lock with following value: false and lock hash = 535391089 and key hash = 126843480`
`2018-11-22 16:41:14.805  INFO 7676 --- [pool-2-thread-4] myService                   : Obtaining lock with following value: false and lock hash = 1935007842 and key hash = 126843480`

If I change my lock type to:
`private final Striped<Lock> myLock = Striped.lock(100);`

all works as expected.

Is my expectation wrong, and it has been resolved that this should be the expected behavior of lazyWeakLocks?

Thanks and regards,
JP

**Comment by jpsilvagallino** [comment]
Hi, anyone was able to look at this?

Thanks.

**Comment by ben-manes** [comment]
A weak lock means that it is wrapped by a `WeakReference` and can be garbage collected if not strongly reachable. This means you should hold a reference to the lock during usage, e.g.

```java
var lock = locks.get(key);
lock.lock();
try {
  // do work
} finally {
  lock.unlock();
}
```

If you do not hold the `lock` reference, then a GC can collect it and a new instance is created. That would break your exclusivity. If you follow the above, you may get different instances over time as the key=>lock mapping is garbage collected. However, it will not violate the exclusive nature of the lock since it the mapping will remain if it is strongly reachable, e.g. the lock is being used.

**Comment by nglorioso** [comment]
I believe that @ben-manes's comment accurately describes what's happening.
