### ISSUE TITLE
LocalCache is locked when computing element weight

### ISSUE THREAD

**Issue by kasper0406** [google/guava#3371]
When using the `CacheBuilder` and specifying a weigher, the current solution assumes that the weigher code is fast as the entire cache is locked when the weigher code is evaluated https://github.com/google/guava/blob/master/guava/src/com/google/common/cache/LocalCache.java#L2009. For weigher functions that are not fast, this leads to the entire cache being locked for the entire duration. It seems to me that it should be fine to computer the weight without the cache structure being locked, and only lock it once the weight has been computed.

**Comment by ben-manes** [comment]
You may increase the `concurrencyLevel` (default is `4`) to improve the situation. This only locks other writes to that segment, allowing reads to continue. The penalty is that policies are per segment, e.g. LRU, so a high number of segments is wasteful and diminishes the policy effectiveness. This situation is improved in `Caffeine` due to decoupling the policy from the hash table, allowing it to use more fine grained locking.
