### ISSUE TITLE
HashBiMap#remove

### ISSUE THREAD

**Issue by TeemoJUN** [google/guava#3401]
```
public V remove(@Nullable Object key) {
    BiEntry<K, V> entry = seekByKey(key, smearedHash(key));
    if (entry == null) {
      return null;
    } else {
      delete(entry);
      entry.prevInKeyInsertionOrder = null;
      entry.nextInKeyInsertionOrder = null;
      return entry.value;
    }
  }
```
why `nextInKToVBucket` `nextInVToKBucket`   not set to null

**Comment by cgdecker** [comment]
I think the only reason the insertion order fields are set to null is that when the entry is removed it no longer has any insertion order relationship to anything else, but I'm not really sure why even that is needed. @lowasser might know more.

That said, I'm closing this because I don't think there's any bug here (if you think there is, feel free to reopen and specify how you think this is a bug) and this isn't really the right forum for just asking questions about how something was implemented.

**Comment by Maaartinus** [comment]
I guess, it's just helping the GC. The entry may outlive the collection and keeping any needless references would be wrong.
