### ISSUE TITLE
Transitive dependency conflict with `ben-manes.caffeine`

### ISSUE THREAD

**Issue by kebeda** [google/guava#3405]
Please get checker-qual and error_prone_annotations to agree with caffeine...update your check-qual dependency to 2.6.0 and your error_prone_annotations dependency to 2.3.3, please.

    Require upper bound dependencies error for org.checkerframework:checker-qua>
        +-com.google.guava:guava:27.1-jre (managed) <-- com.google.guava:guava:>
          +-org.checkerframework:checker-qual:2.5.2
    and
        +-com.github.ben-manes.caffeine:caffeine:2.7.0
          +-org.checkerframework:checker-qual:2.6.0

    Require upper bound dependencies error for com.google.errorprone:error_pron>
        +-com.google.guava:guava:27.1-jre (managed) <-- com.google.guava:guava:>
          +-com.google.errorprone:error_prone_annotations:2.2.0
    and
        +-com.github.ben-manes.caffeine:caffeine:2.7.0
          +-com.google.errorprone:error_prone_annotations:2.3.3

**Comment by cgdecker** [comment]
Neither of these should be required at compile time, so there shouldn't be any problem caused by the different versions I don't think. Furthermore, it's only a minor version difference so in theory at least there shouldn't be any problem caused by just using the newer of the two versions. I don't think it makes sense for us to attempt to keep lock-step in dependency version numbers with other libraries we don't own.

That said, there's probably not any reason we can't update those dependencies to a newer version for the next release.

**Comment by efenderbosch** [comment]
Maybe this dependency just needs to have the scope changed? I've used ``provided`` for this in other projects. There's no maven scope for "required at compile but not at runtime." I guess ``provided`` is as close as we can get? ``test`` scope might be too late for certain tools.

Regardless, I've used exclusions to get around this issue, but it would be nice to not need them.

```xml
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>27.1-jre</version>
                <exclusions>
                    <exclusion>
                        <groupId>com.google.code.findbugs</groupId>
                        <artifactId>jsr305</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.google.errorprone</groupId>
                        <artifactId>error_prone_annotations</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>            
```

**Comment by cgdecker** [comment]
IIRC we used to have those dependencies as `provided` but that caused problems for certain environments for some reason, and we ended up having to change it to how it is now because there was no way to reconcile what those environments wanted with Maven, and this was the closest thing to a middle ground.

But I can't find the specific issue where that was all discussed at the moment, which is why I'm being so vague. =)

**Comment by ben-manes** [comment]
Some languages like Scala cannot handle missing annotations, as they may use them as compile directives (e.g. inlining). Others turn on all javac lints which may warn, though that can be disabled using `-classfile` and I think that prompted the change (#2721). When migrating off of jsr305, Caffeine followed Guava's lead and I agree the two shouldn't to lock-step for these.

**Comment by efenderbosch** [comment]
Here's when it was changed. I thought this all sounded familiar. I was active in this thread, as well.

https://github.com/google/guava/issues/2824
