### ISSUE TITLE
Dispatcher.immediate should be made available or removed

### ISSUE THREAD

**Issue by msangel** [google/guava#3406]
There is no public way to create an `EventBus` instance with `Dispatcher.immediate`. Both `EventBus` constructor that use Dispatcher as argument, same as actually whole `Dispatcher` are package-private, which make its impossible use any of them. `Dispatcher.immediate` is a dead code actually. But in my case I need it.

**Comment by ThomasKoreman** [comment]
Maybe it is useful for developers / contributors to know why you need it.

**Comment by msangel** [comment]
For my command line _single threaded_ utility. In general single threaded applications need it.

**Comment by cgdecker** [comment]
Yeah, `Dispatcher.immediate` is part of something I started on a long time ago but never finished. I think the main thing that was needed was a Builder for `EventBus` because using constructors when there are multiple options that can be specified is not great. I'm not sure when I'll have time to get back to that though.

**Comment by msangel** [comment]
Well. I can always implement needed dispatcher if it will be possible to use it,  Just found few similar bugs with the same problems and even merge request with suitable fix: https://github.com/google/guava/pull/3002
