### ISSUE TITLE
Would you promote EqualsTester as not @Beta?

### ISSUE THREAD

**Issue by suztomo** [google/guava#3452]
Would you promote EqualsTester as not @Beta?

I think the class has been there for a while and I believe it has been useful for many users. Do you think it's good time to remove `@Beta` from EqualsTester?

**Comment by kevinb9n** [comment]
imho the debate here is whether the entirety of guava-testlib is just permanent beta by nature. It may not really call for a finalization process.

That is, @Beta exists due to the problem of released *libraries* using (especially exposing) Guava types, where a library here is approximately "something that ends up on someone else's classpath". Does anyone really do this with guava-testlib? I admit I haven't dug into that, just classified it as "gotta be far smaller scale than guava".

For everything else, the price of minor API changes really isn't much. It's an actual finite process with a beginning and an end! With a bit of decent tooling, those points even being usually on the same calendar day! Also, you have some measure of control over when and IF you want to take that time hit. This is fantasy don't-even-dream-of-it territory for libraries.
