### ISSUE TITLE
[FeatureRequest] Add method Lists.partitionEven

### ISSUE THREAD

**Issue by jiming** [google/guava#3479]
Dear guys,

Lists.partition is very useful. But sometime I need partition list evenly.

For example, I have a list `['a','b','c','d','e','f','g','h','i','j','k']`

Using `List.partition(list, 3)`, the result is 
```json
[
['a','b','c']
,['d','e', 'f']
, ['g','h','i']
, ['j', 'k']
]
```

I expect using `List.partitionEven(list, 3)`, the result should be 
```json
[
['a','b','c','d']
,['e','f','g','h']
,['i','j','k']
]
```

The use case for it is that when I have 3 thread to process the list, by using `partitionEven(list, 3)`, the 3 thread can process data even.

Thanks a lot!

**Comment by netdpb** [comment]
`Lists.partition(list, 3)` is not trying to create a list of three lists. It's trying to create a list of lists, each of which has three elements.

You can get what you want with something like `Lists.partition(list, list.size() / 3)`.

However, for the use case you describe (a three-thread pool), I'd recommend using a `ThreadPoolExecutor` via `Executors.newFixedThreadPool(3)` (and actually a `ListeningExecutorService` decorator on top of that via `MoreExecutors.listeningDecorator()`) with those three threads instead of partitioning your list in advance.
