### ISSUE TITLE
PerThreadQueuedDispatcher: missing the last event dispatch 

### ISSUE THREAD

**Issue by mzyfree** [google/guava#3530]
PerThreadQueuedDispatcher offers the event into queue when it is dispatching other event.
if there isn't any event being posted after that,then the last event in the queue will not be dispatching any more.
Version: 28-jre

>  
    void dispatch(Object event, Iterator<Subscriber> subscribers) {
      checkNotNull(event);
      checkNotNull(subscribers);
      Queue<Event> queueForThread = queue.get();
      queueForThread.offer(new Event(event, subscribers));

      if (!dispatching.get()) {
        dispatching.set(true);
        try {
          Event nextEvent;
          while ((nextEvent = queueForThread.poll()) != null) {
            while (nextEvent.subscribers.hasNext()) {
              nextEvent.subscribers.next().dispatchEvent(nextEvent.event);
            }
          }
        } finally {
          dispatching.remove();
          queue.remove();
        }
      }
    }

**Comment by nglorioso** [comment]
This whole block happens in a thread-local context: i.e.: if multiple threads are dispatching to this dispatcher, they will read different values for `queueForThread` and `dispatching`.

The circumstance where an event (B) would be added into the queue while dispatching another event (A) is if the implementation of one of the subscribers causes the event (B) to be posted. However, since the same thread that causes (B) to be posted is still processing event (A), it will see (B) in the queue afterward and will pick it up.

If, instead (B) is posted on another thread concurrently while processing (A), it will be on its own ThreadLocal queue, and (B) will be immediately processed by the thread posting B.

See: 
https://github.com/google/guava/blob/0cd4e9faa1360da4a343f84cb275d6eda0c5e732/guava-tests/test/com/google/common/eventbus/DispatcherTest.java#L64-L76 

Of course, if you have some example application or code where using this Dispatcher causes events to not be processed, we'd love to see it and fix it!

Thanks!
