### ISSUE TITLE
Bad performance of ArrayListMultiMap in debug mode

### ISSUE THREAD

**Issue by shineech** [google/guava#3541]
Envs:
pc local debug: 
    i5/8GB/ssd, jdk8/jdk11, intelj idea 2019/vscode1.36
server remote debug: 
    Xeon(R) Gold 6144 3.5GHz/768GB/ssd , jdk8/jdk11, intelj idea2019.2/vs code 1.36

I've tried several times in two different ways above -- local/remote debug and got the same result:
After putting huge data in ArrayListMultiMap, whatever you do, it is too slow. And the more data you put into ArrayListMultiMap, the worse performance you get.  (just in debug mode, you set the breakpoints after putting data into ArrayListMultiMap, then try to step over the code, it's horrible...) But if you try to do the same things with HashMap, everything goes well.

See the attachment, set the breakpoints according the comments in line 54 and 87.
![demo](https://user-images.githubusercontent.com/21279118/62019986-b39b9d00-b1f3-11e9-9e78-ae9dfafb5fd3.gif)

[TestCode.zip](https://github.com/google/guava/files/3439975/TestCode.zip)

**Comment by nglorioso** [comment]
Hi there! I want to thank you for the video, this really helps me understand what you are seeing.

This looks like an optimization that IntelliJ does for displaying data in a `HashMap` or the `ArrayList`, which isn't done for `ArrayListMultimap` (you'll note the "Collecting data..." while looking at the local of type `ArrayListMultimap`). 

It sounds like https://www.jetbrains.com/help/idea/customize-data-views.html may help here (e.g.: you get the improved for `HashMap` performance with 'enable alternate views for Collections classes' and you get the poor performance for this large collection with "Enable toString() object view... for all classes that override toString()").

I don't know what it would take to get integrated IntelliJ support for these collections, but that appears to be the root cause of what you're seeing.

**Comment by shineech** [comment]
thanks, it's done
