### ISSUE TITLE
listenablefuture and failureaccess are incompatible with Java's package module system

### ISSUE THREAD

**Issue by shs96c** [google/guava#3564]
When included in the `module-path` the `listenablefuture` and `failureaccess` jars introduce classes that are also in the `guava` jar, causing a "split package", which causes all manner of chaos.

Although not including these jars on the module path might be possible, it's hard to determine in an automated way whether or not to include any random jar on the module path or not.

Since these jars should also have a module name, the better solution would be to move the classes within these jars to unique packages, thus avoiding the problem of a split package in the first place.

**Comment by cpovirk** [comment]
The `failureaccess` overlap is [a bug fixed in 27.0.1](https://github.com/google/guava/releases/tag/v27.0.1) -- sorry about that.

With the `listenablefuture` overlap, users may have to manually exclude `listenablefuture`. We've set things up so that this is safe.

We may still make changes here. To keep that discussion in one place, we have #3320 for that.
