### ISSUE TITLE
Testlib 28.1-jre has no machine-readable licence

### ISSUE THREAD

**Issue by Pr0methean** [google/guava#3585]
FOSSA was unable to detect any licence for testlib 28.1-jre after upgrading from 28.0-jre. Some metadata is probably missing from the Maven package. A workaround in FOSSA is to manually resolve the warning, but this wasn't necessary before.

![Screenshot_2019-08-29_11-07-43](https://user-images.githubusercontent.com/4961925/63965072-4460d500-ca4d-11e9-8b6b-e991ef6e4f17.png)

**Comment by cgdecker** [comment]
I'm not seeing any difference between 28.0 and 28.1 that would have caused any issue like this. License information for `guava-testlib` comes from `guava-parent`, where it is set to "Apache License, Version 2.0" (as it has been since 28.0 when we corrected it from "The Apache Software License, Version 2.0"; see a0ed6c57).

**Comment by Pr0methean** [comment]
This may be a bug in FOSSA, so I've e-mailed their support team.

**Comment by Pr0methean** [comment]
FOSSA admits this is an issue on their end; any known issues with other license scanners yet?

**Comment by cgdecker** [comment]
I haven't heard of any other issues.
