### ISSUE TITLE
cache loader.reload() new value can not be null

### ISSUE THREAD

**Issue by yws-tracy** [google/guava#3616]
ListenableFuture<V> newValue = loader.reload(key, previousValue);
        if (newValue == null) {
          return Futures.immediateFuture(null);
        }
public ListenableFuture<V> reload(K key, V oldValue) throws Exception {
    checkNotNull(key);
    checkNotNull(oldValue);
    return Futures.immediateFuture(load(key));
  }
#class: LocalCache  line: 3632      newValue can possible be null?   I do not think so, is it a bug?

**Comment by netdpb** [comment]
I am not sure why that is there. It may be because `CacheLoader` is implemented by others, and they may return `null` even though they aren't supposed to—and otherwise the resulting NPE would be swallowed.

I don't think there's a real problem if the code unnecessarily handles unexpected `null`s there, though.

I'll close this bug for now; feel free to reopen if you think there's a significant problem here.
