### ISSUE TITLE
[Graph]After modify the node object, will throw Node xxx is not an element of this graph when use ‘graph.successors‘ interface

### ISSUE THREAD

**Issue by qijianan777** [google/guava#3744]
I use ValueGraphBuilder to build a MutableValueGraph graph, and put some node and edge in it. When i modify the attribute of node, and use successors to find successors, but it throw Node  is not an element of this graph.
The code like this 
```java
MutableValueGraph<FlowNode, FlowEdge>graph = ValueGraphBuilder.directed().build();
graph.putEdgeValue(node1, node2, edge);
flowGraph.successors(node1); // can find the successors of node1
node1.setName("xxxx");
flowGraph.successors(node1); // throw node1 is not an element of this graph
```

**Comment by jbduncan** [comment]
@qijianan777 I think your problem is you're trying to mutate a node inside your graph, rather than removing it and replacing it with a new one.

Guava graphs work similarly to Java maps in that they both require nodes/keys to never be _mutated_. In other words, you should never change the value of any of your node's internal fields that would cause `FlowNode::hashCode` to change, as `node1.setName("xxxX")` would do.

This is because, for Guava graphs, when you run `graph.successors(node1)`, the first thing the graph does is to look for `node1` in its internal hash table. However, since `node1.setName("xxxx")` causes its name to change and thus its `hashCode` changes as well, the graph can't find `node1` in its internal hash table anymore. So the graph thinks it doesn't contain `node1`, and it throws an exception.

If you can't make the `FlowNode` class immutable, try following the advice in the Guava user guide about ["Elements and mutable state"](https://github.com/google/guava/wiki/GraphsExplained#elements-and-mutable-state).

I hope this helps. :)

**Comment by kluever** [comment]
In general, please use StackOverflow to ask "how-to" and "why-didn't-it-work" questions
https://stackoverflow.com/questions/ask?tags=guava+java
