### ISSUE TITLE
Add additional immutable collection types, like ImmutableDeque

### ISSUE THREAD

**Issue by rgoldberg** [google/guava#3760]
Please add additional immutable collection types, like `ImmutableDeque`.

**Comment by szarnekow** [comment]
What would be the advantage of an ImmutableDeque over an ImmutableList, given that it is immutable so operations like add/pop etc won’t exist?

**Comment by netdpb** [comment]
That's a good question.

@rgoldberg, what is your specific use case?

**Comment by rgoldberg** [comment]
I want an immutable empty Deque that I can reuse instead of creating new empty Deques, or having to ensure that a saved Deque is never modified. I use ArrayDeques for non-empty Deques.

An immutable empty Deque could just be returned from a method without exposing an ImmutableDeque class, but it wouldn’t hurt if it extended ImmutableCollection / was annotated @Immutable / was named ImmutableDeque for static analysis & code comprehension.

I don’t see any direct need for non-empty ImmutableDeques, but maybe someone else would have a use case where they called non-mutating Deque methods (like descendingIterator()). I doubt there are many (or even any) such cases; my main focus was just for a demarcated immutable empty Deque, but I didn’t want to limit the request, or to over-complicate it.

**Comment by netdpb** [comment]
If this is only for avoiding creating a new empty deque for performance reasons, I don't think that's enough of a reason for a whole immutable type, since you wouldn't declare a method to return that type.

Are you returning empty deques frequently enough that it is a real performance issue?

**Comment by rgoldberg** [comment]
I haven’t run performance tests. I just try not to create new objects unless actually necessary.

**Comment by netdpb** [comment]
Since a deque is only more useful than a list when you're mutating it, I don't think we should add an `ImmutableDeque` type. However, if you just want an immutable empty deque, you could create a simple class that extends `AbstractQueue` and implements `Deque` to throw or return `null` where appropriate.

In the meantime, I'm going to close this for now. Please reopen if you have other use cases that suggest more of a need for an `ImmutableDeque` or other immutable types.
