### ISSUE TITLE
Question, Case Format converter

### ISSUE THREAD

**Issue by adzimzf** [google/guava#3955]
I use this method 
```java
CaseFormat.UPPER_CAMEL.to(CaseFormat.LOWER_UNDERSCORE, fieldName)
```
if the fieldName value is `MyID` the result will be `my_i_d` and if the value is GRPCCall the result will be `g_r_p_c_call`.
is that expected behavior?
because as far as I know, the snake case for `MyID` is` my_id`

**Comment by ogregoire** [comment]
Yes, that's expected behavior.

What would the snake case for `MyIDABC` be? `my_id_a_b_c`? How should this (very basic) method know your specific use case?

If you really want this kind of behavior, you have to prepare your string accordingly, by yourself:

    private static final Map<String,String> specialCasedWords = Stream.of("ID", "GRPC")
      .collect(Collectors.toMap(s -> s, s -> s.charAt(0) + s.substring(1).toLowerCase()));
    static String myCustomCaseConverter(String fieldName) {
      for (var e: specialCasedWords.entrySet()) {
        fieldName = fieldName.replace(e.getKey(), e.getValue());
      }
      return UPPER_CAMEL.to(LOWER_UNDERSCORE, fieldName);
    }

Yes, that's the expected behavior. If the snake case for `MyID` isn't what you want, maybe you should normalize your inputs, by applying the following, for instance: `str = str.replaceAll("ID(?>$|\\p{Upper}", "Id")`

**Comment by adzimzf** [comment]
Thanks for the answer.
the list `ID` and `GRPC` is not predictable, users are able to input the word as they want.
but I've already found the solution with this simple regex
```java
    private static String toSnakeCase(String s){
        return s.replaceAll("(?<g1>.)(?<g2>[A-Z][a-z]+)", "${g1}_${g2}").
                replaceAll("(?<g1>[a-z0-9])(?<g2>[A-Z])","${g1}_${g2}").
                toLowerCase();
    }
```
Thanks in advance buddy
since this issue has already solved I'll close it

**Comment by gabrywu** [comment]
same question
