### ISSUE TITLE
Are there design docs for different components in guava?

### ISSUE THREAD

**Issue by bangarharshit** [google/guava#4006]
Things like:

1. why we choose this design over alternatives?
2. Also, what are the alternatives?
3. How are backward compatibilities maintained?
4. How are apis going to be evolved to handle more cases?

I know some of these docs will be google internal but it can be an amazing learning resource to design APIs

**Comment by cpovirk** [comment]
It would be a lot of fun to release some of our design notes, but we haven't been able to justify spending the time on it :( 

The closest things I can think of are:
- [Relationship between "Guava" and "Guava for Android" in Maven](https://docs.google.com/document/d/1NYGbfz56C0Oh4IGymXjeQUVK4FcRiqDbpc4vGLnDMrY/edit), which is about artifact identifiers rather than APIs
- a couple design docs in one of our other projects, [Truth](https://truth.dev/): [`SubjectBuilder` design doc](https://truth.dev/subject_builder_design), [`Subject`: Remove `named()`, `actual()`, and type parameters](https://truth.dev/subject_named_actual_type_parameters)

Maybe other people on the team remember other things that we've released.

Backward compatibility guarantees are covered in https://github.com/google/guava/wiki/Compatibility#backward-compatibility, which links to https://github.com/google/guava/blob/master/README.md#important-warnings. Note that the policy described there is only a few years old, replacing our older policy: https://groups.google.com/d/topic/guava-discuss/rX-QXo-67ZU/discussion

**Comment by bangarharshit** [comment]
thanks. some of these (especially the truth design doc) is really useful. i can close this task but please release design doc for few more components whenever you folks get time.
