### ISSUE TITLE
Build Android flavor with `-source 8 -target 8` (but still avoid Java 7+ APIs)

### ISSUE THREAD

**Issue by cpovirk** [google/guava#5269]
Currently, our "Android" flavor of Guava supports 2 use cases:
- Android users (API level 15 (Ice Cream Sandwich) and up)
- Java 7 users

We are definitely _not_ going to start using Java 8 _APIs_. Thus, we are _not_ going to increase our minimum Android version to 24, nor are we going to require our users to enable [library desugaring](https://developer.android.com/studio/write/java8-support-table). In short: We'll continue to support older versions of Android with no changes on users' part.

However, we _are_ investigating whether to stop supporting _non_-Android users who use Java 7. This would let us simplify some implementations (mainly by using lambdas), but more importantly, it would let us make some API improvements -- like `default` methods on interfaces and type annotations (such as for nullness).

This is part of a larger effort by many Google projects to consider dropping support for Java 7. Please let us know if you anticipate problems from this change -- mainly, if you are using Guava in your library or app and you support Java 7. Thanks.

(Please also spread the word. I will additionally [announce this on our mailing list](https://groups.google.com/g/guava-announce/c/EIMDZF4dIdY). Later, we may also try to introduce some warnings when Guava is run under Java 7.)

**Comment by ganeshbhargav** [comment]
Migrating from Java 7 to Java 8 is recommended because of New language features, security improvements, Optimum performance, Writing code more efficiently, Oracle recommendation to uninstall pre-8 versions to avoid security risks, Older releases no longer publicly supported, Third party Java libraries no longer being developed and supported.

To check the new features in JDK 8 by library - check https://www.oracle.com/java/technologies/javase/8-whats-new.html

To check incompatibilities between JDK 7 and JDK 8 - https://www.oracle.com/java/technologies/javase/8-compatibility-guide.html#A999387

To check incompatibilities between Java SE 7 and SE 8 - https://www.oracle.com/java/technologies/javase/8-compatibility-guide.html#A999198

To check Features removed in JDK 8 - https://www.oracle.com/java/technologies/javase/8-compatibility-guide.html#A999476

To check Features removed in Java SE 8 - https://www.oracle.com/java/technologies/javase/8-compatibility-guide.html#CHDGHIIH

I do not anticipate any change in Applications using Guava as long as the API's remain the same and return the same result as they used to when they were in Java 7.
The compiled app with guava libraries must be able to run on Java 8 platform. 

Hope this helps resolve the issue.

**Comment by ijuma** [comment]
Out or curiosity, what's the downside of requiring library desugaring?

**Comment by cpovirk** [comment]
For most users, it's probably a reasonable thing to enable. However, there are downsides in some cases. As I understand them, the downsides are:

- It increases app size somewhat. (That's in comparison to doing nothing. Of course, if people have to write their own alternatives to the Java 8 APIs, they may offset that gain.)
- It requires multidex. Many people already have to use that (or will have to in the future), but it can add to startup time in at least some cases. Plus, [there are some limitations on when you can use classes from the other dex under older versions of Android](https://github.com/google/bundletool/issues/182#issuecomment-700295830).

**Comment by hiranya911** [comment]
We started seeing this in Firebase Java SDK builds:

```
WARNING: Java 7 compatibility warning: See https://github.com/google/guava/issues/5269
java.lang.Exception: Guava will drop support for Java 7 in 2021. Please let us know if this will cause you problems: https://github.com/google/guava/issues/5269
```

We would certainly like to drop Java 7 support, but not before the larger Google Cloud client libraries ecosystem decides to do so. AFAICT cloud libraries like Firestore and Storage are still Java 7 compatible. Has a decision been made to migrate all these libraries to Java 8?

**Comment by cpovirk** [comment]
Hi, thanks for reporting that. We have been in contact with the Google Cloud people, and we won't be dropping support unless they are. Part of the reason for this warning was to share any information we could find with them.
