### ISSUE TITLE
Not Working `Lists.newArrayList()` for Path of Nio

### ISSUE THREAD

**Issue by spearkkk** [google/guava#5309]
Hello, this is spearkkk.
To initialize and add element for List, I user newArrayList() method.
Like this:
```
Path path = Paths.get("guava", "best");
List<Path> paths = Lists.newArrayList(path);
```
However I expected that there is `path` in a `paths` list, there is two paths.
Because Path class implements Iterable<Path>,  `path` is divied as logic in Path class.
Eventually, `Paths` has Path("guava") and Path("best").

I think that the method is not working for Path class.
Could you check this issue?
Let me know if i mistake.
Thank youl.

**Comment by netdpb** [comment]
`Path` unfortunately implements `Iterable<Path>`, which means `Lists.newArrayList(path)` is ambiguous. It looks like it calls `newArrayList(Iterable<E>)` instead of `newArrayList(E...)`, both of which are declared on `Lists`.

I'd suggest you just add the element yourself:

```java
List<Path> paths = new ArrayList<>();
paths.add(path);
```

If you really want to do that in one line, you could do:

```java
List<Path> paths = new ArrayList<>(Collections.singleton(path));
```

With a static import, you could shorten that to:

```java
List<Path> paths = new ArrayList<>(singleton(path));
```
