### ISSUE TITLE
Java optional is not serializable, migration would be easy if Optional can contain `isEmpty()` and similar methods.

### ISSUE THREAD

**Issue by nitinsurana** [google/guava#5320]
Google optional is serializable.
Although, refactoring from java.util.Optional to googleOptional requires quite some code changes.

This can be prevented if we can make googleOptional interface similar to Optional.
1. Add isEmpty()
2. Add `Optional.empty()` alongside `Optional.absent()`

Thanks

**Comment by netdpb** [comment]
Thanks for the comment. Guava's `Optional` actually predates `java.util.Optional` by a few years. We have no plans to change `Optional` to be more similar to `java.util.Optional`.

We recommend using `java.util.Optional` in modern code (post Java 8; see [the Javadoc](https://guava.dev/Optional)).

**Comment by netdpb** [comment]
OK, I got caught up in your description of changing `Optional` and didn't notice the title, which was about the fact that `java.util.Optional` isn't serializable.

I'm still going to keep this issue closed, because we can't change `java.util.Optional`, and we're not planning to change `Optional`'s methods to be more similar.

What is your use case for storing an optional value in a field of a serializable object.
