### ISSUE TITLE
Expose Absent and Present as Subtypes of Optional

### ISSUE THREAD

**Issue by vgonsalv** [google/guava#5329]
Consider an interface  `Foo` as follows:

    interface Foo {
        Optional<Bar> doFoo();
    }

Suppose we now have an implementation  which wants to provide a stricter contract of always returning a value. Currently it would have to always wrap the value in an Optional. Even if we document that the Optional always had a value, most linters would complain about the lack of an isPresent() check .

Instead, if Present were exposed as a subtype of Optional, we could define it as follows:

    interface MyFoo extends Foo{
        Present<Bar> doFoo();
    }

This would formally indicate that MyFoo would always return a value, and linting could advise that isPresent() check are unnecessary.

Similarly if we want to indicate that no value is ever returned, we could use the Absent type as well.

**Comment by cpovirk** [comment]
Interesting! I'm surprised that (as far as I can recall) we haven't heard this suggested before.

That said...

We do not want to our `Optional` to compete with the JDK's: We recommend that people use the JDK class if they can. And even if they can't use it today (typically because they target older versions of Android or Java), we don't want to add features that would complicate a future migration to the JDK class.

You could try proposing this to the JDK itself. However, my understanding is that they want to make `Optional` into an [inline type](https://cr.openjdk.java.net/~briangoetz/valhalla/sov/01-background.html), and I _think_ that may interfere with letting it have a subclass like `Present`.

The even longer-term hope is that Java will get Kotlin-style support for nullness in the type system. Then methods like `Foo.doFoo()` can return `Bar?`, and methods like `MyFoo.doFoo()` can return `Bar`.
