### ISSUE TITLE
Cache.asMap() interface makes it possible to map NULL values into the cache

### ISSUE THREAD

**Issue by pontusp** [google/guava#5342]
Through the `asMap()` interface it is possible in certain situations to partially map NULL values into the `Cache` which results in an unpredictable state. When using `ConcurrentMap.compute` and `ConcurrentMap.computeIfPresent` it possible to remap a previous value to null rather than removing it, which I think would be the expected behaviour here. 

Attached [CacheNullValueTest.java.zip](https://github.com/google/guava/files/5636058/CacheNullValueTest.java.zip) contains test cases that reproduces this problem, tested on 30.0-jre

**Comment by ben-manes** [comment]
The test case is confusing because passes due to asserting the invalid behavior. I suspect that the Guava team would prefer to have a failing test to iterate against.

The compute methods are not a good fit with Guava's design, so the implementation has quirks and performance issues. I don't think those methods are commonly used, so they are likely not fully robust.

Can you try Caffeine? I believe my migration of your test passes, but flipping assertions leads me a little unsure. The builder is almost identical but since async is enabled by default, you'd need to specify `Caffeine.executor(Runnable::run)` to mirror Guava.

**Comment by ben-manes** [comment]
I took a quick look and proposed a fix in #5348. I haven't been a contributor in many years and my familiarity with the cache internals is hazy, but I don't think anyone still active on the Guava team is any better off than I am. That PR seems to address the problem, but alas I can't be certain there are not edge cases that I missed.
