### ISSUE TITLE
Add checkstyle as dependency

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [google/guava#5362]
Hi,  
I was reading the contributions rules, and i came across this:

_Files should be formatted according to [Google's Java style guide](https://google.github.io/styleguide/javaguide.html)._

I looked at the main `pom.xml`, but I can't find any kind of static code analysis, for example to be sore that that rule is complied.

So my question is, are there any specific reason why you are not using [something like this](https://checkstyle.sourceforge.io/google_style.html) to check that constraint?

**Comment by cpovirk** [comment]
Thanks. My guess is that we won't want to set this up, but the reasons are a bit weird:

First: All our changes are submitted to an internal repository first and then synced out to GitHub automatically. The internal repository already has a formatting presubmit in place.

Additionally, there's a complication that comes up when our syncing process makes automated changes to some of our code. For example, we have internal code like the following...

```java
/* MOE:insert private */
void foo() {}
```

...which gets rewritten to...

```java
private
void foo() {}
```

That would make more sense on one line, but if we're going to _require_ it that way, we'll have to clean up some existing code (not that that's too hard), and the process will introduce more diffs between the versions (which makes it slightly harder to import pull requests -- also not a big deal, but the benefit of joining the line in that case is also small). \[edit: It would also require a formatting step during the sync to GitHub, and GitHub sync+CI is already the long pole for most of our submissions.\]

Next, there's your point about existing violations on #5363: Either Checkstyle or its "Google style" config is frequently incorrect. Some of this looks like simple bugs in the config. For example, we don't follow the rule that "Single-line Javadoc comment should be multi-line." Others (related to indentation level) suggest a deeper bug. That problem, at least, could be solved by using Spotless and [its support for google-java-format](https://github.com/diffplug/spotless/blob/main/lib/src/main/java/com/diffplug/spotless/java/GoogleJavaFormatStep.java).

We could probably get something set up adequately, but I'm still not sure it would be a net win: For Git in particular, it's easy for commit hooks to interfere with work when people are testing changes locally, and of course the same goes for test-time checks. That goes for when they succeed (since that takes time) as well as when they fail. And then I'd expect to have to maintain it over time.

Again, these are all fairly small concerns, but given that we get most of what we need from the internal checks, additional external checks would likely have more costs than benefits.

\[edit: One other concern is that we occasionally see fuzzing reports against Checkstyle. They're generally just about stack overflows for deeply nested code, which is not a true "security concern" in the way that we'd be using the tool but which still may trigger vulnerability scanners.\]
