### ISSUE TITLE
UnsignedLong to double conversion does not always round correctly

### ISSUE THREAD

**Issue by harpocrates** [google/guava#5375]
The `UnsignedLong.doubleValue` method claims to convert `long` to `double` with correct rounding. Assuming "correct rounding" means produces the `double` whose real value is the closest to the real value of the `long`, here is a counter example:

```java
double guavaDouble = UnsignedLong.fromLongBits(0xfffffffffffff402L).doubleValue();
System.out.println("Original:      " + java.lang.Long.toUnsignedString(0xfffffffffffff402L));
System.out.println("Guava double:  " + new java.math.BigDecimal(guavaDouble));
System.out.println("Closer double: " + new java.math.BigDecimal(18446744073709549568d));
```

This outputs

```
Original:      18446744073709548546
Guava double:  18446744073709547520
Closer double: 18446744073709549568
```

The double that Guava produces is 26 away from the original value, but there was a closer double only 22 away from the original value. (There are no closer values - `18446744073709547520` and `18446744073709549568` are successive doubles: `Math.nextAfter(18446744073709547520d, java.lang.Double.MAX_VALUE) == 18446744073709549568d`)

----

Assuming this isn't desired behaviour, `UnsignedLong.doubleValue` could be fixed by using the following implementation ([based on the reference WebAssembly interpreter's implementation of the `f64.convert_i64_u` instruction](https://github.com/WebAssembly/spec/blob/5475b7015684a07ba69762f8438e3bcff2647686/interpreter/exec/f64_convert.ml#L27-L32)). Here, the rounding is to the nearest double, with ties going to even.

```java
@Override
public double doubleValue() {
  if (value >= 0) {
    @SuppressWarnings("cast")
    return (double) value;
  } else {
    @SuppressWarnings("cast")
    return (double) ((value >>> 1) | (value & 1L)) * 2.0;
  }
}
```

**Comment by Internet-Person-IP** [comment]
We're 5 people doing a course where we're supposed to fix issues, we would like to try and fix this issue or possibly something else that might be beginner-friendly and easy to test.
[Yannis](https://github.com/K2017), [Axel](https://github.com/elmaxe), [Andreas](https://github.com/andreaskth), [Telo](https://github.com/teljoh)

**Comment by eamonnmcmanus** [comment]
Here's my understanding of the situation. The test number looks like this in binary:
```
111...111_0100_0000_0010
^---------^
```
The indicated span is 53 bits, which is as much as a `double` can represent. The current algorithm first drops the leading 1 bit and converts to `double`:
```
011...111_01
 ^---------^
```
Then it adds 2<sup>63</sup>, which produces this:
```
111...111_0
^---------^
```
The true sum of the numbers represented by these two `double` values is halfway between this `111...111_0` and the adjacent `111...111_1`. The result is rounded to even, so the lower value is chosen.

The proposed change instead divides the value by 2 and adds 1 if the remainder (the shifted-out bit) was 1. Then it multiplies the converted `double` value by 2, which is an exact operation since it is just adding 1 to the exponent. So it converts this to a `double`:
```
011...111_10100_0000_0010
 ^---------^
```
The little `..._0010` at the end is enough to make this conversion round up and the result is
```
11...111_1
^--------^
```
That is indeed the closest `double` value since it is 1022 away from the original integer, while the other value is 1026 away in the other direction. (The numbers in the original report somehow omitted a thousand from these values. :-))

An alternative which I believe would also be correct would be to convert the top and bottom 32 bits separately to `double` and combine them in the obvious way. That should work since both values are exactly representable as `double` and we can expect `double` addition to round in the right way.

**Comment by eamonnmcmanus** [comment]
Thanks @harpocrates for finding this subtle problem and including not only a test case but a fix!
