### ISSUE TITLE
CVE-2020-8908 on failureaccess artifact

### ISSUE THREAD

**Issue by ManavIBM** [google/guava#5389]
Hi,

We are using latest guava version 30.1-jre. 
The above CVE suppose to be fixed in that version but owasp still showing vulnerability
on failureaccess artifact.

[ERROR] failureaccess-1.0.1.jar: CVE-2020-8908

Can someone help on this.

Thanks.

**Comment by kishaningithub** [comment]
Duplicate of https://github.com/google/guava/issues/5389

**Comment by cpovirk** [comment]
The ongoing security discussion is indeed tracked by #4011. That said, no tool should ever have been reporting a problem with `failureaccess`, only with `guava` itself. This sounds like a bug in the tool that you're using or the data it relies on.

**Comment by ManavIBM** [comment]
Sure Thanks.

**Comment by MaximeVaschalde** [comment]
Hi,
The vulnerability is showing because in failureaccess [1.0.1], it is indicated in the pom.xml that his PARENT project is guava 26.0-android :

  <parent>
    <groupId>com.google.guava</groupId>
    <artifactId>guava-parent</artifactId>
    <version>26.0-android</version>
  </parent>
  
But in guava 26.0-android, the method 'createTempDir' was NOT deprecated.
Problem tracked by https://github.com/google/guava/issues/4011 was solved with version 30.0-android (Oct, 2020)
The newer versions of guava are still using failureaccess [1.0.1].

Given this new information, is it still a false positive? 
Does the fact that failureaccess [1.0.1] is referencing a vulnerable version of his parent POM, necessarily means that this librairy is vulnerable?

**Comment by cpovirk** [comment]
guava-parent doesn't [contain](https://repo1.maven.org/maven2/com/google/guava/guava-parent/31.1-jre/) any code, so the CVE shouldn't apply to it.

I don't know a ton about the various tools that consume CVEs, but it might be that each of them needs to individually decide which Maven artifacts are affected. It looks like GitHub, for example, [rightly considers only the `guava` artifact to be affected](https://github.com/advisories/GHSA-5mg8-w23w-74h3). Other tools might wrongly consider `guava-parent` to be affected.
