### ISSUE TITLE
Maven Builds require JDK11

### ISSUE THREAD

**Issue by MSSedusch** [google/guava#5391]
Hi,

I am using Guava in an application that is build and runs on JDK 8. I cannot use a newer one.
I am currently using Guava 28.1 which is build with JDK8.
However, for security reasons, I have to update to Guava > 30.0 but these builds seem to be build with JDK11.

Can anyone point me to a Maven repository that contains Guava > 30.0 libs build with JDK 8?

Thanks

**Comment by jbduncan** [comment]
@MSSedusch I'm also a user of Guava (I'm not in the Guava team), but my understanding is that even though the latest versions of Guava are _built_ using Java 11, they can still be _used_ in Java 8 projects without any problems. (I imagine the Guava folks are using javac's `--release` flag or something, which makes this possible.)

Why do you ask? Is it because you can't use the latest pre-built Guava jar on Maven Central for security or build reasons?

**Comment by kluever** [comment]
Please use [StackOverflow](https://stackoverflow.com/questions/ask?tags=guava+java) to ask "how-to" and "why-didn't-it-work" questions.
