### ISSUE TITLE
How to gracefully determine if Collection 、Map or Set is null or empty .

### ISSUE THREAD

**Issue by zhangmingshuang** [google/guava#5413]
When using a String, it can use `Strings.isNullOrEmpty(str)` to determine that `str` is null or empty.

alike, I want use like `Collections.isNullOrEmpty` to determine that the collection is null or empty in gracefully way.

Maybe I have been careless, I can't find a similar implementation in the framework.  Please reply.

Thank you in advance!

**Comment by jbduncan** [comment]
@zhangmingshuang I actually remember reading about this in Guava's ["Idea Graveyard"](https://github.com/google/guava/wiki/IdeaGraveyard#iterablesisnullorempty). The Guava devs suggest to "return empty collections instead of null" so that you can just use `Collection#isEmpty`, or alternatively to follow one of the suggestions in [this StackOverflow answer](https://stackoverflow.com/questions/6910002/google-guava-isnullorempty-for-collections/6921270#6921270):

```java
Set<Foo> foos = NaughtyClass.getFoos();
if (foos == null) {
  foos = ImmutableSet.of();
}
```

or 

```java
Set<Foo> foos = MoreObjects.firstNonNull(
    NaughtyClass.getFoos(), ImmutableSet.<Foo>of());
```

I hope this helps!

**Comment by zhangmingshuang** [comment]
> @zhangmingshuang I actually remember reading about this in Guava's ["Idea Graveyard"](https://github.com/google/guava/wiki/IdeaGraveyard#iterablesisnullorempty). The Guava devs suggest to "return empty collections instead of null" so that you can just use `Collection#isEmpty`, or alternatively to follow one of the suggestions in [this StackOverflow answer](https://stackoverflow.com/questions/6910002/google-guava-isnullorempty-for-collections/6921270#6921270):
> 
> ```java
> Set<Foo> foos = NaughtyClass.getFoos();
> if (foos == null) {
>   foos = ImmutableSet.of();
> }
> ```
> 
> or
> 
> ```java
> Set<Foo> foos = MoreObjects.firstNonNull(
>     NaughtyClass.getFoos(), ImmutableSet.<Foo>of());
> ```
> 
> I hope this helps!

Got it! Thans a lot.
