### ISSUE TITLE
` com.google.common.collect.Range#hasLowerBound` not support deepclone

### ISSUE THREAD

**Issue by YuKongEr** [google/guava#5580]
```java
        Range range = Range.all();
        System.out.println(range.hasLowerBound()); // expect: true, actual: true
        Range newRange = Cloner.deepClone(range);
        System.out.println(range.hasLowerBound()); // expect: true, actual: false
```

because  ` com.google.common.collect.Range#hasLowerBound` implement by `equals` not `instance of`

**Comment by YuKongEr** [comment]
should implement:
```java
     return !this.lowerBound instance of  Cut.BelowAll;
```

**Comment by amalloy** [comment]
Guava does not make any particular effort to support third-party libraries that use reflection to mess with its internals. Since Range is immutable, so if you must use Cloner to clone it, you can always work around the issue by customizing a Cloner instance to treat Range as an immutable class, as it does for e.g. `String`.
