### ISSUE TITLE
Add Streams.stream(Enumeration) method

### ISSUE THREAD

**Issue by Dichotomia** [google/guava#5625]
We have Iterators.forEnumeration(Enumeration) and Streams.stream(Iterator).

Simplify and add Streams.stream(Enumeration) method

**Comment by kevinb9n** [comment]
I believe it's welll-understood that you can get the functionality you want by using the two methods we have together. That's API composability and we see it as success.

When I made `Iterators.forEnumeration`, it was to be the "last word" on `Enumeration` -- so that we would never have to do anything else with that legacy type again. That was over a decade ago, and it's served that purpose well!
