### ISSUE TITLE
One version of `Parameter` lacks the `getAnnotatedType()` method

### ISSUE THREAD

**Issue by mernst** [google/guava#5630]
The variant of class `com.google.common.reflect.Parameter` that is defined in file `android/guava/src/com/google/common/reflect/Parameter.java` lacks the `getAnnotatedType()` method that appears in 
file `guava/src/com/google/common/reflect/Parameter.java`.  I think this method should appear in the Android version too, since (according to my reading of https://developer.android.com/studio/write/java8-support) Android does support type annotations.

**Comment by netdpb** [comment]
The note I see there about type annotations says: "Type annotation information is only available at compile time, and not at runtime." That suggests that the reflection API doesn't have access to type annotations. Does that sound correct?

**Comment by mernst** [comment]
Oh, is `Parameter` only used at run time, never at compile time?  It's not documented either way.  (It is in a package named `reflect...`, which is a strong hint, but I've seen such inconsistencies in some projects and didn't want to assume.)

Thanks for the correction to my (lack of) assumption; I appreciate your help!

When `@Nullable` is a type annotation, how will tests like `nullPointerTester` and `testNullPointers` and `testNullPointerExceptions` work?  I was actually trying to make those tests pass when `@Nullable` is a type annotation.

**Comment by cpovirk** [comment]
There are probably half a dozen unfortunate things that are intersecting here.

Among them:

- [The "Android" branch also supports JDK 1.7.](https://github.com/google/guava#guava-google-core-libraries-for-java) This means that it's limited to Java 7 APIs, so we can't use `getAnnotatedParameterTypes` (from [`Executable`, `@since 1.8`](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/reflect/Executable.html)). [We are looking to drop support for Java 7](https://github.com/google/guava/issues/5269), but...
- As @netdpb notes, [Android's copy of `Executable`](https://developer.android.com/reference/java/lang/reflect/Executable) doesn't support `getAnnotatedParameterTypes` to this day :( As I understand it, the information isn't available in their equivalent to JVM bytecode.
- To keep `NullPointerTester` tests working, we have historically annotated types with a declaration annotation -- sometimes just in the Android backport, sometimes in both "flavors" of Guava.

The long-term plan will likely be:
- drop Java 7 support
- use type annotations everywhere
- make `Parameter` use `getAnnotatedParameterTypes` when running in a JRE (but skip it when running under an Android VM)
- run `NullPointerTester` tests only under a JRE

I'm not sure if any of that helps with the immediate `NullPointerTester` issue you're encountering, though.

**Comment by mernst** [comment]
Chris, the long-term plan you laid out is actually very helpful.  Thanks!

I think I will just disable the NullPointerTests under Android for now, extricating myself from the rat's nest I have wandered into.
