### ISSUE TITLE
Creation of annotation processors

### ISSUE THREAD

**Issue by mluizaa00** [google/guava#5634]
Further looking at the Guava code, I have noted this project doesn't use the **standard** way to create the processor of a annotation such as `@Beta`. 
If I may ask, how is it made? Is it a individual Google Annotation API to generate those processors automatically?

I appreciate all the responses for this question.

**Comment by netdpb** [comment]
I'm not sure what you mean by "the standard way". `@Beta` is not handled by an annotation processor at all, but by an [Error Prone](http://errorprone.info) checker.

We use this issue tracker for bug reports and feature requests, and some other tasks. For general questions about Guava, please consult https://stackoverflow.com/questions/tagged/guava. Closing this issue since it's a question.
