### ISSUE TITLE
`InetAddresses.forString(String)` parses non-ASCII decimals

### ISSUE THREAD

**Issue by Marcono1234** [google/guava#5682]
The method `InetAddresses.forString(String)` parses non-ASCII decimals due to its usage of `Character.digit(...)`.
For example:
```java
// /127.0.0.1
System.out.println(InetAddresses.forString("127.0.0.\u0661"));
// /0:0:0:0:0:0:0:1
System.out.println(InetAddresses.forString("0:0:0:0:0:0:0:\u0661"));
```

While it appears there is no RFC which strictly specifies the syntax, related RFCs, such as [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#appendix-A) specifying the URI syntax, explicitly only allow ASCII `0`-`9` (respectively `f` for IPv6).
Additionally there is [this draft](https://datatracker.ietf.org/doc/html/draft-main-ipaddr-text-rep-00#section-3) which also only permits ASCII digits.

Note however, that Java's `InetAddress.getByName(String)` does support non-ASCII digits as well, though it is not clear whether that is intended or just an oversight.

(This issue might be relevant for #3417)

**Comment by eamonnmcmanus** [comment]
I made the appropriate change and tried it out against the full range of Google's internal tests. I found that some Google projects had tests explicitly verifying that addresses like `１２７.０.０.１` work, where those are "fullwidth" digits. We can fix the code in question so that it sanitizes non-ASCII digits before calling `InetAddresses.forString` (or the various other `InetAddresses` methods), but it seems a bit risky. I think it would be better to document that these methods accept non-ASCII digits, and explain how to reject them if you don't want that (for example `!CharMatcher.ascii().matchesAllOf(address)`. The fact that `java.net.InetAddress` and `java.net.URL` also accept non-ASCII digits does argue in favour of `InetAddresses` continuing to accept them.

I didn't see any test failures from requiring that the port number in `HostAndPort` be ASCII, and I think that change might be safer to make. (#5681)
