### ISSUE TITLE
Joiner.join(Object[]) doesn't accept null but is annotated with @Nullable

### ISSUE THREAD

**Issue by bjmi** [google/guava#5739]
_a4baad35_ introduces `@Nullable` at `Joiner.join(@Nullable Object[] parts)` but actual code would throw a _NullPointerException_.

**Comment by bjmi** [comment]
`@Nullable Object[] parts` means any element can be null but not _parts_. Working as intended.

**Comment by xihongshi6** [comment]
> `@Nullable Object[] parts` means any element can be null but not _parts_. Working as intended.

a little confusing, is this a rule that most people knowns?

**Comment by jbduncan** [comment]
@xihongshi6 I don't know about others, but it's a rule that I understand anyway.

All it is saying is the array cannot be null, but any of the objects in the array _can_ be null.

The reason why is because the `@Nullable` annotation is annotating the `Object` part of the array, rather than the `[]` part.

So this is allowed:

```java
Joiner.on(" ").join(new Object[]{ 1, null, "cat" });
```

But this is not allowed:

```java
Joiner.on(" ").join(null);
```

I hope this helps. :)

**Comment by xihongshi6** [comment]
> @xihongshi6 I don't know about others, but it's a rule that I understand anyway.
> 
> All it is saying is the array cannot be null, but any of the objects in the array _can_ be null.
> 
> The reason why is because the `@Nullable` annotation is annotating the `Object` part of the array, rather than the `[]` part.
> 
> So this is allowed:
> 
> ```java
> Joiner.on(" ").join(new Object[]{ 1, null, "cat" });
> ```
> 
> But this is not allowed:
> 
> ```java
> Joiner.on(" ").join(null);
> ```
> 
> I hope this helps. :)

Thank you for your detailed explanation! 

Maybe someone  see `@Nullable Object[] parts`, he think he can bind a `null` to parts, and get a `null` result, but unfortunately a `NullPointerException` was thrown. To some extend, it is ambiguous, because some people may think the `parts` can be `null`,  the others may think that any element can be `null`.  

Since we use it to annotate elements, we cannot annotate arrays with it, how do we describe a scene that an array can be `null`, but any element of the array cannot be `null`~

**Comment by jbduncan** [comment]
@xihongshi6 In this situation, the right thing to do is to annotate the array like so:

```java
public void someMethod(Object @Nullable [] array) {
}
```

Here, it tells us that the array itself (the `[]` part) can be null, whereas the elements inside cannot.

Likewise, to say that both the array itself and its elements can be null, one would do this:

```java
public void someMethod(@Nullable Object @Nullable [] array) {
}
```

I agree that it is ambiguous! But I think it's a limitation of how arrays and annotations work with each other in Java.

If you have any more Guava questions, may I suggest posting them over at StackOverflow? I look at the <kbd>guava</kbd> tag there often, so if you post with that tag, then I'll be likely to see it. Alternatively, if you have any questions that are just Java-related, post them under the <kbd>java</kbd> tag (I don't monitor questions with that tag), or send me an email. You can find my email address on my GitHub profile. :)
