### ISSUE TITLE
 Information Disclosure and Deserialization of Untrusted Data

### ISSUE THREAD

**Issue by AbstractAlao** [google/guava#5792]
I am maintaining an app that has all of the versions of guava listed as a critical vulnerability.

https://snyk.io/vuln/maven:com.google.guava%3Aguava

Is this a false positive because it says the remediation is to upgrade com.google.guava:guava to version 24.1.1-android, 24.1.1-jre or higher.

**Comment by jbduncan** [comment]
@AbstractAlao I could be wrong, but it looks to me that Guava 30.0-(jre|android)+ do not have any vulnerabilities according to that Snyk page. Is there something I'm missing? What happens if you upgrade to either of those versions?

**Comment by AbstractAlao** [comment]
Looks like that version also has the vulnerability as well. We upgraded to the latest and it still shows up.

![Screenshot_20211130-125316_Chrome](https://user-images.githubusercontent.com/58517851/144101267-28ce3ac3-1ed5-4da7-8d72-da46a292554e.jpg)

**Comment by jbduncan** [comment]
@AbstractAlao Oh, really? I ask because the latest versions of Guava are 31.0.1-jre and 31.0.1-android (see the [releases](https://github.com/google/guava/releases)), and https://snyk.io/vuln/maven:com.google.guava%3Aguava says that 30.1-(jre|android) don't have the security problems anymore, as far as I can tell.

![image](https://user-images.githubusercontent.com/2482228/144151525-bc630add-7647-4e4f-8661-81764d496894.png)

Specifically, it looks to me that Guava 29.0 is the last version to have any security vulnerabilities.

Your screenshot in your last message seems to confirm this, because I believe the syntax `[, 30.0-android),(30.0-android, 30.0-jre)` means that all versions up to _but not including_ 30.0-(jre|android) are affected.

What am I missing?

**Comment by netdpb** [comment]
I think @jbduncan has it correct here. It's not a false positive. The latest version of Guava has neither of those vulnerabilities.
