### ISSUE TITLE
Inconsistency in behavior between unmodifiable and immutable maps

### ISSUE THREAD

**Issue by WojciechZankowski** [google/guava#5874]
Hi, it might be not a real issue, but I am just rising it. 

```java
// JDK

final TreeMap<Integer, String> baseMap = new TreeMap<>() {{put(1, "one");}};

final NavigableMap<Object, Object> jdkUnmodifiableNavigableMap = Collections.unmodifiableNavigableMap(baseMap);
jdkUnmodifiableNavigableMap.compute(null, (k, v) -> v);

final SortedMap<Object, Object> jdkUnmodifiableSortedMap = Collections.unmodifiableSortedMap(baseMap);
jdkUnmodifiableSortedMap.compute(null, (k, v) -> v);

final Map<Object, Object> jdkUnmodifiableMap = Collections.unmodifiableMap(baseMap);
jdkUnmodifiableMap.compute(null, (k, v) -> v);

final Map<Integer, String> jdk11_ImmutableMap = Map.of(1, "one");
jdk11_ImmutableMap.compute(null, (k, v) -> v);

// Guava

final ImmutableMap<Integer, String> immutableMap = ImmutableMap.of(1, "one");
immutableMap.compute(null, (k, v) -> v);

final ImmutableSortedMap<Integer, String> guavaImmutableSortedMap = ImmutableSortedMap.of(1, "one");
guavaImmutableSortedMap.compute(null, (k, v) -> v);
```

and other immutable maps from guava will throw

```
java.lang.UnsupportedOperationException
```

At the same time there are 2 implementations in Guava library that have slightly different behavior:

```java
final TreeMap<Integer, String> baseMap = new TreeMap<>() {{put(1, "one");}};
final NavigableMap<Object, Object> guavaUnmodifiableNavigableMap = Maps.unmodifiableNavigableMap(baseMap);
guavaUnmodifiableNavigableMap.compute(null, (k, v) -> v);
```

will throw
```
java.lang.NullPointerException
```

And the other one will just silently go through. 

```java
final BiMap<Integer, String> baseBiMap = HashBiMap.create();
baseBiMap.put(1, "one");
final BiMap<Integer, String> unmodifiableBiMap = Maps.unmodifiableBiMap(baseBiMap);
unmodifiableBiMap.compute(null, (k, v) -> v);
```

I am not sure if this has been done on purpose by design or was just simply overseen. Happy to contribute if you would qualify it as a something to be changed.

**Comment by cgdecker** [comment]
I think this is intentional. The spec of `compute` allows methods that modify the map to either throw `UnsupportedOperationException` (as `ImmutableMap` does) or not throw it (as the `unmodifiableMap`s do) when the map would not actually be modified based on the actual input to the method.

`ImmutableMap` chooses to always throw since even _trying_ to modify an `ImmutableMap` means there's a programmer error somewhere that should be fixed. It also [is deprecated and documents that](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/collect/ImmutableMap.html#compute(K,java.util.function.BiFunction)). Personally I think `ImmutableMap`'s approach is better, but for better or worse that's not how `unmodifiableMap` does it, and I'm assuming with `unmodifiableBiMap` we chose to just match the JDK `unmodifiableMap` behavior.

**Comment by WojciechZankowski** [comment]
> I'm assuming with `unmodifiableBiMap` we chose to just match the JDK `unmodifiableMap` behavior.

That's actually my concern that ```Maps.unmodifiableNavigableMap()``` and ```Maps.unmodifiableBiMap()``` are not matching the behavior of JDK's ```unmodifiableMap```, JDK's ```immutableMap``` nor Guava's ```immutableMap```. 

Even the delegate behind ```Maps.unmodifiableNavigableMap()``` is ```Collections.unmodifiableSortedMap(delegate)```, but simply ```ForwardingMap``` goes to the default implementation from ```Map``` interface as it is stated in its javadoc. 

Anyway, if you think it is done intentionally then I must trust you. Thanks!

**Comment by cgdecker** [comment]
Ahh, sorry, I read what you were saying too quickly the first time and misunderstood completely. Now that I actually understand what you're saying, this does look like an oversight on our part to me. I think we should make `unmodifiableNavigableMap` and `unmodifiableBiMap` throw `UOE` for such methods like the rest.
