### ISSUE TITLE
the checkNotNull method in com.google.common.collect.Lists#newArrayList(E...) may not take effect

### ISSUE THREAD

**Issue by wxxlamp** [google/guava#6038]
when I code as follows：
```java
public class Test {
    public static void main(String[] args) {
        String a = null;
        System.out.println(Lists.newArrayList(a));
    }
}
```
And `[null]` will be output. It didn't throw an NullPointerException through `checknotnull` method because `E...` converted null parameter to a non-null parameter.

To fix this bug, it may be better to change `newArrayList(E...)` to `newArrayList(E e, E...)`

**Comment by cgdecker** [comment]
In general I agree that `newArrayList(E...)` can potentially cause some confusion, but:

- We aren't going to change its signature because that would be a breaking change.
- We also probably aren't going to add a new method because there's not much reason to use `newArrayList` now that `new ArrayList<>` is a thing.
- In this example it's clear that you aren't passing an array to the method, so I wouldn't expect it to throw NPE.
