### ISSUE TITLE
Convert a Map<String, String[]> to a delimited String in Guava

### ISSUE THREAD

**Issue by Montana** [google/guava#6050]
Hey all,

What is the best way to convert a Java `Map<String, String[]>` to a delimited String? Here's an example I did using Google Guava: 

```java
Map<String, String[]> items = new HashMap<>();
items.put("s1", new String[] {"abc", "def"});
items.put("s2", new String[] {"123", "456"});
System.out.println(Joiner.on(',').withKeyValueSeparator('=').join(items));
```

This does not flatten the `String[]`:

```java
s1=**[Ljava.lang.String;@2e98be86**,s2=[Ljava.lang.String;@b676908
```

Would something like this be more feasible? 

```java
Map<String, String[]> items = new HashMap<>();
items.put("s1", new String[] {"abc", "def"});
items.put("s2", new String[] {"123", "456"});

System.out.println(items.entrySet().stream().map(es -> es.getKey() + "=" + String.join(",", es.getValue())).collect(
    Collectors.toList()));
```

Thank you so much,
Montana Mendy

**Comment by netdpb** [comment]
This issues list is for bugs or feature requests for Guava, not usually for general questions. [Stack Overflow](http://stackoverflow.com) is a better resource.

However, I'll tell you this: your first example doesn't work because Java arrays don't implement `toString()`. However, collections like `List` do, so you could do something like

```
Joiner.on(',').withKeyValueSeparator('=').join(
    Maps.transformValues(items, values -> Arrays.asList(values)))
```

which should get you something like

```
s1=[abc, def, ghi],s2=[123, 456, 789]
```

If you want something different for the values, you could use a `Joiner` on them:

```
Joiner.on(',').withKeyValueSeparator('=').join(
    Maps.transformValues(items, values -> Joiner.on(':').join(values)))
```

which should give you

```
s1=abc:def:ghi,s2=123:456:789
```
