### ISSUE TITLE
Memory Leak Issue

### ISSUE THREAD

**Issue by Abexope** [google/guava#6091]
Java 8, Guava Version is 20.0. I have analyzed my application memory consumption and found suspicious memory leak. My code is as follows:

private LoadingCache<Long, Set<Long>> crossMemberCache =
        CacheBuilder
            .newBuilder()
            .expireAfterWrite(5, TimeUnit.MINUTES)
            .maximumSize(500000)
            .build(new CacheLoader<Long, Set<Long>>() {
                @Override
                public Set<Long> load(Long key) throws Exception {
                    Map<Long, Set<Integer>> map =
                        ginfoClient.getTempRoomMembers(key);  // RPC call
                    return map.keySet();
                }
            });

as above code, the expireAfterWrite is 5min. However, in these heap monitor figure, the usage of JVM heap space exceeded 80% for more than 3 hours until I restart application.

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/50110585/175960975-b13434dd-b6d8-4f47-baa2-ba2c67602aaf.png">

<img width="1614" alt="image" src="https://user-images.githubusercontent.com/50110585/175961302-7ae2d6db-2ba0-460d-9875-f8d21f996a96.png">

<img width="1589" alt="image" src="https://user-images.githubusercontent.com/50110585/175961378-aa79d2f2-a849-4223-93f7-f06e61e11c0b.png">

**Comment by ben-manes** [comment]
If your cache is not being read or written to, then there is nothing to trigger the cache to discard those expired entries. The cleanup behavior is described on `CacheBuilder` and on the [wiki](https://github.com/google/guava/wiki/CachesExplained#when-does-cleanup-happen). If you would like prompt expiration via a background scheduling thread, you can either periodically call `cache.cleanUp()` or use Caffeine and its [scheduler](https://github.com/ben-manes/caffeine/wiki/Cleanup) feature.

The eviction policy is set to a high entry count, but it holds variably sized collections. That could cause it to stay within the size threshold while using excessive memory. Instead consider using a `Weigher` and a `maximumWeight`, e.g. based on the number of items in your collection. In addition, the `map.keySet()` is a view so its heavy-weight values are retained but are not accessible. You might use `ImmutableSet.copyOf(map.keySet())` avoid that.

It is generally recommend to enable statistics for large or important caches so that you can better understand your application's behavior through metrics.

Version 20.0 was released in 2016, whereas the current release v31.1 came out this February. Please use newer versions to minimize your impact to bugs, as using ancient versions can lead you to rediscover a long fixed issue. Your build tool likely has a dependency updates feature (e.g. [versions-maven-plugin](https://www.mojohaus.org/versions-maven-plugin), [gradle-versions-plugin](https://github.com/ben-manes/gradle-versions-plugin)).

**Comment by eamonnmcmanus** [comment]
Thanks @ben-manes for the detailed explanation. I'm closing this, since it appears there is no bug here.
