### ISSUE TITLE
ValueGraph.edges() doesn't return the edge value

### ISSUE THREAD

**Issue by AllysonPemberton-UnlikelyAI** [google/guava#6361]
When you add an edge to a `ValueGraph` with `.putEdgeValue(...)` you give it two nodes and an edge value. However when you access all the edges with `ValueGraph.edges` it only returns the nodes, it doesn't return the edge value. This means that when iterating through `ValueGraph.edges` we have to call `edgeValue` for each node pair to get the complete information.

It would be great if there was a function that returned all the edges with all three pieces (both nodes and the edge value).

**Comment by jrtom** [comment]
@AllysonPemberton-UnlikelyAI 
- what would you expect/want this API to look like?  
- what practical issues are you having with the API in its current state?  (That is: what problem are you trying to solve?  Needing to call `edgeValue()` for each element returned by `edges()` doesn't seem like a huge burden.)

If you just want a `Map<EndpointPair<N>, V>` for the `ValueGraph`, instead of just the `Set<EndpointPair<N>` that `ValueGraph.edges()` provides, you can do this with something like the following code:

```
Map<EndpointPair<N>, V> edgeValues = Maps.asMap(valueGraph.edges(), ValueGraph::edgeValue);
```

(ref: https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/collect/Maps.html#asMap(java.util.Set,com.google.common.base.Function))

**Comment by AllysonPemberton-UnlikelyAI** [comment]
Nice! Yea we need to iterate over all the <EndpointPair, EdgeValue> pairs, so that map will help shorten the code I've written. 

That works fine for us, but it seems to me like that would be a useful API to have within the graph itself. Given that the edges have edgeValues in a ValueGraph, I'd almost be surprised to have a time where you need to access the edges _without_ the edgeValues. 

Feel free to close if you don't think it's worth adding, as we can use the Map.

**Comment by jrtom** [comment]
My feeling is that since there's a one-liner (with no additional dependencies) that provides the `Map` view that's wanted, we're not eager to expand the API.  

Also worth noting that if we were to add an 'edgeValues()` API such as you suggested, we'd need to at least consider doing the same thing for `ValueGraph.incidentEdges()`: https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/graph/ValueGraph.html#incidentEdges(N)
so there's a bit of a slippery slope concern there.

I'm still curious about your use case, i.e., what you're trying to do such that iterating over `edges()` and calling `edgeValue()` for each one doesn't seem like a good fit.  This is what I'm imagining:

with the notional `ValueGraph.edgeValues()`, or the `Map` generated by `Maps.asMap()`:
```
for (Map.Entry<EndpointPair<N>, V> edgeValue : edgeValues()) {
  EndpointPair<N, V> endpoints = edgeValue.getKey();
  V value = edgeValue.getValue();
  ...
}
```

without that API:
```
for (EndpointPair<N> endpoints : valueGraph.edges()) {
  V value = valueGraph.edgeValue(endpoints);
  ...
}
```

To me the second option looks cleaner and easier to read, but I may be misunderstanding your goal.

(Note that our `ValueGraph` implementation doesn't store the `Map` that you want explicitly internally, as it turns out to be more efficient to represent that `Map` implicitly, so if we did provide an `edgeValues()` method it would almost certainly simply be syntactic sugar for the `Maps.asMap` call.)

FYI, the reason why you might want to access the edges without the values is if you're doing something with the graph for which the edge values aren't relevant.  You can of course use the `Graph` view (`ValueGraph.asGraph()`) for that but if your input needs to be a `ValueGraph` for other reasons then there's no reason to create that view just to give you the edges without providing access to the values.

If we do think that telling people how to use `Maps.asMap()` to generate this view would be useful, we could certainly consider updating the documentation (e.g. for `ValueGraph.edges()`) to mention it.

Would be interested in your feedback/additional thoughts.

**Comment by jrtom** [comment]
Thanks for the additional context, that's helpful.

I'm sure that some of this is just because I was using Java long before Streams came out, but I feel like this is one of those cases where Streams may not make the code more clear.  :)

Note that since you're iterating over the edges, you don't have to check for presence of the Optional (ValueGraph is guaranteed to have a value for each edge in the graph), so this could be a bit simpler:

```
ValueGraph<Node, EdgeValue> newGraph = ValueGraphBuilder.from(oldGraph).build();
for (EndpointPair<Node> endpoints : oldGraph.edges()) {
  newGraph.putEdgeValue(modify(endpoints), oldGraph.edgeValue(endpoints).get());
}
```

(and similarly for the other examples).

Based on your example I think I'm reasonably comfortable with saying that we probably don't want to add the new method, but if you come up with further arguments that this would be useful, please reopen this issue.
