### ISSUE TITLE
TempFileCreator throws strange exceptions

### ISSUE THREAD

**Issue by tohidemyname** [google/guava#6598]
When it fails to create a directory, it throws IllegalStateException, but when it fails to create a file, it throws IOException. It looks strange. Why does the class handle the same type of errors differently?

**Comment by cpovirk** [comment]
If I had to guess, I'd say that the root cause is that whoever wrote `Files.createTempDir` (over 15 years ago!) was not a huge fan of checked exceptions :)

And then we never got around to changing it. If we want to give ourselves some credit, we could argue that we never bothered because the operation is very unlikely to fail—and so there was little upside to the disruption that a change in exception type would cause for users.

So then why didn't we at least change `FileBackedOutputStream` to be consistent? Well, it's very rarely used to begin with, so that's one reason not to bother (and, admittedly, also a reason _to_ bother, since a change would cause less disruption :)). But beyond that, `FileBackedOutputStream` implements an API that already declares that it throws checked exceptions. So callers already are likely to have to handle `IOException`, and thus there's less advantage to avoiding checked exceptions (and even some downside from departing from the usual.)

(In principle, this question would fit well on https://groups.google.com/g/guava-discuss.)
