### ISSUE TITLE
Issue with `graph`-related release notes for `32.1.3`

### ISSUE THREAD

**Issue by jbduncan** [google/guava#6769]
The [release notes for 32.1.3](https://github.com/google/guava/releases/tag/v32.1.3) say,

> - `graph`: Fixed the behavior of Graph/ValueGraph views for a node when that node is removed from the graph.

However, I believe this was [rolled back](https://github.com/google/guava/commit/0a30cc3551bfcfc44c08e7358226d53e215519f7), and so the respective text in the release notes should be removed.

What do you think?

**Comment by cpovirk** [comment]
Thanks. If I did things right, the release does not contain the rollback because I released from an earlier commit (plus a cherry pick): https://github.com/google/guava/commits/v32.1.3

This of course raises the question of whether it _should_ contain the rollback :) We rolled back because we broke a test, but we ended up finding that the bug was in the test, and then graph change merely exposed it. (The graph change had previously exposed another old, mysterious bug, so it has a pretty good track record already :)) We have a roll-forward already reviewed, so that should be coming soon.

**Comment by jbduncan** [comment]
@cpovirk Oh, you're right, silly me! Thanks for pointing out my mistake. Great to hear that the rollback was only internal test-related. :)

**Comment by cpovirk** [comment]
And today it was my turn to get worried about whether we ever actually rolled it forward :) It turns out that we did about a week and a half after our conversation here. See https://github.com/google/guava/commit/9c6b9d956e86856ee5284c65a294971fc0cd1fd0.
