### ISSUE TITLE
open access to constuct HashBasedTable object for supporting deserializer

### ISSUE THREAD

**Issue by Dynasty-develop** [google/guava#6893]
### 1. What are you trying to do?

first build some HashBasedTable objects, then serializer them for store, eg redis.. But when i need to use them, i have a fail for deserializer them. Because the HashBasedTable cann`t expose contructure.

### 2. What's the best code you can write to accomplish that without the new feature?

public HashBasedTable(Map<R, Map<C, V>> backingMap);

### 3. What would that same code look like if we added your feature?

public HashBasedTable(Map<R, Map<C, V>> backingMap);

### Concrete Use Cases

I need to use this scenario in which I serializer/ deserializer the HashBasedTable object.

### Packages

com.google.common.collect

### Checklist

- [X] I agree to follow the [code of conduct](https://github.com/google/.github/blob/master/CODE_OF_CONDUCT.md).

- [X] I have read and understood the [contribution guidelines](https://github.com/google/guava/wiki/HowToContribute#feature-requests).

- [X] I have read and understood [Guava's philosophy](https://github.com/google/guava/wiki/PhilosophyExplained), and I strongly believe that this proposal aligns with it.

- [X] I have visited the [idea graveyard](https://github.com/google/guava/wiki/IdeaGraveyard), and did not see anything similar to this idea.

**Comment by Shreyanshsingh23** [comment]
can I be assigned this task ?

**Comment by Shreyanshsingh23** [comment]
While it would be convenient to have a public constructor for HashBasedTable to support easier serialization and deserialization, it's important to note that the Guava library designers have intentionally chosen not to expose a public constructor for HashBasedTable. This design decision is likely due to the complexity and internal structure of the table, and they may have considered it safer to provide factory methods for creating instances.

If you still wish to have a public constructor for HashBasedTable, you could consider creating a wrapper class that extends HashBasedTable and exposes the constructor you need. This way, you can have a deserialization-friendly class while still keeping the internal implementation of HashBasedTable encapsulated.

**Comment by eamonnmcmanus** [comment]
Could you say a bit more about the problem you are seeing? It should normally be possible to serialize and deserialize a `HashBasedTable`, as verified by [this test](https://github.com/google/guava/blob/25ff2376be7662f973c321a63537ca09169bce88/guava-tests/test/com/google/common/collect/HashBasedTableTest.java#L95). Are we talking about something other than [Java Serialization](https://docs.oracle.com/en/java/javase/21/docs/specs/serialization/index.html)?

A code sample that shows the problem would help us understand it.

> If you still wish to have a public constructor for HashBasedTable, you could consider creating a wrapper class that extends > HashBasedTable and exposes the constructor you need.

Unfortunately that isn't possible as such. `HashBasedTable` doesn't have a visible constructor, so it can't be subclassed. But it would be possible to make a wrapper class that _contains_ a `HashBasedTable` and use that for the serialization and deserialization. The [`ForwardingTable`](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/collect/ForwardingTable.html) class would be useful for this.

**Comment by jrtom** [comment]
In general, these days Guava follows the [guidance](https://www.oreilly.com/library/view/effective-java-3rd/9780134686097/ch12.xhtml) of Effective Java item 74 (2d edition; item 85 in the 3d edition): "Prefer alternatives to Java serialization".  (Guava's "[important warnings](https://github.com/google/guava#important-warnings)", item 4, is a consequence of this.)

Basically, Java serialization is fragile (because it depends on details of internal implementation which may change) and we don't recommend using it.  This is why (for instance) the common.graph types we released several years ago [don't implement Serializable](https://github.com/google/guava/issues/2651).

**Comment by eamonnmcmanus** [comment]
Closing for lack of response. @Dynasty-develop feel free to reopen if there is more to say.
