### ISSUE TITLE
Add action version comments in GitHub workflow files

### ISSUE THREAD

**Issue by Marcono1234** [google/guava#7068]
The GitHub workflow files of Guava currently refer to action versions by commit hash, for example:
https://github.com/google/guava/blob/a6a34dc42627f2dc5b8937f428322739b74ce8f3/.github/workflows/ci.yml#L69-L70

While this is good from a security perspective, it makes it difficult at a glance to see which version number (such as "v1.2.3") of that action is used.

What do you think about adding version comments, such as `# v1.2.3`, behind the commit hashes? It seems Dependabot will [automatically update those comments](https://github.blog/changelog/2022-10-31-dependabot-now-updates-comments-in-github-actions-workflows-referencing-action-versions/).

**Comment by cpovirk** [comment]
Thanks, adding them should be fine. I dropped them when I switched to hashes because it was ever so slightly easier and because it's not as if there is a runtime check that verifies that the comment is actually accurate. Now, I don't think that the latter is a practical concern because the values are always generated by Dependabot, which we trust. On the other hand, probably nothing we do here is of great practical significance because... we trust Dependabot to update as as soon as a problem is identified (and/or for security advisories to recognize the vulnerable version by its hash, I _hope_, or at least I hope that _it_ doesn't trust the comment!).

**Comment by cpovirk** [comment]
Fun fact: Dependabot got the version numbers wrong recently, as noted near the top of the description of https://github.com/google/guava/pull/8039 :) I missed it entirely, but netdpb caught it.

**Comment by Marcono1234** [comment]
Gson is affected by that as well (https://github.com/google/gson/pull/2916). Probably affects quite a lot of projects, and apparently Dependabot will not fix that itself once there is a mismatch.

**Comment by cpovirk** [comment]
Version comments are now being checked by [`zizmor`](https://docs.zizmor.sh/). Mismatches will turn the _pre-merge_ CI red. But there's the caveat that I still need to set up our Copybara pushes to block on that.
